(function attachCoreVocabSenseChecklist(root, checklist) {
  if (typeof module !== "undefined" && module.exports) {
    module.exports = checklist;
  }
  root.CORE_VOCAB_SENSE_CHECKLIST = checklist;
})(typeof globalThis !== "undefined" ? globalThis : window, [
  { word: "water", label: "n. 水" },
  { word: "water", label: "v. 澆水" },
  { word: "work", label: "n. 工作" },
  { word: "work", label: "n. 作品" },
  { word: "work", label: "v. 工作 / 做事" },
  { word: "work", label: "v. 運作 / 奏效" },
  { word: "have", label: "v. 有" },
  { word: "have", label: "v. 食 / 飲" },
  { word: "play", label: "v. 玩 / 打（球類）" },
  { word: "play", label: "v. 演奏" },
  { word: "play", label: "n. 戲劇" },
  { word: "paper", label: "n. 紙" },
  { word: "paper", label: "n. 報紙 / 文件 / 試卷" },
  { word: "school", label: "n. 學校" },
  { word: "room", label: "n. 房間" },
  { word: "room", label: "n. 空間" },
  { word: "watch", label: "v. 觀看" },
  { word: "watch", label: "n. 手錶" },
  { word: "book", label: "n. 書" },
  { word: "book", label: "v. 預訂" },
  { word: "right", label: "adj. 正確的" },
  { word: "right", label: "adj. 右邊的" },
  { word: "right", label: "n. 權利" },
  { word: "right", label: "adv. 向右" },
  { word: "left", label: "adj. 左邊的" },
  { word: "left", label: "adv. 向左" },
  { word: "left", label: "adv. 在左邊" },
  { word: "left", label: "v. 離開了（leave 的過去式 / PP）" },
  { word: "left", label: "v. 留下了（leave 的過去式 / PP）" },
  { word: "close", label: "v. 關閉" },
  { word: "close", label: "adj. 接近的" },
  { word: "close", label: "adj. 親密的" },
  { word: "clean", label: "adj. 乾淨的" },
  { word: "clean", label: "v. 清潔" },
  { word: "face", label: "n. 臉" },
  { word: "face", label: "v. 面對" },
  { word: "hand", label: "n. 手" },
  { word: "hand", label: "v. 交給 / 遞給" },
  { word: "head", label: "n. 頭" },
  { word: "head", label: "v. 前往 / 率領" },
  { word: "take", label: "v. 拿" },
  { word: "take", label: "v. 取" },
  { word: "take", label: "v. 帶" },
  { word: "take", label: "v. 乘搭" },
  { word: "take", label: "v. 花費（時間）" },
  { word: "get", label: "v. 得到" },
  { word: "get", label: "v. 取得" },
  { word: "get", label: "v. 收到" },
  { word: "get", label: "v. 變得" },
  { word: "get", label: "v. 到達" },
  { word: "make", label: "v. 製作" },
  { word: "make", label: "v. 製造" },
  { word: "make", label: "v. 使" },
  { word: "make", label: "v. 令" },
  { word: "stand", label: "v. 站立" },
  { word: "stand", label: "n. 攤位" },
  { word: "train", label: "n. 火車" },
  { word: "train", label: "v. 訓練" },
  { word: "fly", label: "v. 飛" },
  { word: "fly", label: "n. 蒼蠅" },
  { word: "draw", label: "v. 畫畫" },
  { word: "draw", label: "v. 吸引" },
  { word: "give", label: "v. 給 / 交給" },
  { word: "put", label: "v. 放 / 擺" },
  { word: "come", label: "v. 來" },
  { word: "come", label: "v. 到達" },
  { word: "look", label: "v. 看" },
  { word: "look", label: "v. 看起來" },
  { word: "see", label: "v. 看見" },
  { word: "see", label: "v. 明白" },
  { word: "say", label: "v. 說" },
  { word: "tell", label: "v. 告訴" },
  { word: "tell", label: "v. 講述" },
  { word: "ask", label: "v. 問" },
  { word: "ask", label: "v. 要求" },
  { word: "call", label: "v. 打電話" },
  { word: "call", label: "v. 稱呼" },
  { word: "call", label: "n. 電話" },
  { word: "answer", label: "v. 回答" },
  { word: "answer", label: "n. 答案" },
  { word: "point", label: "n. 分數 / 重點 / 點" },
  { word: "point", label: "v. 指向" },
  { word: "class", label: "n. 班級" },
  { word: "class", label: "n. 課堂" },
  { word: "class", label: "n. 分類 / 類別" },
  { word: "table", label: "n. 桌子" },
  { word: "table", label: "n. 表格" },
  { word: "date", label: "n. 日期" },
  { word: "date", label: "n. 約會" },
  { word: "story", label: "n. 故事" },
  { word: "story", label: "n. 樓層 / 層" },
  { word: "letter", label: "n. 信" },
  { word: "letter", label: "n. 字母" },
  { word: "minute", label: "n. 分鐘" },
  { word: "minute", label: "adj. 極小的" },
  { word: "past", label: "n. 過去" },
  { word: "past", label: "adj. 過去的" },
  { word: "past", label: "prep. 經過" },
  { word: "well", label: "adv. 好" },
  { word: "well", label: "adj. 健康的" },
  { word: "well", label: "n. 井" },
  { word: "fine", label: "adj. 好的 / 不錯的" },
  { word: "fine", label: "n. 罰款" },
  { word: "free", label: "adj. 免費的" },
  { word: "free", label: "adj. 自由的" },
  { word: "free", label: "v. 釋放" },
  { word: "poor", label: "adj. 貧窮的 / 差的 / 可憐的" },
  { word: "light", label: "n. 光" },
  { word: "light", label: "n. 燈" },
  { word: "light", label: "adj. 輕的" },
  { word: "light", label: "adj. 淺色的" },
  { word: "kind", label: "n. 種類" },
  { word: "kind", label: "adj. 友善的" },
  { word: "hard", label: "adj. 困難的" },
  { word: "hard", label: "adj. 硬的" },
  { word: "hard", label: "adv. 努力地" },
  { word: "mean", label: "v. 意思是 / 意味著" },
  { word: "mean", label: "adj. 刻薄的" },
  { word: "mean", label: "adj. 吝嗇的" },
  { word: "change", label: "v. 改變" },
  { word: "change", label: "n. 變化" },
  { word: "change", label: "n. 零錢" },
  { word: "turn", label: "v. 轉動" },
  { word: "turn", label: "v. 轉彎" },
  { word: "turn", label: "n. 輪流" },
  { word: "turn", label: "n. 次序" },
  { word: "plant", label: "n. 植物" },
  { word: "plant", label: "n. 工廠" },
  { word: "plant", label: "v. 種植" },
  { word: "fall", label: "v. 跌倒" },
  { word: "fall", label: "v. 下降" },
  { word: "fall", label: "n. 秋天" },
  { word: "sound", label: "n. 聲音" },
  { word: "sound", label: "v. 聽起來" },
  { word: "sound", label: "adj. 合理的" },
  { word: "sound", label: "adj. 可靠的" },
  { word: "match", label: "n. 比賽 / 配對" },
  { word: "match", label: "v. 配對" },
  { word: "match", label: "v. 相配" },
  { word: "match", label: "v. 相襯" },
  { word: "present", label: "n. 禮物" },
  { word: "present", label: "adj. 在場的" },
  { word: "present", label: "v. 呈現" },
  { word: "present", label: "v. 展示" },
  { word: "order", label: "n. 次序 / 命令 / 訂單" },
  { word: "order", label: "v. 訂購" },
  { word: "order", label: "v. 命令" },
  { word: "subject", label: "n. 科目" },
  { word: "subject", label: "n. 主題" },
  { word: "break", label: "v. 打破" },
  { word: "break", label: "v. 弄壞" },
  { word: "break", label: "n. 小休 / 休息" },
  { word: "park", label: "n. 公園" },
  { word: "park", label: "v. 泊車" },
  { word: "orange", label: "n. 橙" },
  { word: "orange", label: "adj. 橙色的" },
  { word: "rule out", label: "v. 排除 / 不考慮" },
  { word: "bacon", label: "n. 煙肉 / 培根" },
  { word: "back", label: "n. 背部" },
  { word: "back", label: "adj. 後面的" },
  { word: "back", label: "adv. 回去 / 向後" },
  { word: "clear", label: "adj. 清楚的 / 明確的" },
  { word: "clear", label: "v. 清除 / 清理" },
  { word: "drop", label: "v. 掉下 / 下降" },
  { word: "drop", label: "n. 一滴" },
  { word: "field", label: "n. 田野 / 運動場" },
  { word: "field", label: "n. 領域 / 範疇" },
  { word: "fit", label: "v. 適合 / 合身" },
  { word: "fit", label: "adj. 健康的" },
  { word: "note", label: "n. 筆記 / 便條" },
  { word: "note", label: "v. 注意 / 留意" },
  { word: "plain", label: "adj. 簡單的 / 樸素的" },
  { word: "plain", label: "n. 平原" },
  { word: "rest", label: "n. 休息" },
  { word: "rest", label: "n. 其餘部分" },
  { word: "rest", label: "v. 休息" },
  { word: "round", label: "adj. 圓的" },
  { word: "round", label: "n. 回合 / 一輪" },
  { word: "sense", label: "n. 感覺 / 意識" },
  { word: "sense", label: "n. 道理 / 意義" },
  { word: "stick", label: "n. 棍 / 枝條" },
  { word: "stick", label: "v. 黏住 / 貼住" },
  { word: "store", label: "n. 商店" },
  { word: "store", label: "v. 儲存" },
  { word: "strike", label: "n. 罷工" },
  { word: "strike", label: "v. 撞擊 / 打" },
  { word: "strong", label: "adj. 強壯的" },
  { word: "strong", label: "adj. 強烈的" },
  { word: "support", label: "v. 支持" },
  { word: "support", label: "n. 支持 / 支援" },
  { word: "tie", label: "n. 領帶" },
  { word: "tie", label: "v. 綁 / 打成平手" },
  { word: "trip", label: "n. 旅行" },
  { word: "trip", label: "v. 絆倒" },
  { word: "wave", label: "n. 波浪" },
  { word: "wave", label: "n. 揮手" },
  { word: "wave", label: "v. 揮手" },
  { word: "wear", label: "v. 穿 / 戴" },
  { word: "yard", label: "n. 院子" },
  { word: "bear", label: "n. 熊" },
  { word: "bear", label: "v. 忍受" },
  { word: "check", label: "v. 檢查" },
  { word: "check", label: "n. 檢查" },
  { word: "check", label: "n. 賬單" },
  { word: "pretty", label: "adj. 漂亮的" },
  { word: "pretty", label: "adv. 頗 / 相當" },
  { word: "beard", label: "n. 鬍鬚" },
  { word: "hammer", label: "n. 錘子" },
  { word: "hammer", label: "v. 用錘敲打" },
  { word: "swift", label: "adj. 迅速的 / 敏捷的" },
  { word: "won't", label: "modal v. 不會 / 將不會" },
  { word: "ought to", label: "modal v. 應該" },
  { word: "delicacy", label: "n. 佳餚" },
  { word: "delicacy", label: "n. 精緻 / 微妙" },
  { word: "cub", label: "n. 幼獸" },
  { word: "validity", label: "n. 有效性 / 合理性" },
  { word: "lift", label: "v. 解除 / 撤銷限制" },
  { word: "egg tart", label: "n. 蛋撻" },
  { word: "lung cancer", label: "n. 肺癌" },
  { word: "power", label: "n. 力量" },
  { word: "power", label: "n. 能力" },
  { word: "power", label: "n. 權力" },
  { word: "power", label: "n. 電力" },
  { word: "physical", label: "adj. 身體的" },
  { word: "physical", label: "adj. 物理的" },
  { word: "image", label: "n. 圖像" },
  { word: "image", label: "n. 形象" },
  { word: "lose", label: "v. 失去" },
  { word: "lose", label: "v. 輸掉" },
  { word: "number", label: "n. 數字" },
  { word: "number", label: "n. 號碼" },
  { word: "number", label: "v. 編號" },
  { word: "number", label: "v. 數算" },
  { word: "movement", label: "n. 移動" },
  { word: "movement", label: "n. 運動" },
  { word: "particular", label: "adj. 特定的" },
  { word: "particular", label: "adj. 特別的" },
  { word: "purpose", label: "n. 目的" },
  { word: "purpose", label: "n. 用途" },
  { word: "stop", label: "n. 車站" },
  { word: "stop", label: "n. 停止" },
  { word: "study", label: "v. 學習" },
  { word: "study", label: "v. 研究" },
  { word: "around", label: "prep. 在...周圍" },
  { word: "around", label: "adv. 到處" },
  { word: "around", label: "adv. 大約" },
  { word: "by", label: "prep. 由" },
  { word: "by", label: "prep. 被" },
  { word: "by", label: "prep. 靠近" },
  { word: "by", label: "adv. 經過" },
  { word: "could", label: "modal v. 可以" },
  { word: "could", label: "modal v. 可能" },
  { word: "could", label: "modal v. 能夠" },
  { word: "just", label: "adv. 只是" },
  { word: "just", label: "adv. 剛剛" },
  { word: "just", label: "adv. 正好" },
  { word: "may", label: "modal v. 可能" },
  { word: "may", label: "modal v. 可以" },
  { word: "will", label: "modal v. 將會" },
  { word: "will", label: "n. 意志" },
  { word: "will", label: "n. 遺囑" },
  { word: "with", label: "prep. 和...一起" },
  { word: "with", label: "prep. 帶有" },
  { word: "with", label: "prep. 使用" },
  { word: "would", label: "modal v. 會" },
  { word: "would", label: "modal v. 願意" },
  { word: "event", label: "n. 活動" },
  { word: "event", label: "n. 事件" },
  { word: "move", label: "v. 移動" },
  { word: "move", label: "v. 搬動" },
  { word: "move", label: "v. 感動" },
  { word: "move", label: "n. 行動" },
  { word: "experience", label: "n. 經驗" },
  { word: "experience", label: "n. 經歷" },
  { word: "experience", label: "v. 經歷" },
  { word: "experience", label: "v. 體驗" },
  { word: "expression", label: "n. 表達" },
  { word: "expression", label: "n. 表情" },
  { word: "feature", label: "n. 特色" },
  { word: "feature", label: "n. 特徵" },
  { word: "feature", label: "v. 以...為特色" },
  { word: "feature", label: "v. 由...主演" },
  { word: "process", label: "n. 過程" },
  { word: "process", label: "n. 程序" },
  { word: "process", label: "v. 處理" },
  { word: "process", label: "v. 加工" },
  { word: "rise", label: "v. 上升" },
  { word: "rise", label: "v. 升起" },
  { word: "rise", label: "n. 上升" },
  { word: "rise", label: "n. 增加" },
  { word: "sign", label: "n. 標誌" },
  { word: "sign", label: "n. 跡象" },
  { word: "sign", label: "v. 簽署" },
  { word: "sign", label: "v. 簽名" },
  { word: "shape", label: "v. 塑造" },
  { word: "shape", label: "v. 影響" },
  { word: "keep", label: "v. 保留" },
  { word: "keep", label: "v. 留著" },
  { word: "meet", label: "v. 遇見" },
  { word: "meet", label: "v. 見面" },
  { word: "experiment", label: "v. 進行實驗" },
  { word: "experiment", label: "v. 嘗試" },
  { word: "following", label: "adj. 以下的" },
  { word: "following", label: "adj. 接著的" },
  { word: "following", label: "n. 追隨者" },
  { word: "mobile", label: "adj. 流動的" },
  { word: "mobile", label: "adj. 可移動的" },
  { word: "notice", label: "n. 告示" },
  { word: "notice", label: "n. 通知" },
  { word: "develop", label: "v. 發展" },
  { word: "develop", label: "v. 成長" },
  { word: "develop", label: "v. 培養" },
  { word: "develop", label: "v. 形成" },
  { word: "produce", label: "v. 生產" },
  { word: "produce", label: "v. 製造" },
  { word: "produce", label: "n. 農產品" },
  { word: "produce", label: "n. 農作物" },
  { word: "separate", label: "v. 分開" },
  { word: "separate", label: "v. 分離" },
  { word: "separate", label: "adj. 分開的" },
  { word: "separate", label: "adj. 獨立的" },
  { word: "survey", label: "n. 問卷調查" },
  { word: "survey", label: "n. 調查" },
  { word: "request", label: "n. 要求" },
  { word: "request", label: "n. 請求" },
  { word: "request", label: "v. 要求" },
  { word: "request", label: "v. 請求" },
  { word: "specific", label: "adj. 特定的" },
  { word: "specific", label: "adj. 具體的" },
  { word: "consider", label: "v. 認為" },
  { word: "consider", label: "v. 視為" },
  { word: "several", label: "det. 幾個 / 數個" },
  { word: "several", label: "pron. 幾個 / 數個" },
  { word: "industry", label: "n. 行業" },
  { word: "industry", label: "n. 工業" },
  { word: "ancient", label: "adj. 古代的" },
  { word: "ancient", label: "adj. 古老的" },
  { word: "audience", label: "n. 觀眾" },
  { word: "audience", label: "n. 聽眾" },
  { word: "code", label: "n. 代碼" },
  { word: "code", label: "n. 編碼" },
  { word: "drug", label: "n. 藥物" },
  { word: "drug", label: "n. 毒品" },
  { word: "identify", label: "v. 辨認" },
  { word: "identify", label: "v. 識別" },
  { word: "introduce", label: "v. 介紹" },
  { word: "introduce", label: "v. 引入" },
  { word: "join", label: "v. 加入" },
  { word: "join", label: "v. 參加" },
  { word: "know", label: "v. 知道" },
  { word: "know", label: "v. 認識" },
  { word: "alternative", label: "n. 替代品" },
  { word: "alternative", label: "n. 另一選擇" },
  { word: "alternative", label: "adj. 替代的" },
  { word: "involve", label: "v. 涉及" },
  { word: "involve", label: "v. 牽涉" },
  { word: "ordinary", label: "adj. 平凡的" },
  { word: "ordinary", label: "adj. 普通的" },
  { word: "rather", label: "adv. 頗" },
  { word: "rather", label: "adv. 相當" },
  { word: "rather", label: "adv. 反而" },
  { word: "desert", label: "v. 遺棄" },
  { word: "desert", label: "v. 離棄" },
  { word: "country", label: "n. 國家" },
  { word: "country", label: "n. 鄉郊" },
  { word: "late", label: "adj. 遲的" },
  { word: "late", label: "adj. 晚的" },
  { word: "late", label: "adv. 遲" },
  { word: "late", label: "adv. 晚" },
  { word: "moment", label: "n. 時刻" },
  { word: "moment", label: "n. 片刻" },
  { word: "be", label: "v. 是" },
  { word: "be", label: "v. 成為" },
  { word: "do", label: "v. 做" },
  { word: "do", label: "v. 進行" },
  { word: "form", label: "n. 形式" },
  { word: "form", label: "n. 形態" },
  { word: "form", label: "v. 形成" },
  { word: "form", label: "v. 組成" },
  { word: "list", label: "n. 清單" },
  { word: "list", label: "n. 名單" },
  { word: "description", label: "n. 描述" },
  { word: "description", label: "n. 說明" },
  { word: "detail", label: "n. 詳情" },
  { word: "detail", label: "n. 細節" },
  { word: "picture", label: "n. 圖畫" },
  { word: "picture", label: "n. 相片" },
  { word: "picture", label: "v. 想像" },
  { word: "picture", label: "v. 描繪" },
  { word: "regular", label: "adj. 定期的" },
  { word: "regular", label: "adj. 規則的" },
  { word: "stage", label: "v. 上演" },
  { word: "stage", label: "v. 舉辦" },
  { word: "thought", label: "n. 想法" },
  { word: "thought", label: "n. 念頭" },
  { word: "yet", label: "adv. 尚未" },
  { word: "yet", label: "adv. 還" },
  { word: "yet", label: "conj. 但是" },
  { word: "even", label: "adj. 平坦的" },
  { word: "even", label: "adj. 平均的" },
  { word: "if", label: "conj. 如果" },
  { word: "if", label: "conj. 是否" },
  { word: "or", label: "conj. 或者" },
  { word: "or", label: "conj. 否則" },
  { word: "live", label: "v. 住" },
  { word: "live", label: "v. 生活" },
  { word: "apply", label: "v. 應用" },
  { word: "apply", label: "v. 使用" },
  { word: "count", label: "v. 數" },
  { word: "count", label: "v. 計算" },
  { word: "count", label: "v. 重要" },
  { word: "count", label: "n. 數目" },
  { word: "count", label: "n. 總數" },
  { word: "individual", label: "adj. 個別的" },
  { word: "individual", label: "adj. 個人的" },
  { word: "realise", label: "v. 意識到" },
  { word: "realise", label: "v. 實現" },
  { word: "realize", label: "v. 意識到" },
  { word: "realize", label: "v. 實現" },
  { word: "recognise", label: "v. 認出" },
  { word: "recognise", label: "v. 認可" },
  { word: "recognise", label: "v. 承認" },
  { word: "recognize", label: "v. 認出" },
  { word: "recognize", label: "v. 認可" },
  { word: "recognize", label: "v. 承認" },
  { word: "organise", label: "v. 組織" },
  { word: "organise", label: "v. 安排" },
  { word: "organize", label: "v. 組織" },
  { word: "organize", label: "v. 安排" },
  { word: "analyse", label: "v. 分析" },
  { word: "analyze", label: "v. 分析" },
  { word: "criticise", label: "v. 批評" },
  { word: "criticize", label: "v. 批評" },
  { word: "apologise", label: "v. 道歉" },
  { word: "apologize", label: "v. 道歉" },
  { word: "behaviour", label: "n. 行為" },
  { word: "behavior", label: "n. 行為" },
  { word: "colour", label: "n. 顏色" },
  { word: "color", label: "n. 顏色" },
  { word: "favourite", label: "adj. 最喜歡的 / 最喜歡的人或物" },
  { word: "favorite", label: "adj. 最喜歡的 / 最喜歡的人或物" },
  { word: "centre", label: "n. 中心" },
  { word: "centre", label: "v. 集中於" },
  { word: "centre", label: "v. 以...為中心" },
  { word: "center", label: "n. 中心" },
  { word: "center", label: "v. 集中於" },
  { word: "center", label: "v. 以...為中心" },
  { word: "theatre", label: "n. 劇場" },
  { word: "theatre", label: "n. 戲院" },
  { word: "theater", label: "n. 劇場" },
  { word: "theater", label: "n. 戲院" },
  { word: "travelling", label: "n. 旅行" },
  { word: "traveling", label: "n. 旅行" },
  { word: "neighbour", label: "n. 鄰居" },
  { word: "neighbor", label: "n. 鄰居" },
  { word: "labour", label: "n. 勞動" },
  { word: "labour", label: "n. 勞工" },
  { word: "labor", label: "n. 勞動" },
  { word: "labor", label: "n. 勞工" },
  { word: "honour", label: "n. 榮譽" },
  { word: "honor", label: "n. 榮譽" },
  { word: "programme", label: "n. 節目 / 計劃" },
  { word: "program", label: "n. 節目 / 程式 / 計劃" },
  { word: "practise", label: "v. 練習" },
  { word: "practice", label: "n. 練習" },
  { word: "practice", label: "n. 做法" },
  { word: "practice", label: "n. 慣例" },
  { word: "practice", label: "v. 練習" },
  { word: "defence", label: "n. 防衛" },
  { word: "defence", label: "n. 防守" },
  { word: "defence", label: "n. 辯護" },
  { word: "defense", label: "n. 防衛" },
  { word: "defense", label: "n. 防守" },
  { word: "defense", label: "n. 辯護" },
  { word: "decline", label: "n. 下降" },
  { word: "decline", label: "n. 衰退" },
  { word: "decline", label: "v. 下降" },
  { word: "decline", label: "v. 衰退" },
  { word: "decline", label: "v. 婉拒 / 拒絕" },
  { word: "dependent", label: "adj. 依賴的" },
  { word: "dependent", label: "adj. 取決於...的" },
  { word: "desperate", label: "adj. 絕望的" },
  { word: "desperate", label: "adj. 極需要的" },
  { word: "distinct", label: "adj. 明顯不同的" },
  { word: "distinct", label: "adj. 清楚的" },
  { word: "display", label: "v. 展示" },
  { word: "display", label: "v. 顯示" },
  { word: "distribute", label: "v. 分發" },
  { word: "distribute", label: "v. 分配" },
  { word: "distribution", label: "n. 分發" },
  { word: "distribution", label: "n. 分配" },
  { word: "document", label: "v. 記錄" },
  { word: "document", label: "v. 證明" },
  { word: "donation", label: "n. 捐款" },
  { word: "donation", label: "n. 捐贈" },
  { word: "dramatic", label: "adj. 巨大的 / 突然的" },
  { word: "dramatic", label: "adj. 戲劇的" },
  { word: "edit", label: "v. 編輯" },
  { word: "edit", label: "v. 修改" },
  { word: "eliminate", label: "v. 消除" },
  { word: "eliminate", label: "v. 淘汰" },
  { word: "emphasis", label: "n. 強調" },
  { word: "emphasis", label: "n. 重點" },
  { word: "licence", label: "n. 牌照" },
  { word: "licence", label: "n. 許可證" },
  { word: "license", label: "n. 牌照" },
  { word: "license", label: "n. 許可證" },
  { word: "license", label: "v. 批准" },
  { word: "license", label: "v. 發牌" },
  { word: "agency", label: "n. 機構" },
  { word: "agency", label: "n. 代理公司" },
  { word: "aggressive", label: "adj. 有攻擊性的" },
  { word: "aggressive", label: "adj. 進取的" },
  { word: "aim", label: "n. 目標" },
  { word: "aim", label: "n. 目的" },
  { word: "aim", label: "v. 旨在" },
  { word: "aim", label: "v. 瞄準" },
  { word: "ambition", label: "n. 抱負" },
  { word: "ambition", label: "n. 雄心" },
  { word: "ambitious", label: "adj. 有抱負的" },
  { word: "ambitious", label: "adj. 有雄心的" },
  { word: "arrest", label: "n. 逮捕" },
  { word: "arrest", label: "n. 拘捕" },
  { word: "arrest", label: "v. 逮捕" },
  { word: "arrest", label: "v. 拘捕" },
  { word: "artificial", label: "adj. 人工的" },
  { word: "artificial", label: "adj. 人造的" },
  { word: "associate", label: "v. 聯想" },
  { word: "associate", label: "v. 聯繫" },
  { word: "associate", label: "adj. 副的" },
  { word: "associate", label: "adj. 相關的" },
  { word: "association", label: "n. 協會" },
  { word: "association", label: "n. 關聯" },
  { word: "assure", label: "v. 保證" },
  { word: "assure", label: "v. 使...相信" },
  { word: "authority", label: "n. 權威" },
  { word: "authority", label: "n. 權力" },
  { word: "authority", label: "n. 當局" },
  { word: "authority", label: "n. 官方機構" },
  { word: "barrier", label: "n. 屏障" },
  { word: "barrier", label: "n. 障礙" },
  { word: "blame", label: "n. 責任" },
  { word: "blame", label: "n. 責備" },
  { word: "blame", label: "v. 責怪" },
  { word: "blame", label: "v. 指責" },
  { word: "boost", label: "n. 提升" },
  { word: "boost", label: "n. 幫助" },
  { word: "boost", label: "v. 提升" },
  { word: "boost", label: "v. 促進" },
  { word: "broadcast", label: "v. 廣播" },
  { word: "broadcast", label: "v. 播放" },
  { word: "cabin", label: "n. 機艙" },
  { word: "cabin", label: "n. 船艙" },
  { word: "cabin", label: "n. 小屋" },
  { word: "benefit", label: "v. 有益於" },
  { word: "benefit", label: "v. 受益" },
  { word: "budget", label: "v. 制定預算" },
  { word: "budget", label: "v. 節省開支" },
  { word: "campaign", label: "n. 活動" },
  { word: "campaign", label: "n. 運動" },
  { word: "campaign", label: "v. 發起運動" },
  { word: "campaign", label: "v. 參與運動" },
  { word: "challenge", label: "v. 挑戰" },
  { word: "challenge", label: "v. 質疑" },
  { word: "capture", label: "v. 捕捉" },
  { word: "capture", label: "v. 俘虜" },
  { word: "capture", label: "v. 拍攝" },
  { word: "capture", label: "v. 記錄" },
  { word: "capture", label: "n. 捕獲" },
  { word: "capture", label: "n. 佔領" },
  { word: "casual", label: "adj. 隨便的" },
  { word: "casual", label: "adj. 非正式的" },
  { word: "cause", label: "v. 導致" },
  { word: "cause", label: "v. 引起" },
  { word: "case", label: "n. 盒" },
  { word: "case", label: "n. 箱" },
  { word: "cabinet", label: "n. 櫥櫃" },
  { word: "cabinet", label: "n. 內閣" },
  { word: "canvas", label: "n. 畫布" },
  { word: "canvas", label: "n. 帆布" },
  { word: "capital", label: "n. 資本" },
  { word: "capital", label: "n. 資金" },
  { word: "career", label: "n. 職業" },
  { word: "career", label: "n. 事業" },
  { word: "cease", label: "v. 停止" },
  { word: "cease", label: "v. 終止" },
  { word: "charming", label: "adj. 迷人的" },
  { word: "charming", label: "adj. 有魅力的" },
  { word: "chest", label: "n. 胸部" },
  { word: "chest", label: "n. 胸腔" },
  { word: "border", label: "n. 邊界" },
  { word: "border", label: "n. 國界" },
  { word: "beat", label: "v. 打敗" },
  { word: "beat", label: "v. 打" },
  { word: "beat", label: "n. 節拍" },
  { word: "beat", label: "n. 心跳" },
  { word: "block", label: "n. 大廈" },
  { word: "block", label: "n. 街區" },
  { word: "block", label: "n. 一塊" },
  { word: "block", label: "n. 一段" },
  { word: "block", label: "v. 阻擋" },
  { word: "block", label: "v. 堵塞" },
  { word: "boom", label: "n. 快速增長" },
  { word: "boom", label: "n. 繁榮" },
  { word: "bother", label: "v. 打擾" },
  { word: "bother", label: "v. 煩擾" },
  { word: "boundary", label: "n. 邊界" },
  { word: "boundary", label: "n. 界線" },
  { word: "boutique", label: "n. 時裝店" },
  { word: "boutique", label: "n. 精品店" },
  { word: "bury", label: "v. 埋葬" },
  { word: "bury", label: "v. 埋藏" },
  { word: "breath", label: "n. 呼吸" },
  { word: "breath", label: "n. 氣息" },
  { word: "bubble", label: "n. 氣泡" },
  { word: "bubble", label: "n. 泡泡" },
  { word: "calm", label: "adj. 冷靜的" },
  { word: "calm", label: "adj. 平靜的" },
  { word: "candidate", label: "n. 候選人" },
  { word: "candidate", label: "n. 參加者" },
  { word: "captain", label: "n. 隊長" },
  { word: "captain", label: "n. 船長" },
  { word: "captain", label: "n. 機長" },
  { word: "central", label: "adj. 中央的" },
  { word: "central", label: "adj. 主要的" },
  { word: "channel", label: "n. 渠道" },
  { word: "channel", label: "n. 途徑" },
  { word: "cheat", label: "v. 作弊" },
  { word: "cheat", label: "v. 欺騙" },
  { word: "cheat", label: "n. 騙子" },
  { word: "cheat", label: "n. 作弊者" },
  { word: "clause", label: "n. 子句" },
  { word: "clause", label: "n. 條款" },
  { word: "combination", label: "n. 組合" },
  { word: "combination", label: "n. 結合" },
  { word: "comic", label: "adj. 滑稽的" },
  { word: "comic", label: "adj. 喜劇的" },
  { word: "command", label: "v. 命令" },
  { word: "command", label: "v. 指揮" },
  { word: "command", label: "n. 掌握" },
  { word: "command", label: "n. 控制能力" },
  { word: "comparative", label: "adj. 比較的" },
  { word: "comparative", label: "adj. 相對的" },
  { word: "concerned", label: "adj. 有關的" },
  { word: "concerned", label: "adj. 相關的" },
  { word: "confusion", label: "n. 困惑" },
  { word: "confusion", label: "n. 混亂" },
  { word: "consideration", label: "n. 考慮" },
  { word: "consideration", label: "n. 體諒 / 顧及" },
  { word: "construction", label: "n. 建造 / 施工" },
  { word: "construction", label: "n. 建築物 / 結構" },
  { word: "consumption", label: "n. 消耗" },
  { word: "consumption", label: "n. 消費" },
  { word: "contest", label: "n. 比賽 / 競賽" },
  { word: "contest", label: "v. 爭辯 / 質疑" },
  { word: "contribute", label: "v. 貢獻 / 捐助" },
  { word: "contribute", label: "v. 促成 / 是原因之一" },
  { word: "coverage", label: "n. 新聞報道" },
  { word: "coverage", label: "n. 覆蓋範圍" },
  { word: "crack", label: "n. 裂縫" },
  { word: "crack", label: "v. 破裂 / 裂開" },
  { word: "crack", label: "v. 破解 / 解決" },
  { word: "craft", label: "n. 手藝 / 工藝" },
  { word: "craft", label: "n. 船 / 飛行器" },
  { word: "craft", label: "v. 精心製作" },
  { word: "creation", label: "n. 創造 / 創作" },
  { word: "creation", label: "n. 創作品" },
  { word: "brief", label: "adj. 短暫的" },
  { word: "brief", label: "adj. 簡短的" },
  { word: "brief", label: "n. 摘要" },
  { word: "brief", label: "n. 指示" },
  { word: "broad", label: "adj. 廣泛的" },
  { word: "broad", label: "adj. 概括的" },
  { word: "broadcaster", label: "n. 廣播員" },
  { word: "broadcaster", label: "n. 播音員" },
  { word: "broadly", label: "adv. 大體上" },
  { word: "broadly", label: "adv. 廣泛地" },
  { word: "cable", label: "n. 電纜" },
  { word: "cable", label: "n. 纜線" },
  { word: "calculate", label: "v. 估計" },
  { word: "calculate", label: "v. 推算" },
  { word: "grey", label: "adj. 灰色的" },
  { word: "gray", label: "adj. 灰色的" },
  { word: "jewellery", label: "n. 珠寶" },
  { word: "jewelry", label: "n. 珠寶" },
  { word: "tyre", label: "n. 輪胎" },
  { word: "tire", label: "n. 輪胎" },
  { word: "sit down", label: "v. 坐下" },
  { word: "stand up", label: "v. 站起來" },
  { word: "come in", label: "v. 進來" },
  { word: "go away", label: "v. 走開 / 離開" },
  { word: "put down", label: "v. 放下" },
  { word: "take back", label: "v. 取回 / 收回" },
  { word: "give back", label: "v. 歸還" },
  { word: "hand in", label: "v. 交功課 / 遞交" },
  { word: "hand out", label: "v. 派發" },
  { word: "lie down", label: "v. 躺下" },
  { word: "lie to", label: "v. 向...說謊" },
  { word: "try on", label: "v. 試穿" },
  { word: "try out", label: "v. 試用 / 試做" },
  { word: "work out", label: "v. 計算出 / 想出 / 解決" },
  { word: "work out", label: "v. 做運動 / 健身" },
  { word: "bring up", label: "v. 提出" },
  { word: "bring up", label: "v. 撫養" },
  { word: "break down", label: "v. 壞掉 / 失靈" },
  { word: "break down", label: "v. 分解 / 拆解" },
  { word: "break up", label: "v. 分手 / 分開" },
  { word: "carry on", label: "v. 繼續" },
  { word: "carry out", label: "v. 實施 / 進行 / 執行" },
  { word: "look", label: "n. 眼神 / 樣子" },
  { word: "department", label: "n. 部門" },
  { word: "department", label: "n. 政府部門" },
  { word: "rod", label: "n. 桿 / 棒" },
  { word: "versus", label: "prep. 對 / 對抗" },
  { word: "right", label: "adv. 正確地" },
  { word: "right", label: "adv. 立刻 / 馬上" },
  { word: "left", label: "v. 離開了（leave 的過去式 / PP）" },
  { word: "left", label: "v. 留下了（leave 的過去式 / PP）" },
  { word: "Mainland China", label: "n. 中國內地" },
  { word: "public housing", label: "n. 公共房屋 / 公屋" },
  { word: "housing estate", label: "n. 屋邨 / 屋苑" },
  { word: "public housing estate", label: "n. 公共屋邨 / 公屋" },
  { word: "estate", label: "n. 屋苑" },
  { word: "employer", label: "n. 僱主" },
  { word: "grant", label: "v. 準許 / 授予" },
  { word: "root", label: "v. 紮根" },
  { word: "take hold", label: "v. 紮根 / 站穩陣腳" },
  { word: "express condolence", label: "v. 表達慰問 / 弔唁" },
  { word: "barrel", label: "n. 圓桶" },
  { word: "cupboard", label: "n. 櫥櫃" },
  { word: "district", label: "n. 地區" },
  { word: "ministry", label: "n. 政府部門" },
  { word: "steak", label: "n. 牛扒" },
  { word: "extent", label: "n. 程度" },
  { word: "extent", label: "n. 範圍" },
  { word: "white-collar worker", label: "n. 白領人士" },
  { word: "have no choice but to", label: "v. 別無選擇，只好" }
]);
