(function attachCoreVocabSenseChecklist(root, checklist) {
  if (typeof module !== "undefined" && module.exports) {
    module.exports = checklist;
  }
  root.CORE_VOCAB_SENSE_CHECKLIST = checklist;
})(typeof globalThis !== "undefined" ? globalThis : window, [
  { word: "water", label: "n. 水" },
  { word: "water", label: "v. 澆水" },
  { word: "work", label: "n. 工作" },
  { word: "work", label: "n. 作品" },
  { word: "work", label: "v. 工作 / 做事" },
  { word: "work", label: "v. 運作 / 奏效" },
  { word: "have", label: "v. 有" },
  { word: "have", label: "v. 食 / 飲" },
  { word: "play", label: "v. 玩 / 打（球類）" },
  { word: "play", label: "v. 演奏" },
  { word: "play", label: "n. 戲劇" },
  { word: "paper", label: "n. 紙" },
  { word: "paper", label: "n. 報紙 / 文件 / 試卷" },
  { word: "school", label: "n. 學校" },
  { word: "room", label: "n. 房間" },
  { word: "room", label: "n. 空間" },
  { word: "watch", label: "v. 觀看" },
  { word: "watch", label: "n. 手錶" },
  { word: "book", label: "n. 書" },
  { word: "book", label: "v. 預訂" },
  { word: "right", label: "adj. 正確的" },
  { word: "right", label: "adj. 右邊的" },
  { word: "right", label: "n. 權利" },
  { word: "right", label: "adv. 向右" },
  { word: "left", label: "adj. 左邊的" },
  { word: "left", label: "adv. 向左" },
  { word: "left", label: "adv. 在左邊" },
  { word: "left", label: "v. 離開了（leave 的過去式 / PP）" },
  { word: "left", label: "v. 留下了（leave 的過去式 / PP）" },
  { word: "close", label: "v. 關閉" },
  { word: "close", label: "adj. 接近的" },
  { word: "close", label: "adj. 親密的" },
  { word: "clean", label: "adj. 乾淨的" },
  { word: "clean", label: "v. 清潔" },
  { word: "face", label: "n. 臉" },
  { word: "face", label: "v. 面對" },
  { word: "hand", label: "n. 手" },
  { word: "hand", label: "v. 交給 / 遞給" },
  { word: "head", label: "n. 頭" },
  { word: "head", label: "v. 前往 / 率領" },
  { word: "take", label: "v. 拿 / 帶 / 乘搭" },
  { word: "take", label: "v. 花費（時間）" },
  { word: "get", label: "v. 得到 / 收到" },
  { word: "get", label: "v. 變得 / 到達" },
  { word: "make", label: "v. 製造 / 使 / 做" },
  { word: "stand", label: "v. 站立" },
  { word: "stand", label: "n. 攤位" },
  { word: "train", label: "n. 火車" },
  { word: "train", label: "v. 訓練" },
  { word: "fly", label: "v. 飛" },
  { word: "fly", label: "n. 蒼蠅" },
  { word: "draw", label: "v. 畫畫" },
  { word: "draw", label: "v. 吸引" },
  { word: "give", label: "v. 給 / 交給" },
  { word: "put", label: "v. 放 / 擺" },
  { word: "come", label: "v. 來" },
  { word: "come", label: "v. 到達" },
  { word: "look", label: "v. 看" },
  { word: "look", label: "v. 看起來" },
  { word: "see", label: "v. 看見 / 明白" },
  { word: "say", label: "v. 說" },
  { word: "tell", label: "v. 告訴 / 分辨" },
  { word: "ask", label: "v. 問 / 要求" },
  { word: "call", label: "v. 打電話 / 稱呼" },
  { word: "call", label: "n. 電話" },
  { word: "answer", label: "v. 回答" },
  { word: "answer", label: "n. 答案" },
  { word: "point", label: "n. 分數 / 重點 / 點" },
  { word: "point", label: "v. 指向" },
  { word: "class", label: "n. 班 / 課堂" },
  { word: "class", label: "n. 分類 / 類別" },
  { word: "table", label: "n. 桌子" },
  { word: "table", label: "n. 表格" },
  { word: "date", label: "n. 日期" },
  { word: "date", label: "n. 約會" },
  { word: "story", label: "n. 故事" },
  { word: "story", label: "n. 樓層 / 層" },
  { word: "letter", label: "n. 信" },
  { word: "letter", label: "n. 字母" },
  { word: "minute", label: "n. 分鐘" },
  { word: "minute", label: "adj. 極小的" },
  { word: "past", label: "n. 過去" },
  { word: "past", label: "adj. 過去的" },
  { word: "past", label: "prep. 經過" },
  { word: "well", label: "adv. 好" },
  { word: "well", label: "adj. 健康的" },
  { word: "well", label: "n. 井" },
  { word: "fine", label: "adj. 好的 / 不錯的" },
  { word: "fine", label: "n. 罰款" },
  { word: "free", label: "adj. 免費的 / 自由的" },
  { word: "free", label: "v. 釋放" },
  { word: "poor", label: "adj. 貧窮的 / 差的 / 可憐的" },
  { word: "light", label: "n. 光" },
  { word: "light", label: "n. 燈" },
  { word: "light", label: "adj. 輕的" },
  { word: "light", label: "adj. 淺色的" },
  { word: "kind", label: "n. 種類" },
  { word: "kind", label: "adj. 友善的" },
  { word: "hard", label: "adj. 困難的 / 硬的" },
  { word: "hard", label: "adv. 努力地" },
  { word: "mean", label: "v. 意思是 / 意味著" },
  { word: "mean", label: "adj. 刻薄的" },
  { word: "mean", label: "adj. 吝嗇的" },
  { word: "change", label: "v. 改變" },
  { word: "change", label: "n. 變化" },
  { word: "change", label: "n. 零錢" },
  { word: "turn", label: "v. 轉動" },
  { word: "turn", label: "v. 轉彎" },
  { word: "turn", label: "n. 輪流" },
  { word: "turn", label: "n. 次序" },
  { word: "plant", label: "n. 植物" },
  { word: "plant", label: "n. 工廠" },
  { word: "plant", label: "v. 種植" },
  { word: "fall", label: "v. 跌倒" },
  { word: "fall", label: "v. 下降" },
  { word: "fall", label: "n. 秋天" },
  { word: "sound", label: "n. 聲音" },
  { word: "sound", label: "v. 聽起來" },
  { word: "sound", label: "adj. 合理的" },
  { word: "sound", label: "adj. 可靠的" },
  { word: "match", label: "n. 比賽 / 配對" },
  { word: "match", label: "v. 配對 / 相配" },
  { word: "present", label: "n. 禮物" },
  { word: "present", label: "adj. 在場的" },
  { word: "present", label: "v. 呈現 / 展示" },
  { word: "order", label: "n. 次序 / 命令 / 訂單" },
  { word: "order", label: "v. 訂購 / 命令" },
  { word: "subject", label: "n. 科目" },
  { word: "subject", label: "n. 主題" },
  { word: "break", label: "v. 打破" },
  { word: "break", label: "n. 小休 / 休息" },
  { word: "park", label: "n. 公園" },
  { word: "park", label: "v. 泊車" },
  { word: "orange", label: "n. 橙" },
  { word: "orange", label: "adj. 橙色的" },
  { word: "rule out", label: "v. 排除 / 不考慮" },
  { word: "bacon", label: "n. 煙肉 / 培根" },
  { word: "back", label: "n. 背部" },
  { word: "back", label: "adj. 後面的" },
  { word: "back", label: "adv. 回去 / 向後" },
  { word: "clear", label: "adj. 清楚的 / 明確的" },
  { word: "clear", label: "v. 清除 / 清理" },
  { word: "drop", label: "v. 掉下 / 下降" },
  { word: "drop", label: "n. 一滴" },
  { word: "field", label: "n. 田野 / 運動場" },
  { word: "field", label: "n. 領域 / 範疇" },
  { word: "fit", label: "v. 適合 / 合身" },
  { word: "fit", label: "adj. 健康的" },
  { word: "note", label: "n. 筆記 / 便條" },
  { word: "note", label: "v. 注意 / 留意" },
  { word: "plain", label: "adj. 簡單的 / 樸素的" },
  { word: "plain", label: "n. 平原" },
  { word: "rest", label: "n. 休息" },
  { word: "rest", label: "n. 其餘部分" },
  { word: "rest", label: "v. 休息" },
  { word: "round", label: "adj. 圓的" },
  { word: "round", label: "n. 回合 / 一輪" },
  { word: "sense", label: "n. 感覺 / 意識" },
  { word: "sense", label: "n. 道理 / 意義" },
  { word: "stick", label: "n. 棍 / 枝條" },
  { word: "stick", label: "v. 黏住 / 貼住" },
  { word: "store", label: "n. 商店" },
  { word: "store", label: "v. 儲存" },
  { word: "strike", label: "n. 罷工" },
  { word: "strike", label: "v. 撞擊 / 打" },
  { word: "strong", label: "adj. 強壯的 / 強烈的" },
  { word: "support", label: "v. 支持" },
  { word: "support", label: "n. 支持 / 支援" },
  { word: "tie", label: "n. 領帶" },
  { word: "tie", label: "v. 綁 / 打成平手" },
  { word: "trip", label: "n. 旅行" },
  { word: "trip", label: "v. 絆倒" },
  { word: "wave", label: "n. 波浪 / 揮手" },
  { word: "wave", label: "v. 揮手" },
  { word: "wear", label: "v. 穿 / 戴" },
  { word: "yard", label: "n. 院子" },
  { word: "bear", label: "n. 熊" },
  { word: "bear", label: "v. 忍受" },
  { word: "check", label: "v. 檢查" },
  { word: "check", label: "n. 檢查 / 賬單" },
  { word: "pretty", label: "adj. 漂亮的" },
  { word: "pretty", label: "adv. 頗 / 相當" },
  { word: "beard", label: "n. 鬍鬚" },
  { word: "hammer", label: "n. 錘子" },
  { word: "hammer", label: "v. 用錘敲打" },
  { word: "swift", label: "adj. 迅速的 / 敏捷的" },
  { word: "won't", label: "modal v. 不會 / 將不會" },
  { word: "ought to", label: "modal v. 應該" },
  { word: "delicacy", label: "n. 佳餚" },
  { word: "delicacy", label: "n. 精緻 / 微妙" },
  { word: "cub", label: "n. 幼獸" },
  { word: "validity", label: "n. 有效性 / 合理性" },
  { word: "lift", label: "v. 解除 / 撤銷限制" },
  { word: "egg tart", label: "n. 蛋撻" },
  { word: "lung cancer", label: "n. 肺癌" },
  { word: "realise", label: "v. 意識到 / 實現" },
  { word: "realize", label: "v. 意識到 / 實現" },
  { word: "recognise", label: "v. 認出 / 認可 / 承認" },
  { word: "recognize", label: "v. 認出 / 認可 / 承認" },
  { word: "organise", label: "v. 組織 / 安排" },
  { word: "organize", label: "v. 組織 / 安排" },
  { word: "analyse", label: "v. 分析" },
  { word: "analyze", label: "v. 分析" },
  { word: "criticise", label: "v. 批評" },
  { word: "criticize", label: "v. 批評" },
  { word: "apologise", label: "v. 道歉" },
  { word: "apologize", label: "v. 道歉" },
  { word: "behaviour", label: "n. 行為" },
  { word: "behavior", label: "n. 行為" },
  { word: "colour", label: "n. 顏色" },
  { word: "color", label: "n. 顏色" },
  { word: "favourite", label: "adj. 最喜歡的 / 最喜歡的人或物" },
  { word: "favorite", label: "adj. 最喜歡的 / 最喜歡的人或物" },
  { word: "centre", label: "n. 中心" },
  { word: "center", label: "n. 中心" },
  { word: "theatre", label: "n. 劇場 / 戲院" },
  { word: "theater", label: "n. 劇場 / 戲院" },
  { word: "travelling", label: "n. 旅行" },
  { word: "traveling", label: "n. 旅行" },
  { word: "neighbour", label: "n. 鄰居" },
  { word: "neighbor", label: "n. 鄰居" },
  { word: "labour", label: "n. 勞動 / 勞工" },
  { word: "labor", label: "n. 勞動 / 勞工" },
  { word: "honour", label: "n. 榮譽" },
  { word: "honor", label: "n. 榮譽" },
  { word: "programme", label: "n. 節目 / 計劃" },
  { word: "program", label: "n. 節目 / 程式 / 計劃" },
  { word: "practise", label: "v. 練習" },
  { word: "practice", label: "n. 練習 / 做法 / 方式" },
  { word: "practice", label: "v. 練習" },
  { word: "defence", label: "n. 防衛 / 防守" },
  { word: "defense", label: "n. 防衛 / 防守" },
  { word: "licence", label: "n. 牌照 / 許可證" },
  { word: "license", label: "n. 牌照 / 許可證" },
  { word: "grey", label: "adj. 灰色的" },
  { word: "gray", label: "adj. 灰色的" },
  { word: "jewellery", label: "n. 珠寶" },
  { word: "jewelry", label: "n. 珠寶" },
  { word: "tyre", label: "n. 輪胎" },
  { word: "tire", label: "n. 輪胎" },
  { word: "sit down", label: "v. 坐下" },
  { word: "stand up", label: "v. 站起來" },
  { word: "come in", label: "v. 進來" },
  { word: "go away", label: "v. 走開 / 離開" },
  { word: "put down", label: "v. 放下" },
  { word: "take back", label: "v. 取回 / 收回" },
  { word: "give back", label: "v. 歸還" },
  { word: "hand in", label: "v. 交功課 / 遞交" },
  { word: "hand out", label: "v. 派發" },
  { word: "lie down", label: "v. 躺下" },
  { word: "lie to", label: "v. 向...說謊" },
  { word: "try on", label: "v. 試穿" },
  { word: "try out", label: "v. 試用 / 試做" },
  { word: "work out", label: "v. 計算出 / 想出 / 解決" },
  { word: "work out", label: "v. 做運動 / 健身" },
  { word: "bring up", label: "v. 提出" },
  { word: "bring up", label: "v. 撫養" },
  { word: "break down", label: "v. 壞掉 / 失靈" },
  { word: "break down", label: "v. 分解 / 拆解" },
  { word: "break up", label: "v. 分手 / 分開" },
  { word: "carry on", label: "v. 繼續" },
  { word: "carry out", label: "v. 實施 / 進行 / 執行" },
  { word: "look", label: "n. 眼神 / 樣子" },
  { word: "department", label: "n. 部門" },
  { word: "department", label: "n. 政府部門" },
  { word: "rod", label: "n. 桿 / 棒" },
  { word: "versus", label: "prep. 對 / 對抗" },
  { word: "right", label: "adv. 正確地" },
  { word: "right", label: "adv. 立刻 / 馬上" },
  { word: "left", label: "v. 離開了（leave 的過去式 / PP）" },
  { word: "left", label: "v. 留下了（leave 的過去式 / PP）" },
  { word: "sign", label: "n. 標誌 / 跡象" },
  { word: "Mainland China", label: "n. 中國內地" },
  { word: "public housing", label: "n. 公共房屋 / 公屋" },
  { word: "housing estate", label: "n. 屋邨 / 屋苑" },
  { word: "public housing estate", label: "n. 公共屋邨 / 公屋" },
  { word: "estate", label: "n. 屋苑" },
  { word: "employer", label: "n. 僱主" },
  { word: "grant", label: "v. 準許 / 授予" },
  { word: "root", label: "v. 紮根" },
  { word: "take hold", label: "v. 紮根 / 站穩陣腳" },
  { word: "express condolence", label: "v. 表達慰問 / 弔唁" },
  { word: "barrel", label: "n. 圓桶" },
  { word: "cupboard", label: "n. 櫥櫃" },
  { word: "district", label: "n. 地區" },
  { word: "ministry", label: "n. 政府部門" },
  { word: "steak", label: "n. 牛扒" },
  { word: "white-collar worker", label: "n. 白領人士" },
  { word: "have no choice but to", label: "v. 別無選擇，只好" }
]);
