// Question tag fill-in bank for Battleship grammar mode.
// Fill-in gameplay lives in ui-grammar.js.
(function () {
    const rows = [
        ["這條裙很漂亮。", "It's a beautiful dress, ______?", ["isn't it"], "Positive statement + negative tag."],
        ["今天很冷。", "It's cold today, ______?", ["isn't it"], "Use is in the tag for It is."],
        ["你爸爸是一位老師。", "Your dad is a teacher, ______?", ["isn't he"], "Use he for your dad."],
        ["演唱會很精彩。", "The concert was great, ______?", ["wasn't it"], "Use was for a past be statement."],
        ["孩子們正在開心地玩。", "The kids are playing happily, ______?", ["aren't they"], "Use they for plural people."],
        ["Mary 來自加拿大。", "Mary is from Canada, ______?", ["isn't she"], "Use she for Mary."],
        ["我們遲到了。", "We are late, ______?", ["aren't we"], "Use are with we."],
        ["我遲到了。", "I am late, ______?", ["aren't I"], "The tag for I am is aren't I."],
        ["這是你的頭盔。", "This is your helmet, ______?", ["isn't it"], "Use it after this."],
        ["這些是你的書。", "These are your books, ______?", ["aren't they"], "Use they after these."],
        ["昨天有延誤。", "There was a delay yesterday, ______?", ["wasn't there"], "Use there in the tag after there was."],
        ["Carol 不是認真的。", "Carol isn't serious, ______?", ["is she"], "Negative statement + positive tag."],
        ["那些鞋不是他的。", "Those shoes aren't his, ______?", ["are they"], "Use they after those."],
        ["那件事並不容易。", "It wasn't easy, ______?", ["was it"], "Negative be statement + positive tag."],
        ["你不累。", "You aren't tired, ______?", ["are you"], "Use are with you."],
        ["課室沒有太多噪音。", "There wasn't much noise in the classroom, ______?", ["was there"], "Use there in the tag."],
        ["你會跟我一起來。", "You'll come with me, ______?", ["won't you"], "Use will in the tag."],
        ["Jessica 會彈結他。", "Jessica can play the guitar, ______?", ["can't she"], "Use can in the tag."],
        ["我們現在應該回家。", "We should go home now, ______?", ["shouldn't we"], "Use should in the tag."],
        ["他們聽得到我們。", "They could hear us, ______?", ["couldn't they"], "Use could in the tag."],
        ["她稍後會打電話來。", "She will call later, ______?", ["won't she"], "Use will in the tag."],
        ["你想知道真相。", "You would like to know the truth, ______?", ["wouldn't you"], "Use would in the tag."],
        ["他們去過韓國。", "They have been to Korea, ______?", ["haven't they"], "Use have in perfect tense."],
        ["Alex 看過那套電影。", "Alex has watched the movie, ______?", ["hasn't he"], "Use has in present perfect."],
        ["你在電腦死機前已儲存工作。", "You had saved your work before the computer crashed, ______?", ["hadn't you"], "Use had in past perfect."],
        ["你不會告訴任何人。", "You won't tell anybody, ______?", ["will you"], "Negative modal statement + positive tag."],
        ["Sam 不會游泳。", "Sam can't swim, ______?", ["can he"], "Negative modal statement + positive tag."],
        ["他不應該大叫。", "He shouldn't shout in the library, ______?", ["should he"], "Use should after shouldn't."],
        ["他們不能打開門。", "They couldn't open the door, ______?", ["could they"], "Use could after couldn't."],
        ["她還未完成報告。", "She hasn't finished the report, ______?", ["has she"], "Use has after hasn't."],
        ["你還未聽到消息。", "You haven't heard the news, ______?", ["have you"], "Use have after haven't."],
        ["已經幾個月沒有下雨。", "It hasn't rained for a few months, ______?", ["has it"], "Use has after hasn't."],
        ["Jacky 和 Ethan 不是在爭吵。", "Jacky and Ethan aren't having an argument, ______?", ["are they"], "Use they for two people."],
        ["你吃牛肉。", "You eat beef, ______?", ["don't you"], "Use do when there is no auxiliary verb."],
        ["這聽起來很可怕。", "It sounds terrible, ______?", ["doesn't it"], "Use does for a singular present verb."],
        ["他們贏了比賽。", "They won the match, ______?", ["didn't they"], "Use did for simple past."],
        ["你哥哥喜歡音樂。", "Your brother likes music, ______?", ["doesn't he"], "Use does for a singular present verb."],
        ["他們想來。", "They want to come, ______?", ["don't they"], "Use do for plural present verbs."],
        ["我昨天解釋了你的職責。", "I explained your duties yesterday, ______?", ["didn't I"], "Use did for simple past."],
        ["她很努力溫習。", "She studies hard every day, ______?", ["doesn't she"], "Use does for a singular present verb."],
        ["巴士遲到了。", "The bus arrived late, ______?", ["didn't it"], "Use did for simple past."],
        ["Peter 住在附近。", "Peter lives nearby, ______?", ["doesn't he"], "Use does for a singular present verb."],
        ["我們需要更多椅子。", "We need more chairs, ______?", ["don't we"], "Use do for plural present verbs."],
        ["他很少來這裡。", "He seldom comes here, ______?", ["does he"], "Seldom is negative in meaning, so use a positive tag."],
        ["你幾乎不認識他。", "You hardly know him, ______?", ["do you"], "Hardly is negative in meaning, so use a positive tag."],
        ["他們從未去過加拿大。", "They have never been to Canada, ______?", ["have they"], "Never is negative in meaning, so use a positive tag."],
        ["沒有人打電話找我。", "Nobody phoned for me, ______?", ["did they"], "Use they for nobody."],
        ["沒有事情出錯。", "Nothing went wrong, ______?", ["did it"], "Use it for nothing."],
        ["很少學生明白那條問題。", "Few students understood the question, ______?", ["did they"], "Few is negative in meaning."],
        ["關於這個題目資料很少。", "There was little information on the subject, ______?", ["was there"], "Little is negative in meaning."],
        ["沒有人知道發生甚麼事。", "No one knew what was going on, ______?", ["did they"], "Use they for no one."],
        ["你對我們的新計劃一無所知。", "You know nothing about our latest plan, ______?", ["do you"], "Nothing is negative in meaning."],
        ["她很少投訴。", "She rarely complains, ______?", ["does she"], "Rarely is negative in meaning."],
        ["我們從不浪費食物。", "We never waste food, ______?", ["do we"], "Never is negative in meaning."],
        ["有人留下了書包。", "Someone left their schoolbag behind, ______?", ["didn't they"], "Use they for someone."],
        ["每個人都已經到達。", "Everyone has arrived, ______?", ["haven't they"], "Use they for everyone."],
        ["大家昨晚都玩得開心。", "Everybody had fun at last night's party, ______?", ["didn't they"], "Had fun is an action, so use did."],
        ["所有事情都改變了。", "Everything has changed, ______?", ["hasn't it"], "Use it for everything."],
        ["有東西從架上掉下來。", "Something fell off the shelf, ______?", ["didn't it"], "Use it for something."],
        ["這藥會治好我的喉嚨痛。", "This medicine will cure my sore throat, ______?", ["won't it"], "Use it after this."],
        ["那些鞋屬於 Valerie。", "Those shoes belong to Valerie, ______?", ["don't they"], "Use they after those."],
        ["他的所有答案都是正確的。", "All his answers were correct, ______?", ["weren't they"], "Use they for plural answers."],
        ["有些肉沒有完全煮熟。", "Some of the meat wasn't fully cooked, ______?", ["was it"], "Meat is uncountable, so use it."],
        ["其中一部影印機昨天壞了。", "One of the photocopiers stopped working yesterday, ______?", ["didn't it"], "The subject is one, so use it."],
        ["我們為媽媽做朱古力蛋糕吧。", "Let's make a chocolate cake for Mum, ______?", ["shall we"], "Use shall we after Let's."],
        ["我們這個星期六看電影吧。", "Let's see a film this Saturday, ______?", ["shall we"], "Use shall we after Let's."],
        ["我們不要再爭吵吧。", "Let's not argue anymore, ______?", ["shall we"], "Use shall we after Let's not."],
        ["我們現在開始吧。", "Let's start now, ______?", ["shall we"], "Use shall we after Let's."],
        ["你已經準備好義賣物品清單。", "You have prepared a list for the charity sale, ______?", ["haven't you"], "Use have in present perfect."],
        ["你會看一看。", "You'll take a look, ______?", ["won't you"], "Use will in the tag."],
        ["曲奇是必備物品。", "Cookies are must-haves, ______?", ["aren't they"], "Use they for plural cookies."],
        ["這是一個好主意。", "It's a great idea, ______?", ["isn't it"], "Use is in the tag."],
        ["那些相中的公仔很可愛。", "They are cute, ______?", ["aren't they"], "Use are in the tag."],
        ["那些手工筆記簿應該很有用。", "The handmade notebooks should be useful, ______?", ["shouldn't they"], "Use they for notebooks."],
        ["我們都喜歡他的水彩畫。", "We all love his watercolour paintings, ______?", ["don't we"], "Use do when there is no auxiliary verb."],
        ["這不是一個壞主意。", "It isn't a bad idea, ______?", ["is it"], "Negative statement + positive tag."],
        ["最近天氣越來越暖。", "It's getting warmer these days, ______?", ["isn't it"], "Use is in the tag."],
        ["去年發生過類似事情。", "Something like that happened last year, ______?", ["didn't it"], "Use it for something."],
        ["那聽起來很酷。", "That sounds cool, ______?", ["doesn't it"], "Use it after that."],
        ["我們的攤位會很受歡迎。", "Our booth will be popular, ______?", ["won't it"], "Use will in the tag."],
        ["你們兩個都喜歡藝術。", "You both love art, ______?", ["don't you"], "Use do because love has no auxiliary verb."],
        ["我們根本不能錯過它。", "We couldn't miss it, ______?", ["could we"], "Use could after couldn't."],
        ["這是一個很大的享受。", "It's a big treat, ______?", ["isn't it"], "Positive statement + negative tag."],
        ["有很多不同畫家的插畫。", "There are many illustrations by different artists, ______?", ["aren't there"], "Use there in the tag."],
        ["那很有趣。", "That's interesting, ______?", ["isn't it"], "Use it after that."],
        ["Nara 是不同的。", "Nara is different, ______?", ["isn't he"], "Use he for a male person."],
        ["我們去看看吧。", "Let's go and have a look, ______?", ["shall we"], "Use shall we after Let's."],
        ["這是一個很有創意的想法。", "It's a pretty creative idea, ______?", ["isn't it"], "Positive statement + negative tag."],
        ["那些動物畫又明亮又開朗。", "Those paintings of animals are bright and cheery, ______?", ["aren't they"], "Use they after those."],
        ["我們不應該錯過那些明信片。", "We shouldn't miss those postcards, ______?", ["should we"], "Use should after shouldn't."],
        ["學生們已經準備好了。", "The students are ready, ______?", ["aren't they"], "Use they for students."],
        ["功課很容易。", "The homework is easy, ______?", ["isn't it"], "Homework is uncountable, so use it."],
        ["你的父母昨晚在家。", "Your parents were at home last night, ______?", ["weren't they"], "Use they for parents."],
        ["考試並不困難。", "The exam wasn't difficult, ______?", ["was it"], "Negative statement + positive tag."],
        ["Henry 遺失了鎖匙。", "Henry has lost his keys, ______?", ["hasn't he"], "Use has in present perfect."],
        ["你已經吃了午飯。", "You have eaten lunch, ______?", ["haven't you"], "Use have in present perfect."],
        ["她中午前已經離開。", "She had left before noon, ______?", ["hadn't she"], "Use had in past perfect."],
        ["他們之前沒有見過那位老師。", "They had not seen the teacher before, ______?", ["had they"], "Negative past perfect + positive tag."],
        ["男嬰正在睡覺。", "The baby boy is sleeping, ______?", ["isn't he"], "Use he for the baby boy."],
        ["那些女孩正在唱歌。", "The girls are singing, ______?", ["aren't they"], "Use they for the girls."],
        ["Tom 不喜歡茶。", "Tom doesn't like tea, ______?", ["does he"], "Use does after doesn't."],
        ["你姐姐沒有打電話。", "Your sister didn't call, ______?", ["did she"], "Use did after didn't."],
        ["他們不需要門票。", "They don't need tickets, ______?", ["do they"], "Use do after don't."],
        ["我們沒有完成專題。", "We didn't finish the project, ______?", ["did we"], "Use did after didn't."],
        ["這沒有關係。", "It doesn't matter, ______?", ["does it"], "Use does after doesn't."],
        ["Peter 可以幫忙。", "Peter can help us, ______?", ["can't he"], "Use can in the tag."],
        ["Mary 不能參加。", "Mary can't join the meeting, ______?", ["can she"], "Use can after can't."],
        ["我們明天會見面。", "We will meet tomorrow, ______?", ["won't we"], "Use will in the tag."],
        ["他絕不會說謊。", "He would never lie to us, ______?", ["would he"], "Never is negative in meaning."],
        ["她從未吃過壽司。", "She has never eaten sushi, ______?", ["has she"], "Never is negative in meaning."],
        ["男孩子們很少練習。", "The boys seldom practise after school, ______?", ["do they"], "Seldom is negative in meaning."],
        ["桌上沒有東西。", "There is nothing on the table, ______?", ["is there"], "Nothing is negative in meaning."],
        ["禮堂裏人很少。", "There were few people in the hall, ______?", ["were there"], "Few is negative in meaning."],
        ["沒有人受傷。", "Nobody was injured in the accident, ______?", ["were they"], "Use they for nobody."],
        ["門被鎖上了。", "The door was locked, ______?", ["wasn't it"], "Use it for the door."],
        ["那些門被鎖上了。", "The doors were locked, ______?", ["weren't they"], "Use they for doors."],
        ["Lee 老師派了功課。", "Ms Lee gave us homework, ______?", ["didn't she"], "Use did for simple past."],
        ["這架巴士去中環。", "This bus goes to Central, ______?", ["doesn't it"], "Use does for a singular present verb."],
        ["這些蘋果看起來很新鮮。", "These apples look fresh, ______?", ["don't they"], "Use they after these."],
        ["牛奶聞起來很奇怪。", "The milk smells strange, ______?", ["doesn't it"], "Milk is uncountable, so use it."],
        ["你的電話不是防水的。", "Your phone isn't waterproof, ______?", ["is it"], "Negative statement + positive tag."],
        ["會議九點開始。", "The meeting starts at nine, ______?", ["doesn't it"], "Use does for a singular present verb."],
        ["孩子們很享受旅行。", "The children enjoyed the trip, ______?", ["didn't they"], "Use did for simple past."],
        ["我們可以解決這個問題。", "We can solve this problem, ______?", ["can't we"], "Use can in the tag."],
        ["你應該檢查答案。", "You should check the answer, ______?", ["shouldn't you"], "Use should in the tag."],
        ["檔案已經被刪除。", "The file has been deleted, ______?", ["hasn't it"], "Use has in present perfect passive."],
        ["窗戶已經被清潔。", "The windows have been cleaned, ______?", ["haven't they"], "Use have for plural windows."],
        ["花了很多錢。", "A lot of money was spent on the project, ______?", ["wasn't it"], "Money is uncountable, so use it."],
        ["所有椅子都被移走了。", "All of the chairs were moved, ______?", ["weren't they"], "Use they for chairs."],
        ["每一個箱子都很重。", "Each box is heavy, ______?", ["isn't it"], "Each is singular."],
        ["消息令人驚訝。", "The news was surprising, ______?", ["wasn't it"], "News is uncountable, so use it."],
        ["物理很有趣。", "Physics is interesting, ______?", ["isn't it"], "School subjects are usually singular."],
        ["剪刀很鋒利。", "The scissors are sharp, ______?", ["aren't they"], "Scissors is plural in form."],
        ["警方很有幫助。", "The police were helpful, ______?", ["weren't they"], "Police is normally plural."],
        ["這些資料很有用。", "The information is useful, ______?", ["isn't it"], "Information is uncountable, so use it."],
        ["出現了一個錯誤。", "There has been a mistake, ______?", ["hasn't there"], "Use there in the tag."],
        ["已經有一些投訴。", "There have been some complaints, ______?", ["haven't there"], "Use there in the tag."],
        ["等一等會比較安全。", "It would be safer to wait, ______?", ["wouldn't it"], "Use would in the tag."],
        ["你寧願留在家。", "You would rather stay at home, ______?", ["wouldn't you"], "Use would with would rather."],
        ["我不應該在這裡。", "I shouldn't be here, ______?", ["should I"], "Use should after shouldn't."],
        ["我沒有打擾你。", "I am not disturbing you, ______?", ["am I"], "Use am I after I am not."],
        ["我是對的。", "I am right, ______?", ["aren't I"], "The tag for I am is aren't I."],
        ["你每天早上都喝咖啡。", "You always have coffee in the morning, ______?", ["don't you"], "Have is an action here, so use do."],
        ["她昨晚發高燒。", "She had a high fever last night, ______?", ["didn't she"], "Had is an action/state in simple past, so use did."],
        ["他們晚飯後經常散步。", "They always have a walk after dinner, ______?", ["don't they"], "Have a walk uses do in the tag."],
        ["你哥哥有長頭髮。", "Your brother has long hair, ______?", ["hasn't he", "doesn't he"], "Possession with has can use hasn't he or doesn't he."],
        ["她有一個漂亮的花園。", "She has a beautiful garden, ______?", ["hasn't she", "doesn't she"], "Possession with has can use hasn't she or doesn't she."],
        ["他們有一間鄉郊大屋。", "They have a beautiful house in the country, ______?", ["haven't they", "don't they"], "Possession with have can use haven't they or don't they."],
        ["我們已經見過面。", "We've met before, ______?", ["haven't we"], "We've means we have in present perfect."],
        ["她今天早上一直在溫習。", "She has been revising all morning, ______?", ["hasn't she"], "Use has in present perfect continuous."],
        ["他們昨晚一直在等你。", "They had been waiting for you, ______?", ["hadn't they"], "Use had in past perfect continuous."],
        ["這部電腦需要維修。", "This computer needs repairing, ______?", ["doesn't it"], "Use does for a singular present verb."],
        ["很多學生想加入這個活動。", "Many students want to join the activity, ______?", ["don't they"], "Use they for many students."],
        ["你們不是來自同一間學校。", "You aren't from the same school, ______?", ["are you"], "Negative be statement + positive tag."],
        ["我們不是在浪費時間。", "We aren't wasting time, ______?", ["are we"], "Negative be statement + positive tag."],
        ["他昨晚沒有睡好。", "He didn't sleep well last night, ______?", ["did he"], "Use did after didn't."],
        ["她通常乘地鐵上學。", "She usually takes the MTR to school, ______?", ["doesn't she"], "Use does for a singular present verb."],
        ["他們通常星期五交功課。", "They usually hand in homework on Friday, ______?", ["don't they"], "Use do for plural present verbs."],
        ["我們可以晚一點討論。", "We can discuss it later, ______?", ["can't we"], "Use can in the tag."],
        ["你不介意等一會。", "You don't mind waiting for a while, ______?", ["do you"], "Use do after don't."],
        ["這本書不屬於你。", "This book doesn't belong to you, ______?", ["does it"], "Use does after doesn't."],
        ["他已經交了表格。", "He has submitted the form, ______?", ["hasn't he"], "Use has in present perfect."],
        ["她還沒有回覆電郵。", "She hasn't replied to the email, ______?", ["has she"], "Use has after hasn't."],
        ["你昨天買了票。", "You bought the tickets yesterday, ______?", ["didn't you"], "Use did for simple past."],
        ["我們明天不會遲到。", "We won't be late tomorrow, ______?", ["will we"], "Use will after won't."],
        ["班房裏有足夠椅子。", "There are enough chairs in the classroom, ______?", ["aren't there"], "Use there in the tag."],
        ["班房裏沒有足夠椅子。", "There aren't enough chairs in the classroom, ______?", ["are there"], "Use there in the tag."]
    ];

    function normalizeCategory(hint) {
        if (/let/i.test(hint)) return 'lets';
        if (/negative in meaning|nobody|nothing|no one|few|little|seldom|rarely|never/i.test(hint)) return 'negative_words';
        if (/perfect/i.test(hint)) return 'perfect';
        if (/modal|will|can|should|would|could/i.test(hint)) return 'modal_auxiliary';
        if (/there/i.test(hint)) return 'there';
        if (/do|does|did/i.test(hint)) return 'do_support';
        return 'be_tags';
    }

    window.GRAMMAR_QUESTION_TAG_BANK = rows.map((row, index) => {
        const [chinese, question, answers, hint] = row;
        const acceptedAnswers = Array.isArray(answers) ? answers : [answers];
        const category = normalizeCategory(hint);
        return {
            id: `question_tag_${String(index + 1).padStart(3, '0')}`,
            chinese,
            tense: 'question_tag',
            voice: category,
            tenses: ['question_tag'],
            voices: [category],
            category: 'Question Tag',
            question,
            answers: acceptedAnswers,
            answerSlots: [acceptedAnswers[0]],
            exp: hint
        };
    });
})();
