// Additional IT IS / adjective-pattern rearrange questions.
// Base questions are loaded from grammar_it_is_data.js.
(function () {
    const extraQuestions = [
        { id: "it_is_069", rule: 1, chinese: "對學生來說，準時交功課是重要的。", correct_tokens: [["It", "is", "important", "for", "students", "to", "hand", "in", "homework", "on", "time", "."]], distractors: ["of", "that"] },
        { id: "it_is_070", rule: 1, chinese: "對小朋友來說，每天閱讀是有用的。", correct_tokens: [["It", "is", "useful", "for", "children", "to", "read", "every", "day", "."]], distractors: ["of", "that"] },
        { id: "it_is_071", rule: 1, chinese: "對我們來說，在考試前溫習是必要的。", correct_tokens: [["It", "is", "necessary", "for", "us", "to", "revise", "before", "exams", "."]], distractors: ["of", "that"] },
        { id: "it_is_072", rule: 1, chinese: "對他來說，獨自解決這個問題是困難的。", correct_tokens: [["It", "is", "difficult", "for", "him", "to", "solve", "this", "problem", "alone", "."]], distractors: ["of", "that"] },
        { id: "it_is_073", rule: 1, chinese: "對她來說，記住所有生字是容易的。", correct_tokens: [["It", "is", "easy", "for", "her", "to", "remember", "all", "the", "vocabulary", "."]], distractors: ["of", "that"] },
        { id: "it_is_074", rule: 1, chinese: "對長者來說，使用新科技是具挑戰性的 (challenging)。", correct_tokens: [["It", "is", "challenging", "for", "elderly", "people", "to", "use", "new", "technology", "."]], distractors: ["of", "that"] },
        { id: "it_is_075", rule: 1, chinese: "對青少年來說，控制情緒是困難的。", correct_tokens: [["It", "is", "hard", "for", "teenagers", "to", "control", "their", "emotions", "."]], distractors: ["of", "that"] },
        { id: "it_is_076", rule: 1, chinese: "對我們來說，乘搭地鐵上學是方便的。", correct_tokens: [["It", "is", "convenient", "for", "us", "to", "go", "to", "school", "by", "MTR", "."]], distractors: ["of", "that"] },
        { id: "it_is_077", rule: 1, chinese: "對旅客來說，在香港找到方向是容易的。", correct_tokens: [["It", "is", "easy", "for", "tourists", "to", "find", "their", "way", "in", "Hong", "Kong", "."]], distractors: ["of", "that"] },
        { id: "it_is_078", rule: 1, chinese: "對家長來說，了解孩子的壓力是重要的。", correct_tokens: [["It", "is", "important", "for", "parents", "to", "understand", "their", "children's", "pressure", "."]], distractors: ["of", "that"] },
        { id: "it_is_079", rule: 1, chinese: "對學生來說，在課堂上保持安靜是必須的。", correct_tokens: [["It", "is", "necessary", "for", "students", "to", "keep", "quiet", "in", "class", "."]], distractors: ["of", "that"] },
        { id: "it_is_080", rule: 1, chinese: "對我來說，沒有字典閱讀這篇文章是不可能的。", correct_tokens: [["It", "is", "impossible", "for", "me", "to", "read", "this", "article", "without", "a", "dictionary", "."]], distractors: ["of", "that"] },
        { id: "it_is_081", rule: 1, chinese: "對他們來說，在雨中完成比賽是可能的。", correct_tokens: [["It", "is", "possible", "for", "them", "to", "finish", "the", "race", "in", "the", "rain", "."]], distractors: ["of", "that"] },
        { id: "it_is_082", rule: 1, chinese: "對我們來說，早點離開是較好的。", correct_tokens: [["It", "is", "better", "for", "us", "to", "leave", "earlier", "."]], distractors: ["of", "that"] },
        { id: "it_is_083", rule: 1, chinese: "對你來說，向老師求助是安全的。", correct_tokens: [["It", "is", "safe", "for", "you", "to", "ask", "the", "teacher", "for", "help", "."]], distractors: ["of", "that"] },
        { id: "it_is_084", rule: 1, chinese: "對小朋友來說，獨自在街上玩是危險的。", correct_tokens: [["It", "is", "dangerous", "for", "children", "to", "play", "in", "the", "street", "alone", "."]], distractors: ["of", "that"] },
        { id: "it_is_085", rule: 1, chinese: "對我們來說，保持課室清潔是合理的。", correct_tokens: [["It", "is", "reasonable", "for", "us", "to", "keep", "the", "classroom", "clean", "."]], distractors: ["of", "that"] },
        { id: "it_is_086", rule: 1, chinese: "對新生來說，認識新朋友是正常的。", correct_tokens: [["It", "is", "normal", "for", "new", "students", "to", "make", "new", "friends", "."]], distractors: ["of", "that"] },
        { id: "it_is_087", rule: 1, chinese: "對我來說，明天之前完成報告是不可能的。", correct_tokens: [["It", "is", "impossible", "for", "me", "to", "finish", "the", "report", "by", "tomorrow", "."]], distractors: ["of", "that"] },
        { id: "it_is_088", rule: 1, chinese: "對學生來說，均衡飲食是有益的。", correct_tokens: [["It", "is", "beneficial", "for", "students", "to", "have", "a", "balanced", "diet", "."]], distractors: ["of", "that"] },
        { id: "it_is_089", rule: 1, chinese: "對老師來說，照顧每個學生並不容易。", correct_tokens: [["It", "is", "not", "easy", "for", "teachers", "to", "take", "care", "of", "every", "student", "."]], distractors: ["of", "that"] },
        { id: "it_is_090", rule: 1, chinese: "對我們來說，浪費食物是不對的。", correct_tokens: [["It", "is", "wrong", "for", "us", "to", "waste", "food", "."]], distractors: ["of", "that"] },
        { id: "it_is_091", rule: 1, chinese: "對初學者來說，清楚地寫英文句子是有幫助的。", correct_tokens: [["It", "is", "helpful", "for", "beginners", "to", "write", "English", "sentences", "clearly", "."]], distractors: ["of", "that"] },
        { id: "it_is_092", rule: 1, chinese: "對他來說，在陌生人面前說話是尷尬的。", correct_tokens: [["It", "is", "awkward", "for", "him", "to", "speak", "in", "front", "of", "strangers", "."]], distractors: ["of", "that"] },
        { id: "it_is_093", rule: 1, chinese: "對學生來說，每晚睡八小時是健康的。", correct_tokens: [["It", "is", "healthy", "for", "students", "to", "sleep", "eight", "hours", "every", "night", "."]], distractors: ["of", "that"] },

        { id: "it_is_094", rule: 2, chinese: "你幫那位老人過馬路真好心。", correct_tokens: [["It", "is", "kind", "of", "you", "to", "help", "the", "old", "man", "cross", "the", "road", "."]], distractors: ["for", "that"] },
        { id: "it_is_095", rule: 2, chinese: "他抄功課真不誠實。", correct_tokens: [["It", "is", "dishonest", "of", "him", "to", "copy", "homework", "."]], distractors: ["for", "that"] },
        { id: "it_is_096", rule: 2, chinese: "Mary 不鎖門就離開真粗心。", correct_tokens: [["It", "is", "careless", "of", "Mary", "to", "leave", "the", "door", "unlocked", "."]], distractors: ["for", "that"] },
        { id: "it_is_097", rule: 2, chinese: "他們向新同學打招呼真有禮貌。", correct_tokens: [["It", "is", "polite", "of", "them", "to", "greet", "the", "new", "student", "."]], distractors: ["for", "that"] },
        { id: "it_is_098", rule: 2, chinese: "你為朋友保守秘密真忠誠。", correct_tokens: [["It", "is", "loyal", "of", "you", "to", "keep", "your", "friend's", "secret", "."]], distractors: ["for", "that"] },
        { id: "it_is_099", rule: 2, chinese: "她承認錯誤真勇敢。", correct_tokens: [["It", "is", "brave", "of", "her", "to", "admit", "her", "mistake", "."]], distractors: ["for", "that"] },
        { id: "it_is_100", rule: 2, chinese: "他在圖書館大聲說話真無禮。", correct_tokens: [["It", "is", "rude", "of", "him", "to", "talk", "loudly", "in", "the", "library", "."]], distractors: ["for", "that"] },
        { id: "it_is_101", rule: 2, chinese: "你檢查答案真明智。", correct_tokens: [["It", "is", "wise", "of", "you", "to", "check", "your", "answers", "."]], distractors: ["for", "that"] },
        { id: "it_is_102", rule: 2, chinese: "他忘記媽媽的生日真大意。", correct_tokens: [["It", "is", "careless", "of", "him", "to", "forget", "his", "mother's", "birthday", "."]], distractors: ["for", "that"] },
        { id: "it_is_103", rule: 2, chinese: "他們分享食物真慷慨。", correct_tokens: [["It", "is", "generous", "of", "them", "to", "share", "their", "food", "."]], distractors: ["for", "that"] },
        { id: "it_is_104", rule: 2, chinese: "你嘲笑同學真刻薄。", correct_tokens: [["It", "is", "mean", "of", "you", "to", "laugh", "at", "your", "classmate", "."]], distractors: ["for", "that"] },
        { id: "it_is_105", rule: 2, chinese: "她將座位讓給孕婦真體貼。", correct_tokens: [["It", "is", "thoughtful", "of", "her", "to", "give", "her", "seat", "to", "a", "pregnant", "woman", "."]], distractors: ["for", "that"] },
        { id: "it_is_106", rule: 2, chinese: "Tom 不準備就參加比賽真愚蠢。", correct_tokens: [["It", "is", "foolish", "of", "Tom", "to", "join", "the", "competition", "without", "preparation", "."]], distractors: ["for", "that"] },
        { id: "it_is_107", rule: 2, chinese: "你向老師道歉真成熟。", correct_tokens: [["It", "is", "mature", "of", "you", "to", "apologize", "to", "the", "teacher", "."]], distractors: ["for", "that"] },
        { id: "it_is_108", rule: 2, chinese: "他捐出零用錢真善良。", correct_tokens: [["It", "is", "kind", "of", "him", "to", "donate", "his", "pocket", "money", "."]], distractors: ["for", "that"] },

        { id: "it_is_109", rule: 3, chinese: "很明顯他沒有溫習。", correct_tokens: [["It", "is", "obvious", "that", "he", "has", "not", "revised", "."]], distractors: ["for", "to"] },
        { id: "it_is_110", rule: 3, chinese: "很清楚這個計劃需要更多時間。", correct_tokens: [["It", "is", "clear", "that", "this", "plan", "needs", "more", "time", "."]], distractors: ["for", "to"] },
        { id: "it_is_111", rule: 3, chinese: "很奇怪他今天沒有回覆我們。", correct_tokens: [["It", "is", "strange", "that", "he", "has", "not", "replied", "to", "us", "today", "."]], distractors: ["for", "to"] },
        { id: "it_is_112", rule: 3, chinese: "很可惜你錯過了這次機會。", correct_tokens: [["It", "is", "a", "pity", "that", "you", "missed", "this", "chance", "."]], distractors: ["for", "to"] },
        { id: "it_is_113", rule: 3, chinese: "消息指學校明天會暫停課堂。", correct_tokens: [["It", "is", "reported", "that", "the", "school", "will", "suspend", "classes", "tomorrow", "."]], distractors: ["for", "to"] },
        { id: "it_is_114", rule: 3, chinese: "據說那名學生贏得了比賽。", correct_tokens: [["It", "is", "said", "that", "the", "student", "won", "the", "competition", "."]], distractors: ["for", "to"] },
        { id: "it_is_115", rule: 3, chinese: "大家相信運動能減少壓力。", correct_tokens: [["It", "is", "believed", "that", "exercise", "can", "reduce", "stress", "."]], distractors: ["for", "to"] },
        { id: "it_is_116", rule: 3, chinese: "可以肯定的是他正在說謊。", correct_tokens: [["It", "is", "certain", "that", "he", "is", "lying", "."]], distractors: ["for", "to"] },
        { id: "it_is_117", rule: 3, chinese: "很重要的是每個人都準時到達。", correct_tokens: [["It", "is", "important", "that", "everyone", "arrive", "on", "time", "."]], distractors: ["for", "to"] },
        { id: "it_is_118", rule: 3, chinese: "很令人驚訝的是他沒有通過測驗。", correct_tokens: [["It", "is", "surprising", "that", "he", "did", "not", "pass", "the", "quiz", "."]], distractors: ["for", "to"] },
        { id: "it_is_119", rule: 3, chinese: "很公平的是每隊有相同時間。", correct_tokens: [["It", "is", "fair", "that", "each", "team", "has", "the", "same", "time", "."]], distractors: ["for", "to"] },
        { id: "it_is_120", rule: 3, chinese: "很不幸，巴士已經離開了。", correct_tokens: [["It", "is", "unfortunate", "that", "the", "bus", "has", "already", "left", "."]], distractors: ["for", "to"] },
        { id: "it_is_121", rule: 3, chinese: "很可能我們會遲到。", correct_tokens: [["It", "is", "likely", "that", "we", "will", "be", "late", "."]], distractors: ["for", "to"] },
        { id: "it_is_122", rule: 3, chinese: "不太可能他會改變主意。", correct_tokens: [["It", "is", "unlikely", "that", "he", "will", "change", "his", "mind", "."]], distractors: ["for", "to"] },
        { id: "it_is_123", rule: 3, chinese: "有可能考試會延期。", correct_tokens: [["It", "is", "possible", "that", "the", "exam", "will", "be", "postponed", "."]], distractors: ["for", "to"] },
        { id: "it_is_124", rule: 3, chinese: "很難相信他只用了十分鐘完成。", correct_tokens: [["It", "is", "hard", "to", "believe", "that", "he", "finished", "it", "in", "ten", "minutes", "."]], distractors: ["for", "of"] },
        { id: "it_is_125", rule: 3, chinese: "令人擔心的是很多學生睡眠不足。", correct_tokens: [["It", "is", "worrying", "that", "many", "students", "do", "not", "get", "enough", "sleep", "."]], distractors: ["for", "to"] },
        { id: "it_is_126", rule: 3, chinese: "好消息是我們取得了足夠資金。", correct_tokens: [["It", "is", "good", "news", "that", "we", "have", "raised", "enough", "money", "."]], distractors: ["for", "to"] },
        { id: "it_is_127", rule: 3, chinese: "壞消息是電腦壞了。", correct_tokens: [["It", "is", "bad", "news", "that", "the", "computer", "has", "broken", "down", "."]], distractors: ["for", "to"] },
        { id: "it_is_128", rule: 3, chinese: "令人失望的是隊長忘記了會議。", correct_tokens: [["It", "is", "disappointing", "that", "the", "captain", "forgot", "the", "meeting", "."]], distractors: ["for", "to"] },
        { id: "it_is_129", rule: 3, chinese: "令人鼓舞的是全班都有進步。", correct_tokens: [["It", "is", "encouraging", "that", "the", "whole", "class", "has", "improved", "."]], distractors: ["for", "to"] },
        { id: "it_is_130", rule: 3, chinese: "人們認為充足睡眠能改善記憶力。", correct_tokens: [["It", "is", "thought", "that", "enough", "sleep", "can", "improve", "memory", "."]], distractors: ["for", "to"] },
        { id: "it_is_131", rule: 3, chinese: "據估計這項工程會花三個月。", correct_tokens: [["It", "is", "estimated", "that", "this", "project", "will", "take", "three", "months", "."]], distractors: ["for", "to"] },
        { id: "it_is_132", rule: 3, chinese: "很自然的是他會感到緊張。", correct_tokens: [["It", "is", "natural", "that", "he", "feels", "nervous", "."]], distractors: ["for", "to"] },
        { id: "it_is_133", rule: 3, chinese: "令人遺憾的是他沒有珍惜機會。", correct_tokens: [["It", "is", "regrettable", "that", "he", "did", "not", "treasure", "the", "chance", "."]], distractors: ["for", "to"] },

        { id: "it_is_134", rule: 4, chinese: "是時候我們開始計劃旅行了。", correct_tokens: [["It", "is", "time", "for", "us", "to", "start", "planning", "the", "trip", "."]], distractors: ["that", "of"] },
        { id: "it_is_135", rule: 4, chinese: "是時候你整理你的書桌了。", correct_tokens: [["It", "is", "time", "for", "you", "to", "tidy", "your", "desk", "."]], distractors: ["that", "of"] },
        { id: "it_is_136", rule: 4, chinese: "投訴這個決定是沒有用的。", correct_tokens: [["It", "is", "no", "use", "complaining", "about", "this", "decision", "."]], distractors: ["to", "that"] },
        { id: "it_is_137", rule: 4, chinese: "跟他爭論是沒有好處的。", correct_tokens: [["It", "is", "no", "good", "arguing", "with", "him", "."]], distractors: ["to", "that"] },
        { id: "it_is_138", rule: 4, chinese: "等待遲到的人是浪費時間。", correct_tokens: [["It", "is", "a", "waste", "of", "time", "waiting", "for", "late", "people", "."]], distractors: ["to", "that"] },
        { id: "it_is_139", rule: 4, chinese: "讀這本書是值得的。", correct_tokens: [["It", "is", "worth", "reading", "this", "book", "."]], distractors: ["to", "that"] },
        { id: "it_is_140", rule: 4, chinese: "由你決定是否參加。", correct_tokens: [["It", "is", "up", "to", "you", "to", "decide", "whether", "to", "join", "."]], distractors: ["for", "that"] },
        { id: "it_is_141", rule: 4, chinese: "不用多說，誠實是重要的。", correct_tokens: [["It", "goes", "without", "saying", "that", "honesty", "is", "important", "."]], distractors: ["is", "to"] },
        { id: "it_is_142", rule: 4, chinese: "結果是他沒有收到訊息。", correct_tokens: [["It", "turns", "out", "that", "he", "did", "not", "receive", "the", "message", "."]], distractors: ["is", "for"] },
        { id: "it_is_143", rule: 4, chinese: "看來我們要改變計劃。", correct_tokens: [["It", "seems", "that", "we", "need", "to", "change", "the", "plan", "."]], distractors: ["is", "for"] },
        { id: "it_is_144", rule: 4, chinese: "我突然想到我把功課留在家中。", correct_tokens: [["It", "occurred", "to", "me", "that", "I", "had", "left", "my", "homework", "at", "home", "."]], distractors: ["is", "for"] },
        { id: "it_is_145", rule: 4, chinese: "直到老師解釋後，我才明白。", correct_tokens: [["It", "was", "not", "until", "the", "teacher", "explained", "it", "that", "I", "understood", "."]], distractors: ["is", "for"] },
        { id: "it_is_146", rule: 4, chinese: "毫不意外的是他忘記帶書。", correct_tokens: [["It", "should", "come", "as", "no", "surprise", "that", "he", "forgot", "to", "bring", "his", "book", "."]], distractors: ["is", "for"] },
        { id: "it_is_147", rule: 4, chinese: "無可否認的是手機令生活更方便。", correct_tokens: [["It", "is", "undeniable", "that", "mobile", "phones", "make", "life", "more", "convenient", "."]], distractors: ["to", "for"] },
        { id: "it_is_148", rule: 4, chinese: "大家普遍承認閱讀能擴闊眼界。", correct_tokens: [["It", "is", "widely", "acknowledged", "that", "reading", "can", "broaden", "our", "horizons", "."]], distractors: ["to", "for"] },

        { id: "it_is_149", rule: 5, chinese: "對我們來說，明天帶計數機是必要的嗎?", correct_tokens: [["Is", "it", "necessary", "for", "us", "to", "bring", "a", "calculator", "tomorrow", "?"]], distractors: ["It", "is"] },
        { id: "it_is_150", rule: 5, chinese: "對你來說，每天練習英文重要嗎?", correct_tokens: [["Is", "it", "important", "for", "you", "to", "practise", "English", "every", "day", "?"]], distractors: ["It", "is"] },
        { id: "it_is_151", rule: 5, chinese: "對他們來說，在八點前到達是可能的嗎?", correct_tokens: [["Is", "it", "possible", "for", "them", "to", "arrive", "before", "eight", "?"]], distractors: ["It", "is"] },
        { id: "it_is_152", rule: 5, chinese: "為甚麼對學生來說充足睡眠是重要的?", correct_tokens: [["Why", "is", "it", "important", "for", "students", "to", "get", "enough", "sleep", "?"]], distractors: ["of", "that"] },
        { id: "it_is_153", rule: 5, chinese: "為甚麼他不道歉是無禮的?", correct_tokens: [["Why", "is", "it", "rude", "of", "him", "not", "to", "apologize", "?"]], distractors: ["for", "that"] },
        { id: "it_is_154", rule: 5, chinese: "她幫新同學真好人嗎?", correct_tokens: [["Is", "it", "nice", "of", "her", "to", "help", "the", "new", "student", "?"]], distractors: ["for", "that"] },
        { id: "it_is_155", rule: 5, chinese: "這是否很明顯Tom在說謊?", correct_tokens: [["Is", "it", "obvious", "that", "Tom", "is", "lying", "?"]], distractors: ["for", "to"] },
        { id: "it_is_156", rule: 5, chinese: "為甚麼現在完成計劃是不可能的?", correct_tokens: [["Why", "is", "it", "impossible", "to", "finish", "the", "plan", "now", "?"]], distractors: ["for", "of"] },
        { id: "it_is_157", rule: 5, chinese: "對他來說，戒掉這個壞習慣困難嗎?", correct_tokens: [["Is", "it", "difficult", "for", "him", "to", "give", "up", "this", "bad", "habit", "?"]], distractors: ["of", "that"] },
        { id: "it_is_158", rule: 5, chinese: "對我們來說，準備急救箱是否明智?", correct_tokens: [["Is", "it", "wise", "for", "us", "to", "prepare", "a", "first-aid", "kit", "?"]], distractors: ["of", "that"] },

        { id: "it_is_159", rule: 6, chinese: "對我來說，不笑出來是困難的。", correct_tokens: [["It", "is", "difficult", "for", "me", "not", "to", "laugh", "."]], distractors: ["of", "no"] },
        { id: "it_is_160", rule: 6, chinese: "對學生來說，上課時不看電話是重要的。", correct_tokens: [["It", "is", "important", "for", "students", "not", "to", "look", "at", "their", "phones", "in", "class", "."]], distractors: ["of", "no"] },
        { id: "it_is_161", rule: 6, chinese: "你不告訴別人這個秘密真明智。", correct_tokens: [["It", "is", "wise", "of", "you", "not", "to", "tell", "others", "this", "secret", "."]], distractors: ["for", "no"] },
        { id: "it_is_162", rule: 6, chinese: "他不聽醫生的建議真愚蠢。", correct_tokens: [["It", "is", "foolish", "of", "him", "not", "to", "follow", "the", "doctor's", "advice", "."]], distractors: ["for", "no"] },
        { id: "it_is_163", rule: 6, chinese: "對我們來說，不犯同一個錯誤是必要的。", correct_tokens: [["It", "is", "necessary", "for", "us", "not", "to", "make", "the", "same", "mistake", "."]], distractors: ["of", "no"] },
        { id: "it_is_164", rule: 6, chinese: "對她來說，不擔心考試是不容易的。", correct_tokens: [["It", "is", "not", "easy", "for", "her", "not", "to", "worry", "about", "the", "exam", "."]], distractors: ["of", "no"] },
        { id: "it_is_165", rule: 6, chinese: "對他來說，不相信那個謊言是困難的。", correct_tokens: [["It", "is", "hard", "for", "him", "not", "to", "believe", "that", "lie", "."]], distractors: ["of", "no"] },
        { id: "it_is_166", rule: 6, chinese: "對小朋友來說，不觸摸熱水是重要的。", correct_tokens: [["It", "is", "important", "for", "children", "not", "to", "touch", "hot", "water", "."]], distractors: ["of", "no"] },
        { id: "it_is_167", rule: 6, chinese: "你沒有忘記帶後備筆真細心。", correct_tokens: [["It", "is", "thoughtful", "of", "you", "not", "to", "forget", "to", "bring", "extra", "pens", "."]], distractors: ["for", "no"] },
        { id: "it_is_168", rule: 6, chinese: "對我們來說，不浪費時間是有幫助的。", correct_tokens: [["It", "is", "helpful", "for", "us", "not", "to", "waste", "time", "."]], distractors: ["of", "no"] }
    ];

    window.GRAMMAR_IT_IS_BANK = (Array.isArray(window.GRAMMAR_IT_IS_BANK) ? window.GRAMMAR_IT_IS_BANK : []).concat(extraQuestions);
})();
