// Extra junior-secondary indirect question practice.
// Loaded after grammar_indirect_question_data.js and appended to the main bank.
(function () {
    const extraQuestions = [
        { id: "indirect_question_065", rule: 5, chinese: "學生是否準時完成家課很重要。", correct_tokens: [["Whether", "students", "finish", "their", "homework", "on", "time", "is", "important", "."]], distractors: ["Do", "students", "if", "?"] },
        { id: "indirect_question_066", rule: 5, chinese: "你吃甚麼會影響你的健康。", correct_tokens: [["What", "you", "eat", "affects", "your", "health", "."]], distractors: ["do", "does", "eats", "?"] },
        { id: "indirect_question_067", rule: 5, chinese: "他住在哪裡並不重要。", correct_tokens: [["Where", "he", "lives", "is", "not", "important", "."]], distractors: ["does", "live", "where", "?"] },
        { id: "indirect_question_068", rule: 5, chinese: "她為甚麼哭令她的父母擔心。", correct_tokens: [["Why", "she", "cried", "worried", "her", "parents", "."]], distractors: ["did", "cry", "does", "?"] },
        { id: "indirect_question_069", rule: 5, chinese: "我們如何解決這個問題很重要。", correct_tokens: [["How", "we", "solve", "this", "problem", "is", "important", "."]], distractors: ["do", "can", "solves", "?"] },
        { id: "indirect_question_070", rule: 5, chinese: "哪一隊會贏取決於團隊合作。", correct_tokens: [["Which", "team", "will", "win", "depends", "on", "teamwork", "."]], distractors: ["does", "is", "winning", "?"] },
        { id: "indirect_question_071", rule: 5, chinese: "天氣是否會改變很難預測。", correct_tokens: [["Whether", "the", "weather", "will", "change", "is", "hard", "to", "predict", "."]], distractors: ["If", "does", "will", "?"] },
        { id: "indirect_question_072", rule: 5, chinese: "誰打破了窗仍然未知。", correct_tokens: [["Who", "broke", "the", "window", "is", "still", "unknown", "."]], distractors: ["did", "break", "does", "?"] },
        { id: "indirect_question_073", rule: 5, chinese: "昨天發生了甚麼令我們驚訝。", correct_tokens: [["What", "happened", "yesterday", "surprised", "us", "."]], distractors: ["did", "happen", "does", "?"] },
        { id: "indirect_question_074", rule: 5, chinese: "我們需要多少錢仍不清楚。", correct_tokens: [["How", "much", "money", "we", "need", "is", "unclear", "."]], distractors: ["do", "need", "many", "?"] },
        { id: "indirect_question_075", rule: 5, chinese: "我們是否應該取消旅行取決於雨勢。", correct_tokens: [["Whether", "we", "should", "cancel", "the", "trip", "depends", "on", "the", "rain", "."]], distractors: ["If", "do", "should", "?"] },
        { id: "indirect_question_076", rule: 5, chinese: "考試幾時開始仍未公布。", correct_tokens: [["When", "the", "exam", "will", "start", "has", "not", "been", "announced", "."]], distractors: ["will", "does", "start", "?"] },
        { id: "indirect_question_077", rule: 5, chinese: "甚麼令他生氣是那些噪音。", correct_tokens: [["What", "makes", "him", "angry", "is", "the", "noise", "."]], distractors: ["does", "make", "why", "?"] },
        { id: "indirect_question_078", rule: 5, chinese: "巴士為甚麼遲到仍然是個謎。", correct_tokens: [["Why", "the", "bus", "was", "late", "is", "a", "mystery", "."]], distractors: ["was", "why", "did", "?"] },
        { id: "indirect_question_079", rule: 5, chinese: "她是否在說真話十分重要。", correct_tokens: [["Whether", "she", "is", "telling", "the", "truth", "is", "very", "important", "."]], distractors: ["If", "does", "tell", "?"] },
        { id: "indirect_question_080", rule: 5, chinese: "誰會帶領小組尚未選出。", correct_tokens: [["Who", "will", "lead", "the", "group", "has", "not", "been", "chosen", "."]], distractors: ["will", "does", "leader", "?"] },
        { id: "indirect_question_081", rule: 5, chinese: "你多常練習會影響你的進步。", correct_tokens: [["How", "often", "you", "practise", "affects", "your", "progress", "."]], distractors: ["do", "does", "practises", "?"] },
        { id: "indirect_question_082", rule: 5, chinese: "我們下一步應該做甚麼很清楚。", correct_tokens: [["What", "we", "should", "do", "next", "is", "clear", "."]], distractors: ["should", "do", "what", "?"] },
        { id: "indirect_question_083", rule: 5, chinese: "我們應該讀哪一本書由老師決定。", correct_tokens: [["Which", "book", "we", "should", "read", "is", "up", "to", "the", "teacher", "."]], distractors: ["should", "do", "read", "?"] },
        { id: "indirect_question_084", rule: 5, chinese: "我們明天在哪裡見面取決於學校。", correct_tokens: [["Where", "we", "meet", "tomorrow", "depends", "on", "the", "school", "."]], distractors: ["do", "will", "where", "?"] },
        { id: "indirect_question_085", rule: 7, chinese: "我不知道我的鉛筆在哪裡。", correct_tokens: [["I", "do", "not", "know", "where", "my", "pencil", "is", "."]], distractors: ["is", "my", "pencil", "?"] },
        { id: "indirect_question_086", rule: 7, chinese: "我想知道Tom為甚麼缺席。", correct_tokens: [["I", "wonder", "why", "Tom", "was", "absent", "."]], distractors: ["did", "is", "why", "?"] },
        { id: "indirect_question_087", rule: 7, chinese: "請告訴我會議幾時開始。", correct_tokens: [["Please", "tell", "me", "when", "the", "meeting", "starts", "."]], distractors: ["does", "start", "when", "?"] },
        { id: "indirect_question_088", rule: 7, chinese: "請解釋這個應用程式如何運作。", correct_tokens: [["Please", "explain", "how", "this", "app", "works", "."]], distractors: ["does", "work", "how", "?"] },
        { id: "indirect_question_089", rule: 7, chinese: "她問我是否喜歡那套電影。", correct_tokens: [["She", "asked", "me", "whether", "I", "liked", "the", "film", "."], ["She", "asked", "me", "if", "I", "liked", "the", "film", "."]], distractors: ["if", "did", "like", "?"] },
        { id: "indirect_question_090", rule: 7, chinese: "他告訴我他午餐想吃甚麼。", correct_tokens: [["He", "told", "me", "what", "he", "wanted", "for", "lunch", "."]], distractors: ["did", "want", "what", "?"] },
        { id: "indirect_question_091", rule: 7, chinese: "我們需要決定坐在哪裡。", correct_tokens: [["We", "need", "to", "decide", "where", "to", "sit", "."]], distractors: ["where", "should", "we", "?"] },
        { id: "indirect_question_092", rule: 7, chinese: "我不肯定答案是否正確。", correct_tokens: [["I", "am", "not", "sure", "whether", "the", "answer", "is", "correct", "."], ["I", "am", "not", "sure", "if", "the", "answer", "is", "correct", "."]], distractors: ["if", "is", "answer", "?"] },
        { id: "indirect_question_093", rule: 7, chinese: "Peter想知道誰拿了他的書。", correct_tokens: [["Peter", "wants", "to", "know", "who", "took", "his", "book", "."]], distractors: ["did", "take", "who", "?"] },
        { id: "indirect_question_094", rule: 7, chinese: "我的老師問我為甚麼遲到。", correct_tokens: [["My", "teacher", "asked", "why", "I", "was", "late", "."]], distractors: ["did", "was", "why", "?"] },
        { id: "indirect_question_095", rule: 7, chinese: "我明白你為甚麼疲倦。", correct_tokens: [["I", "understand", "why", "you", "are", "tired", "."]], distractors: ["are", "you", "why", "?"] },
        { id: "indirect_question_096", rule: 7, chinese: "他們討論了他們可以如何幫忙。", correct_tokens: [["They", "discussed", "how", "they", "could", "help", "."]], distractors: ["could", "they", "do", "?"] },
        { id: "indirect_question_097", rule: 7, chinese: "我們找出了Mary住在哪裡。", correct_tokens: [["We", "found", "out", "where", "Mary", "lives", "."]], distractors: ["does", "live", "where", "?"] },
        { id: "indirect_question_098", rule: 7, chinese: "我忘記了圖書館幾時關門。", correct_tokens: [["I", "forgot", "when", "the", "library", "closes", "."]], distractors: ["does", "close", "when", "?"] },
        { id: "indirect_question_099", rule: 7, chinese: "媽媽問我是否洗了碗。", correct_tokens: [["Mum", "asked", "whether", "I", "had", "washed", "the", "dishes", "."], ["Mum", "asked", "if", "I", "had", "washed", "the", "dishes", "."]], distractors: ["if", "did", "wash", "?"] },
        { id: "indirect_question_100", rule: 7, chinese: "請示範如何使用這部機器。", correct_tokens: [["Please", "show", "me", "how", "to", "use", "this", "machine", "."]], distractors: ["how", "can", "I", "?"] },
        { id: "indirect_question_101", rule: 7, chinese: "沒有人知道誰會成為我們的班長。", correct_tokens: [["Nobody", "knows", "who", "will", "be", "our", "class", "monitor", "."]], distractors: ["will", "is", "who", "?"] },
        { id: "indirect_question_102", rule: 7, chinese: "我不記得我把鑰匙放在哪裡。", correct_tokens: [["I", "cannot", "remember", "where", "I", "put", "my", "key", "."]], distractors: ["did", "put", "where", "?"] },
        { id: "indirect_question_103", rule: 7, chinese: "他想知道自己是否應該道歉。", correct_tokens: [["He", "wondered", "whether", "he", "should", "apologize", "."], ["He", "wondered", "if", "he", "should", "apologize", "."]], distractors: ["if", "should", "he", "?"] },
        { id: "indirect_question_104", rule: 7, chinese: "全班討論我們應該帶甚麼。", correct_tokens: [["The", "class", "talked", "about", "what", "we", "should", "bring", "."]], distractors: ["should", "do", "what", "?"] },
        { id: "indirect_question_105", rule: 7, chinese: "我對動物如何溝通感興趣。", correct_tokens: [["I", "am", "interested", "in", "how", "animals", "communicate", "."]], distractors: ["do", "communicate", "how", "?"] },
        { id: "indirect_question_106", rule: 7, chinese: "她問我乘坐哪一輛巴士。", correct_tokens: [["She", "asked", "me", "which", "bus", "I", "took", "."]], distractors: ["did", "take", "which", "?"] },
        { id: "indirect_question_107", rule: 7, chinese: "我們學習了樹木為甚麼重要。", correct_tokens: [["We", "learned", "why", "trees", "are", "important", "."]], distractors: ["are", "why", "do", "?"] },
        { id: "indirect_question_108", rule: 7, chinese: "Tom問我票價是多少。", correct_tokens: [["Tom", "asked", "me", "how", "much", "the", "ticket", "cost", "."]], distractors: ["did", "cost", "many", "?"] },
        { id: "indirect_question_109", rule: 7, chinese: "這份報告解釋了運動為甚麼有用。", correct_tokens: [["The", "report", "explains", "why", "exercise", "is", "useful", "."]], distractors: ["does", "is", "why", "?"] },
        { id: "indirect_question_110", rule: 7, chinese: "我想知道我們是否可以早點離開。", correct_tokens: [["I", "want", "to", "know", "whether", "we", "can", "leave", "early", "."], ["I", "want", "to", "know", "if", "we", "can", "leave", "early", "."]], distractors: ["if", "can", "we", "?"] },
        { id: "indirect_question_111", rule: 7, chinese: "他們正在檢查門是否鎖上了。", correct_tokens: [["They", "are", "checking", "whether", "the", "door", "is", "locked", "."], ["They", "are", "checking", "if", "the", "door", "is", "locked", "."]], distractors: ["if", "is", "door", "?"] },
        { id: "indirect_question_112", rule: 7, chinese: "我忘記了這個字如何串寫。", correct_tokens: [["I", "forgot", "how", "to", "spell", "this", "word", "."]], distractors: ["how", "can", "I", "?"] },
        { id: "indirect_question_113", rule: 7, chinese: "老師解釋了我們必須做甚麼。", correct_tokens: [["The", "teacher", "explained", "what", "we", "had", "to", "do", "."]], distractors: ["did", "must", "what", "?"] },
        { id: "indirect_question_114", rule: 7, chinese: "我們正在考慮放學後去哪裡。", correct_tokens: [["We", "are", "thinking", "about", "where", "to", "go", "after", "school", "."]], distractors: ["where", "we", "should", "?"] },
        { id: "indirect_question_115", rule: 7, chinese: "她知道嬰兒為甚麼在哭。", correct_tokens: [["She", "knows", "why", "the", "baby", "is", "crying", "."]], distractors: ["is", "why", "does", "?"] },
        { id: "indirect_question_116", rule: 7, chinese: "我沒有聽到他說了甚麼。", correct_tokens: [["I", "did", "not", "hear", "what", "he", "said", "."]], distractors: ["did", "say", "what", "?"] },
        { id: "indirect_question_117", rule: 7, chinese: "我們需要查出火車幾時到達。", correct_tokens: [["We", "need", "to", "find", "out", "when", "the", "train", "arrives", "."]], distractors: ["does", "arrive", "when", "?"] },
        { id: "indirect_question_118", rule: 7, chinese: "他問我在哪裡買這雙鞋。", correct_tokens: [["He", "asked", "where", "I", "bought", "these", "shoes", "."]], distractors: ["did", "buy", "where", "?"] },
        { id: "indirect_question_119", rule: 7, chinese: "我想知道這座建築物有多舊。", correct_tokens: [["I", "wonder", "how", "old", "this", "building", "is", "."]], distractors: ["is", "does", "old", "?"] },
        { id: "indirect_question_120", rule: 7, chinese: "Jane不肯定哪一個答案正確。", correct_tokens: [["Jane", "is", "not", "sure", "which", "answer", "is", "correct", "."]], distractors: ["is", "which", "does", "?"] },
        { id: "indirect_question_121", rule: 7, chinese: "那男孩問他可否借一支筆。", correct_tokens: [["The", "boy", "asked", "whether", "he", "could", "borrow", "a", "pen", "."], ["The", "boy", "asked", "if", "he", "could", "borrow", "a", "pen", "."]], distractors: ["if", "could", "he", "?"] },
        { id: "indirect_question_122", rule: 7, chinese: "我知道你的意思。", correct_tokens: [["I", "know", "what", "you", "mean", "."]], distractors: ["do", "mean", "what", "?"] },
        { id: "indirect_question_123", rule: 7, chinese: "告示告訴我們測驗幾時開始。", correct_tokens: [["The", "notice", "tells", "us", "when", "the", "test", "begins", "."]], distractors: ["does", "begin", "when", "?"] },
        { id: "indirect_question_124", rule: 7, chinese: "我們必須選擇誰先匯報。", correct_tokens: [["We", "have", "to", "choose", "who", "will", "present", "first", "."]], distractors: ["will", "who", "does", "?"] },
        { id: "indirect_question_125", rule: 7, chinese: "我不明白電力如何運作。", correct_tokens: [["I", "do", "not", "understand", "how", "electricity", "works", "."]], distractors: ["does", "work", "how", "?"] },
        { id: "indirect_question_126", rule: 7, chinese: "教練解釋了我們為甚麼輸了比賽。", correct_tokens: [["The", "coach", "explained", "why", "we", "lost", "the", "match", "."]], distractors: ["did", "lose", "why", "?"] },
        { id: "indirect_question_127", rule: 7, chinese: "爸爸問我想吃甚麼。", correct_tokens: [["Dad", "asked", "what", "I", "wanted", "to", "eat", "."]], distractors: ["did", "want", "what", "?"] },
        { id: "indirect_question_128", rule: 7, chinese: "她擔心自己是否會通過考試。", correct_tokens: [["She", "is", "worried", "about", "whether", "she", "will", "pass", "the", "exam", "."]], distractors: ["if", "will", "does", "?"] },
        { id: "indirect_question_129", rule: 7, chinese: "我不能決定應該穿哪一件恤衫。", correct_tokens: [["I", "cannot", "decide", "which", "shirt", "I", "should", "wear", "."]], distractors: ["should", "wear", "which", "?"] },
        { id: "indirect_question_130", rule: 7, chinese: "我們討論了學校是否應該容許電話。", correct_tokens: [["We", "discussed", "whether", "phones", "should", "be", "allowed", "at", "school", "."]], distractors: ["if", "do", "allow", "?"] },
        { id: "indirect_question_131", rule: 7, chinese: "這個故事展示了友誼如何改變人。", correct_tokens: [["The", "story", "shows", "how", "friendship", "can", "change", "people", "."]], distractors: ["can", "does", "how", "?"] },
        { id: "indirect_question_132", rule: 7, chinese: "他沒有說他要去哪裡。", correct_tokens: [["He", "did", "not", "say", "where", "he", "was", "going", "."]], distractors: ["did", "go", "where", "?"] },
        { id: "indirect_question_133", rule: 7, chinese: "我不肯定他為甚麼生氣。", correct_tokens: [["I", "am", "not", "sure", "why", "he", "is", "angry", "."]], distractors: ["is", "why", "does", "?"] },
        { id: "indirect_question_134", rule: 7, chinese: "我們需要檢查有多少學生缺席。", correct_tokens: [["We", "need", "to", "check", "how", "many", "students", "are", "absent", "."]], distractors: ["are", "do", "many", "?"] },
        { id: "indirect_question_135", rule: 7, chinese: "我想知道這個遊戲是否太難。", correct_tokens: [["I", "want", "to", "know", "whether", "this", "game", "is", "too", "difficult", "."], ["I", "want", "to", "know", "if", "this", "game", "is", "too", "difficult", "."]], distractors: ["if", "does", "game", "?"] },
        { id: "indirect_question_136", rule: 7, chinese: "老師問我們是否明白規則。", correct_tokens: [["The", "teacher", "asked", "whether", "we", "understood", "the", "rules", "."], ["The", "teacher", "asked", "if", "we", "understood", "the", "rules", "."]], distractors: ["if", "do", "understand", "?"] },
        { id: "indirect_question_137", rule: 7, chinese: "她想知道我最喜歡哪一科。", correct_tokens: [["She", "wanted", "to", "know", "which", "subject", "I", "liked", "most", "."]], distractors: ["did", "like", "which", "?"] },
        { id: "indirect_question_138", rule: 7, chinese: "我們正在學習如何保護環境。", correct_tokens: [["We", "are", "learning", "how", "to", "protect", "the", "environment", "."]], distractors: ["how", "can", "we", "?"] },
        { id: "indirect_question_139", rule: 7, chinese: "我不知道這個字是甚麼意思。", correct_tokens: [["I", "do", "not", "know", "what", "this", "word", "means", "."]], distractors: ["does", "mean", "what", "?"] },
        { id: "indirect_question_140", rule: 7, chinese: "他問我家離學校有多遠。", correct_tokens: [["He", "asked", "how", "far", "my", "home", "was", "from", "school", "."]], distractors: ["is", "does", "far", "?"] },
        { id: "indirect_question_141", rule: 7, chinese: "我們不知道派對是否仍然會舉行。", correct_tokens: [["We", "do", "not", "know", "whether", "the", "party", "will", "still", "take", "place", "."], ["We", "do", "not", "know", "if", "the", "party", "will", "still", "take", "place", "."]], distractors: ["if", "does", "party", "?"] },
        { id: "indirect_question_142", rule: 7, chinese: "請提醒我明天要帶甚麼。", correct_tokens: [["Please", "remind", "me", "what", "to", "bring", "tomorrow", "."]], distractors: ["what", "should", "I", "?"] },
        { id: "indirect_question_143", rule: 7, chinese: "校長宣布了下一個假期幾時開始。", correct_tokens: [["The", "principal", "announced", "when", "the", "next", "holiday", "would", "start", "."]], distractors: ["will", "would", "when", "?"] },
        { id: "indirect_question_144", rule: 8, chinese: "你知道洗手間在哪裡嗎？", correct_tokens: [["Do", "you", "know", "where", "the", "toilet", "is", "?"]], distractors: ["is", "where", "toilet", "."] },
        { id: "indirect_question_145", rule: 8, chinese: "你可以告訴我這堂課幾時完結嗎？", correct_tokens: [["Can", "you", "tell", "me", "when", "the", "lesson", "ends", "?"]], distractors: ["does", "end", "when", "."] },
        { id: "indirect_question_146", rule: 8, chinese: "你記得她為甚麼早走嗎？", correct_tokens: [["Do", "you", "remember", "why", "she", "left", "early", "?"]], distractors: ["did", "leave", "why", "."] },
        { id: "indirect_question_147", rule: 8, chinese: "你可以告訴我怎樣去車站嗎？", correct_tokens: [["Could", "you", "tell", "me", "how", "I", "can", "get", "to", "the", "station", "?"]], distractors: ["can", "I", "how", "."] },
        { id: "indirect_question_148", rule: 8, chinese: "你知道商店是否開門嗎？", correct_tokens: [["Do", "you", "know", "whether", "the", "shop", "is", "open", "?"], ["Do", "you", "know", "if", "the", "shop", "is", "open", "?"]], distractors: ["if", "is", "shop", "."] },
        { id: "indirect_question_149", rule: 8, chinese: "你可以解釋天空為甚麼是藍色嗎？", correct_tokens: [["Can", "you", "explain", "why", "the", "sky", "is", "blue", "?"]], distractors: ["is", "why", "does", "."] },
        { id: "indirect_question_150", rule: 8, chinese: "你知不知道我的電話在哪裡？", correct_tokens: [["Do", "you", "have", "any", "idea", "where", "my", "phone", "is", "?"]], distractors: ["is", "where", "phone", "."] },
        { id: "indirect_question_151", rule: 8, chinese: "你決定了你會買甚麼嗎？", correct_tokens: [["Have", "you", "decided", "what", "you", "will", "buy", "?"]], distractors: ["will", "what", "do", "."] },
        { id: "indirect_question_152", rule: 8, chinese: "你猜到誰贏得獎品嗎？", correct_tokens: [["Can", "you", "guess", "who", "won", "the", "prize", "?"]], distractors: ["did", "win", "who", "."] },
        { id: "indirect_question_153", rule: 8, chinese: "你知道這個袋多少錢嗎？", correct_tokens: [["Do", "you", "know", "how", "much", "this", "bag", "costs", "?"]], distractors: ["does", "cost", "many", "."] },
        { id: "indirect_question_154", rule: 8, chinese: "你可以告訴我哪輛巴士去中環嗎？", correct_tokens: [["Could", "you", "tell", "me", "which", "bus", "goes", "to", "Central", "?"]], distractors: ["does", "go", "which", "."] },
        { id: "indirect_question_155", rule: 8, chinese: "你記得電影幾點開始嗎？", correct_tokens: [["Do", "you", "remember", "what", "time", "the", "film", "starts", "?"]], distractors: ["does", "start", "when", "."] },
        { id: "indirect_question_156", rule: 8, chinese: "你可以告訴我明天是否有測驗嗎？", correct_tokens: [["Can", "you", "tell", "me", "whether", "there", "is", "a", "test", "tomorrow", "?"], ["Can", "you", "tell", "me", "if", "there", "is", "a", "test", "tomorrow", "?"]], distractors: ["if", "is", "there", "."] },
        { id: "indirect_question_157", rule: 8, chinese: "你知道Peter為甚麼不開心嗎？", correct_tokens: [["Do", "you", "know", "why", "Peter", "is", "unhappy", "?"]], distractors: ["is", "why", "does", "."] },
        { id: "indirect_question_158", rule: 8, chinese: "你可以查出圖書館在哪裡嗎？", correct_tokens: [["Can", "you", "find", "out", "where", "the", "library", "is", "?"]], distractors: ["is", "where", "does", "."] },
        { id: "indirect_question_159", rule: 8, chinese: "你知道誰會加入我們嗎？", correct_tokens: [["Do", "you", "know", "who", "will", "join", "us", "?"]], distractors: ["will", "who", "does", "."] },
        { id: "indirect_question_160", rule: 8, chinese: "你可以告訴我旅程需時多久嗎？", correct_tokens: [["Could", "you", "tell", "me", "how", "long", "the", "trip", "takes", "?"]], distractors: ["does", "take", "long", "."] },
        { id: "indirect_question_161", rule: 8, chinese: "你知不知道巴士幾時到達？", correct_tokens: [["Do", "you", "have", "any", "idea", "when", "the", "bus", "will", "arrive", "?"]], distractors: ["will", "when", "does", "."] },
        { id: "indirect_question_162", rule: 8, chinese: "你可以告訴我應該做甚麼嗎？", correct_tokens: [["Can", "you", "tell", "me", "what", "I", "should", "do", "?"]], distractors: ["should", "what", "do", "."] },
        { id: "indirect_question_163", rule: 8, chinese: "你知道我們是否需要帶外套嗎？", correct_tokens: [["Do", "you", "know", "whether", "we", "need", "to", "bring", "a", "jacket", "?"], ["Do", "you", "know", "if", "we", "need", "to", "bring", "a", "jacket", "?"]], distractors: ["if", "do", "need", "."] },
        { id: "indirect_question_164", rule: 8, chinese: "你聽說比賽為甚麼取消了嗎？", correct_tokens: [["Have", "you", "heard", "why", "the", "match", "was", "cancelled", "?"]], distractors: ["was", "why", "did", "."] }
    ];

    window.GRAMMAR_INDIRECT_QUESTION_BANK = [
        ...(Array.isArray(window.GRAMMAR_INDIRECT_QUESTION_BANK) ? window.GRAMMAR_INDIRECT_QUESTION_BANK : []),
        ...extraQuestions
    ];
})();
