// Generated for Battleship grammar mode. Multiple-choice gameplay lives in ui-grammar.js.
(function () {
    const rows = [
        ["我爸爸通常夜晚很晚回家。", "My father usually comes home late ______ night.", "at", "in|at|on|by|during", "night 用 at。"],
        ["火車在早上八點正開出。", "The train leaves ______ 8:00 am sharp.", "at", "at|on|in|by|until", "具體鐘點用 at。"],
        ["商店在午夜關門。", "The shop closes ______ midnight.", "at", "in|on|at|by|during", "midnight 是具體時刻，用 at。"],
        ["我們在正午見面。", "We will meet ______ noon.", "at", "in|on|at|by|during", "noon 是具體時刻，用 at。"],
        ["她在日出時醒來。", "She wakes up ______ sunrise.", "at", "in|on|at|by|during", "sunrise 是具體時刻，用 at。"],
        ["他們在日落時拍照。", "They took photos ______ sunset.", "at", "in|on|at|by|during", "sunset 是具體時刻，用 at。"],
        ["士兵在黎明時離開營地。", "The soldiers left the camp ______ dawn.", "at", "in|on|at|by|during", "dawn 是具體時刻，用 at。"],
        ["他在午飯時間到達。", "He arrived ______ lunchtime.", "at", "in|on|at|by|until", "lunchtime 視為具體時刻，用 at。"],
        ["我現在很忙。", "I am busy ______ the moment.", "at", "in|at|on|by|during", "at the moment 是固定搭配。"],
        ["她目前在加拿大讀書。", "She is studying in Canada ______ present.", "at", "in|on|at|by|during", "at present 是固定搭配。"],
        ["我們同時到達。", "We arrived ______ the same time.", "at", "in|on|at|by|during", "at the same time 是固定搭配。"],
        ["我七歲時開始學英文。", "I started learning English ______ the age of seven.", "at", "in|on|at|by|during", "at the age of 是固定搭配。"],
        ["比賽在半夜開始。", "The match started ______ half past ten.", "at", "in|on|at|by|during", "具體時間點用 at。"],
        ["請在十二點半到達。", "Please arrive ______ half past twelve.", "at", "in|on|at|by|during", "具體鐘點用 at。"],
        ["他通常在清晨跑步。", "He usually jogs ______ dawn.", "at", "in|on|at|by|during", "dawn 是具體時刻，用 at。"],
        ["我們在聖誕節期間探望親戚。", "We visit our relatives ______ Christmas.", "at", "on|in|at|by|from", "指整個節日期間用 at。"],
        ["他們在復活節期間去旅行。", "They often travel ______ Easter.", "at", "on|in|at|by|during", "節日期間通常用 at。"],
        ["我在農曆新年期間見到很多親戚。", "I see many relatives ______ Chinese New Year.", "at", "on|in|at|by|from", "指整個節日期間用 at。"],
        ["老師在課堂開始時收功課。", "The teacher collects homework ______ the beginning of the lesson.", "at", "in|on|at|by|during", "at the beginning of 表示時間點。"],
        ["請在活動結束時交回名牌。", "Please return the name tag ______ the end of the event.", "at", "in|on|at|by|during", "at the end of 表示時間點。"],

        ["我們星期一有英文測驗。", "We have an English quiz ______ Monday.", "on", "in|at|on|by|until", "星期幾用 on。"],
        ["星期二下午有會議。", "There is a meeting ______ Tuesday afternoon.", "on", "in|at|on|by|X (no word)", "有星期幾，即使用 afternoon 也用 on。"],
        ["我們星期日早上去野餐。", "We are going to have a picnic ______ Sunday morning.", "on", "in|at|on|by|X (no word)", "特定日子的早上用 on。"],
        ["音樂會在星期五晚上舉行。", "The concert is ______ Friday night.", "on", "in|at|on|by|during", "特定日子的 night 用 on。"],
        ["我的生日在五月二十二日。", "My birthday is ______ 22nd May.", "on", "in|at|on|by|from", "具體日期用 on。"],
        ["派對在十月三十一日晚上舉行。", "The party is ______ the evening of 31 October.", "on", "in|at|on|by|from", "有具體日期，即使用 evening 也用 on。"],
        ["我們在聖誕節當日吃火雞。", "We eat turkey ______ Christmas Day.", "on", "at|on|in|by|from", "有 Day 字眼用 on。"],
        ["你在平安夜做甚麼？", "What are you doing ______ Christmas Eve?", "on", "in|at|on|by|during", "Eve 是特定日子，用 on。"],
        ["他們在元旦見面。", "They met ______ New Year's Day.", "on", "at|on|in|by|during", "有 Day 字眼用 on。"],
        ["我會在五月第一天探望你。", "I will visit you ______ the first day of May.", "on", "in|at|on|by|during", "指定某一天用 on。"],
        ["學生在開學日穿校服。", "Students wear uniforms ______ the first school day.", "on", "in|at|on|by|during", "指定某一天用 on。"],
        ["我們在星期六晚上看電影。", "We watched a film ______ Saturday evening.", "on", "in|at|on|by|X (no word)", "星期六 evening 是特定日子，用 on。"],
        ["她在寒冷的冬天早上不喜歡早起。", "She hates getting up early ______ cold winter mornings.", "on", "in|at|on|by|during", "特定種類的 mornings 常用 on。"],
        ["我通常在雨天乘巴士。", "I usually take the bus ______ rainy days.", "on", "in|at|on|by|during", "特定日子類型用 on。"],
        ["他們在考試日很緊張。", "They are nervous ______ exam day.", "on", "in|at|on|by|during", "特定日子用 on。"],
        ["校長在畢業禮當天致辭。", "The principal gave a speech ______ graduation day.", "on", "in|at|on|by|during", "特定日子用 on。"],
        ["我在生日那天收到禮物。", "I received a present ______ my birthday.", "on", "in|at|on|by|during", "生日那一天用 on。"],
        ["他們在星期三早上交報告。", "They handed in the report ______ Wednesday morning.", "on", "in|at|on|by|X (no word)", "有星期幾，用 on。"],
        ["我們在母親節吃晚飯。", "We had dinner together ______ Mother's Day.", "on", "at|on|in|by|during", "有 Day 字眼用 on。"],
        ["學生在最後一天清理課室。", "Students cleaned the classroom ______ the last day of term.", "on", "in|at|on|by|during", "指定某一天用 on。"],

        ["我在二零一二年出生。", "I was born ______ 2012.", "in", "in|on|at|by|during", "年份用 in。"],
        ["他們在二零一零年結婚。", "They got married ______ 2010.", "in", "at|on|in|by|during", "年份用 in。"],
        ["我的假期在七月開始。", "My holiday starts ______ July.", "in", "on|in|at|by|until", "月份用 in。"],
        ["這件事發生在四月。", "It happened ______ April.", "in", "in|at|on|by|during", "月份用 in。"],
        ["鳥兒在冬天飛往南方。", "Birds fly south ______ winter.", "in", "at|on|in|by|until", "季節用 in。"],
        ["樹葉在秋天落下。", "Leaves fall ______ autumn.", "in", "at|on|in|by|during", "季節用 in。"],
        ["我們在晚上看電視。", "We watch TV ______ the evening.", "in", "at|on|in|by|until", "morning / afternoon / evening 用 in。"],
        ["他在早上跑步。", "He runs ______ the morning.", "in", "at|on|in|by|until", "morning 用 in。"],
        ["我下午通常做功課。", "I usually do my homework ______ the afternoon.", "in", "at|on|in|by|during", "afternoon 用 in。"],
        ["科技在二十世紀迅速進步。", "Technology advanced quickly ______ the 20th century.", "in", "at|on|in|by|during", "世紀用 in。"],
        ["這張相是在九十年代拍的。", "This photo was taken ______ the 1990s.", "in", "at|on|in|by|during", "年代用 in。"],
        ["這座學校在一九九零年建成。", "The school was built ______ 1990.", "in", "in|at|on|by|during", "年份用 in。"],
        ["我們在未來會用更多科技。", "We will use more technology ______ the future.", "in", "at|on|in|by|during", "in the future 是固定搭配。"],
        ["人們在過去沒有智能電話。", "People did not have smartphones ______ the past.", "in", "at|on|in|by|during", "in the past 是固定搭配。"],
        ["他們在假期中留在香港。", "They stayed in Hong Kong ______ the holidays.", "in", "at|on|in|by|during", "in the holidays 可指假期期間。"],
        ["我在中學時學會打籃球。", "I learned to play basketball ______ secondary school.", "in", "at|on|in|by|during", "in secondary school 指求學階段。"],
        ["很多花在春天盛開。", "Many flowers bloom ______ spring.", "in", "at|on|in|by|during", "季節用 in。"],
        ["我們在十二月考試。", "We have exams ______ December.", "in", "in|on|at|by|during", "月份用 in。"],
        ["她在二十一世紀初出生。", "She was born ______ the early 21st century.", "in", "at|on|in|by|during", "世紀或長時間段用 in。"],
        ["我在暑假期間學游泳。", "I learned to swim ______ the summer holiday.", "in", "at|on|in|by|during", "in the holiday 可指假期之中。"],

        ["別擔心，我五分鐘後會準備好。", "Don't worry! I will be ready ______ five minutes.", "in", "at|on|in|during|until", "未來式 in + 一段時間 = 幾久之後。"],
        ["我可以在兩星期內讀完這本書。", "I can finish reading this book ______ two weeks.", "in", "at|on|in|by|until", "in 可表示需時多久完成。"],
        ["我一小時後回來。", "I'll be back ______ an hour.", "in", "at|on|in|by|until", "in an hour 表示一小時後。"],
        ["她四星期內學會駕駛。", "She learned to drive ______ four weeks.", "in", "at|on|in|by|until", "in 可表示花了多久完成。"],
        ["火車幾分鐘後開出。", "The train leaves ______ a few minutes.", "in", "at|on|in|by|during", "in a few minutes 表示幾分鐘後。"],
        ["我們兩天內完成專題。", "We completed the project ______ two days.", "in", "at|on|in|by|until", "in 可表示需時多久完成。"],
        ["晚餐十分鐘後準備好。", "Dinner will be ready ______ ten minutes.", "in", "at|on|in|by|during", "未來式 in + 時間 = 幾久後。"],
        ["電影十分鐘後開始。", "The film starts ______ ten minutes.", "in", "at|on|in|by|until", "in ten minutes 表示十分鐘後。"],
        ["醫生五分鐘後會見你。", "The doctor will see you ______ five minutes.", "in", "at|on|in|by|until", "in five minutes 表示五分鐘後。"],
        ["我們半小時後離開。", "We are leaving ______ half an hour.", "in", "at|on|in|by|during", "in half an hour 表示半小時後。"],
        ["巴士兩分鐘後到達。", "The bus will arrive ______ two minutes.", "in", "at|on|in|by|until", "未來式 in + 時間。"],
        ["她一個月內完成訓練。", "She finished the training ______ a month.", "in", "at|on|in|by|during", "in 可表示需時多久完成。"],
        ["我會在三日內回覆你。", "I will reply to you ______ three days.", "in", "at|on|in|by|until", "in three days 可表示三日內或三日後。"],
        ["比賽十五分鐘後開始。", "The match begins ______ fifteen minutes.", "in", "at|on|in|by|during", "未來開始時間用 in + 一段時間。"],
        ["他們兩年內建好那座橋。", "They built the bridge ______ two years.", "in", "at|on|in|by|during", "in 可表示花了多久完成。"],
        ["請稍等，校長很快會來。", "Please wait. The principal will come ______ a moment.", "in", "at|on|in|by|until", "in a moment 表示很快。"],
        ["我能在一星期內完成那幅畫。", "I can finish the painting ______ a week.", "in", "at|on|in|by|until", "in 可表示完成所需時間。"],
        ["火警演習三分鐘後開始。", "The fire drill will start ______ three minutes.", "in", "at|on|in|by|during", "in + 時間表示幾久後。"],
        ["我們在二十分鐘內走到學校。", "We walked to school ______ twenty minutes.", "in", "at|on|in|by|during", "in 可表示花了多久。"],
        ["她一晚內讀完那本小說。", "She read the novel ______ one night.", "in", "at|on|in|by|during", "in 可表示完成所需時間。"],

        ["請在星期三或之前交功課。", "Please submit your homework ______ Wednesday.", "by", "in|on|at|by|until", "by 表示不遲於某時間。"],
        ["我必須在星期五或之前完成報告。", "I must finish this report ______ Friday.", "by", "in|on|at|by|until", "deadline 用 by。"],
        ["你需要在晚上十點前回家。", "You need to be home ______ 10 pm.", "by", "in|on|at|by|until", "by 10 pm 表示十點或之前。"],
        ["請在星期五前回覆。", "Please reply ______ Friday.", "by", "in|on|at|by|until", "限期用 by。"],
        ["所有學生要在八點前到達。", "All students must arrive ______ eight o'clock.", "by", "in|on|at|by|until", "by 表示不遲於。"],
        ["你要在月底前還書。", "You must return the book ______ the end of the month.", "by", "in|on|at|by|until", "by the end of 是限期。"],
        ["請在明天前完成表格。", "Please finish the form ______ tomorrow.", "by", "in|on|at|by|until", "by tomorrow 表示明天或之前。"],
        ["我們要在午飯前提交海報。", "We have to submit the poster ______ lunchtime.", "by", "in|on|at|by|until", "by lunchtime 表示午飯時間或之前。"],
        ["火車應該在六點前到達。", "The train should arrive ______ six o'clock.", "by", "in|on|at|by|until", "by six o'clock 表示最遲六點。"],
        ["我會在月底前付錢。", "I will pay the money ______ the end of the month.", "by", "in|on|at|by|until", "by the end of 表示期限。"],
        ["報名表必須在星期一前送交。", "The application form must be handed in ______ Monday.", "by", "in|on|at|by|until", "限期用 by。"],
        ["請在演出開始前坐好。", "Please be seated ______ the start of the show.", "by", "in|on|at|by|until", "by the start 表示開始前或開始時。"],
        ["我們必須在天黑前離開。", "We must leave ______ dark.", "by", "in|on|at|by|until", "by dark 表示天黑前。"],
        ["你要在考試前溫習好。", "You should revise everything ______ the exam.", "by", "in|on|at|by|until", "by the exam 表示考試前完成。"],
        ["請在今天下午三點前交表。", "Please hand in the form ______ 3 pm today.", "by", "in|on|at|by|until", "deadline 用 by。"],
        ["我們希望在聖誕節前完成工程。", "We hope to finish the work ______ Christmas.", "by", "in|on|at|by|during", "by Christmas 表示聖誕前完成。"],
        ["媽媽叫我在晚飯前回家。", "Mum told me to come home ______ dinner.", "by", "in|on|at|by|until", "by dinner 表示晚飯前或晚飯時。"],
        ["請在下課前收拾好書包。", "Please pack your schoolbag ______ the end of the lesson.", "by", "in|on|at|by|until", "by the end 表示限期。"],
        ["我們需要在假期前完成專題。", "We need to finish the project ______ the holiday.", "by", "in|on|at|by|during", "by the holiday 表示假期前。"],
        ["他保證在星期六前寄出包裹。", "He promised to send the parcel ______ Saturday.", "by", "in|on|at|by|until", "by Saturday 表示星期六或之前。"],

        ["請等到我回來。", "Please wait ______ I come back.", "until", "by|during|until|in|at", "until 表示持續到某時間為止。"],
        ["你可以留在這裡直到六點。", "You can stay here ______ six o'clock.", "until", "by|during|until|in|at", "until 表示一直到六點。"],
        ["圖書館開放到晚上八點。", "The library is open ______ 8 pm.", "until", "by|during|until|in|at", "open until 表示開放到某時間。"],
        ["我們一直等到巴士到達。", "We waited ______ the bus arrived.", "until", "by|during|until|in|at", "wait until 表示等到。"],
        ["她沒有睡覺直到午夜。", "She did not sleep ______ midnight.", "until", "by|during|until|in|at", "not ... until 表示直到...才。"],
        ["請保留收據直到活動完結。", "Please keep the receipt ______ the event ends.", "until", "by|during|until|in|at", "until 表示一直保留到。"],
        ["他一直工作到深夜。", "He worked ______ late at night.", "until", "by|during|until|in|at", "work until 表示工作到某時間。"],
        ["我們不會離開直到老師准許。", "We will not leave ______ the teacher allows us.", "until", "by|during|until|in|at", "not leave until 表示直到...才離開。"],
        ["你應該等到綠燈才過馬路。", "You should wait ______ the light turns green.", "until", "by|during|until|in|at", "wait until 表示等到。"],
        ["店舖營業到晚上十點。", "The shop stays open ______ 10 pm.", "until", "by|during|until|in|at", "stay open until 表示營業到。"],
        ["我們會一直練習到比賽開始。", "We will practise ______ the match starts.", "until", "by|during|until|in|at", "until 表示持續到開始。"],
        ["我會等到你完成。", "I will wait ______ you finish.", "until", "by|during|until|in|at", "until 後可接子句。"],
        ["他直到去年才學游泳。", "He did not learn to swim ______ last year.", "until", "by|during|until|in|at", "not ... until 表示直到...才。"],
        ["請留在課室直到鐘聲響起。", "Please stay in the classroom ______ the bell rings.", "until", "by|during|until|in|at", "stay until 表示留到。"],
        ["她看書看到凌晨兩點。", "She read ______ two in the morning.", "until", "by|during|until|in|at", "read until 表示讀到某時間。"],
        ["我們不會知道結果直到明天。", "We will not know the result ______ tomorrow.", "until", "by|during|until|in|at", "not know until 表示直到...才知道。"],
        ["孩子們玩到晚飯時間。", "The children played ______ dinner time.", "until", "by|during|until|in|at", "play until 表示玩到某時間。"],
        ["請等到你的名字被叫到。", "Please wait ______ your name is called.", "until", "by|during|until|in|at", "wait until 後接子句。"],
        ["他沒有道歉直到老師提醒他。", "He did not apologise ______ the teacher reminded him.", "until", "by|during|until|in|at", "not ... until 表示直到...才。"],
        ["我們會留在學校直到雨停。", "We will stay at school ______ the rain stops.", "until", "by|during|until|in|at", "until 表示直到某事發生。"],

        ["電影期間不要說話。", "Don't talk ______ the movie.", "during", "in|at|on|during|by", "during + 名詞表示期間。"],
        ["我們在飛行期間睡覺。", "We slept ______ the flight.", "during", "in|at|on|during|by", "during the flight 表示飛行期間。"],
        ["我在考試期間感到緊張。", "I felt nervous ______ the exam.", "during", "in|at|on|during|by", "during + 事件名詞。"],
        ["請在會議期間保持安靜。", "Please keep quiet ______ the meeting.", "during", "in|at|on|during|by", "during the meeting 表示會議期間。"],
        ["很多學生在午飯期間打球。", "Many students play ball games ______ lunchtime.", "during", "in|at|on|during|by", "during lunchtime 表示午飯期間。"],
        ["我在假期期間看了很多書。", "I read many books ______ the holiday.", "during", "in|at|on|during|by", "during the holiday 表示假期期間。"],
        ["我們在暴風雨期間留在室內。", "We stayed indoors ______ the storm.", "during", "in|at|on|during|by", "during the storm 表示風暴期間。"],
        ["她在課堂期間做筆記。", "She took notes ______ the lesson.", "during", "in|at|on|during|by", "during the lesson 表示課堂期間。"],
        ["手機在演出期間必須關掉。", "Phones must be switched off ______ the performance.", "during", "in|at|on|during|by", "during the performance 表示演出期間。"],
        ["他在訪問期間問了很多問題。", "He asked many questions ______ the interview.", "during", "in|at|on|during|by", "during the interview 表示訪問期間。"],
        ["我們在停電期間使用手電筒。", "We used torches ______ the blackout.", "during", "in|at|on|during|by", "during the blackout 表示停電期間。"],
        ["孩子們在小息期間吃小食。", "The children ate snacks ______ recess.", "during", "in|at|on|during|by", "during recess 表示小息期間。"],
        ["她在旅程期間拍了很多相。", "She took many photos ______ the trip.", "during", "in|at|on|during|by", "during the trip 表示旅程期間。"],
        ["請在測驗期間不要使用字典。", "Please do not use a dictionary ______ the quiz.", "during", "in|at|on|during|by", "during the quiz 表示測驗期間。"],
        ["我在暑期課程期間認識了新朋友。", "I met new friends ______ the summer course.", "during", "in|at|on|during|by", "during the course 表示課程期間。"],
        ["他在比賽期間受傷。", "He got hurt ______ the match.", "during", "in|at|on|during|by", "during the match 表示比賽期間。"],
        ["請在講座期間關掉聲音。", "Please turn off the sound ______ the talk.", "during", "in|at|on|during|by", "during the talk 表示講座期間。"],
        ["我們在晚飯期間討論旅行。", "We discussed the trip ______ dinner.", "during", "in|at|on|during|by", "during dinner 表示晚飯期間。"],
        ["她在火警演習期間保持冷靜。", "She stayed calm ______ the fire drill.", "during", "in|at|on|during|by", "during the fire drill 表示演習期間。"],
        ["他們在演唱會期間唱歌。", "They sang loudly ______ the concert.", "during", "in|at|on|during|by", "during the concert 表示演唱會期間。"],

        ["商店由上午九點開到下午六點。", "The shop is open ______ 9 am to 6 pm.", "from", "at|on|from|by|between", "from ... to ... 表示由...到...。"],
        ["他星期一至星期五工作。", "He works ______ Monday to Friday.", "from", "between|from|at|on|in", "from ... to ... 表示由...到...。"],
        ["活動由二月開始至四月完結。", "The activity runs ______ February to April.", "from", "between|from|during|by|at", "from ... to ... 表示時間範圍。"],
        ["課堂由九點至十點半。", "The lesson lasts ______ nine to half past ten.", "from", "between|from|during|by|at", "from ... to ... 表示由...到...。"],
        ["圖書館由星期二開到星期六。", "The library opens ______ Tuesday to Saturday.", "from", "between|from|during|by|at", "from ... to ... 表示由...到...。"],
        ["展覽由三月一日至三月十日舉行。", "The exhibition is open ______ 1 March to 10 March.", "from", "between|from|during|by|at", "from ... to ... 表示日期範圍。"],
        ["我由七點溫習到九點。", "I studied ______ seven to nine.", "from", "between|from|during|by|at", "from ... to ... 表示由...到...。"],
        ["巴士服務由清晨運作到午夜。", "The bus service runs ______ dawn to midnight.", "from", "between|from|during|by|at", "from ... to ... 表示時間範圍。"],
        ["他們由早到晚工作。", "They worked ______ morning to night.", "from", "between|from|during|by|at", "from ... to ... 表示由...到...。"],
        ["訓練由星期三開始至星期五結束。", "The training lasts ______ Wednesday to Friday.", "from", "between|from|during|by|at", "from ... to ... 表示由...到...。"],
        ["我在二零一八年至二零二零年之間住在澳門。", "I lived in Macau ______ 2018 and 2020.", "between", "from|to|between|in|at", "between ... and ... 表示兩個時間之間。"],
        ["請在三點至四點之間打電話給我。", "Please call me ______ three and four.", "between", "from|to|between|in|at", "between ... and ... 表示兩個時間之間。"],
        ["測驗會在星期一和星期三之間進行。", "The quiz will be held ______ Monday and Wednesday.", "between", "from|to|between|on|at", "between ... and ... 表示兩個日期之間。"],
        ["她在午飯和晚飯之間吃水果。", "She eats fruit ______ lunch and dinner.", "between", "from|to|between|during|at", "between ... and ... 表示兩件事之間。"],
        ["巴士會在六點到六點半之間到達。", "The bus will arrive ______ six and half past six.", "between", "from|to|between|by|at", "between ... and ... 表示兩個時間之間。"],
        ["我們在聖誕節和新年之間放假。", "We have a holiday ______ Christmas and New Year.", "between", "from|to|between|during|at", "between ... and ... 表示兩個節日之間。"],
        ["請在五月和六月之間完成計劃。", "Please finish the plan ______ May and June.", "between", "from|to|between|in|by", "between ... and ... 表示兩個月份之間。"],
        ["他在小息和午飯之間完成家課。", "He finished his homework ______ recess and lunch.", "between", "from|to|between|during|at", "between ... and ... 表示兩個時間點之間。"],
        ["面試安排在十點和十一點之間。", "The interview is scheduled ______ ten and eleven.", "between", "from|to|between|by|at", "between ... and ... 表示兩個鐘點之間。"],
        ["我通常在星期二和星期四之間溫習。", "I usually revise ______ Tuesday and Thursday.", "between", "from|to|between|on|at", "between ... and ... 表示兩個日子之間。"],

        ["我自二零二零年起住在這裡。", "I have lived here ______ 2020.", "since", "since|for|during|in|at", "since + 起點時間。"],
        ["她自星期一以來一直生病。", "She has been sick ______ Monday.", "since", "since|for|during|on|at", "since + 起點時間。"],
        ["我們自上星期起沒有見面。", "We have not met ______ last week.", "since", "since|for|during|in|at", "since + 起點時間。"],
        ["他自早上八點起一直在溫習。", "He has been studying ______ 8 am.", "since", "since|for|during|in|at", "since + 具體起點時間。"],
        ["我自小學起認識她。", "I have known her ______ primary school.", "since", "since|for|during|in|at", "since + 起點階段。"],
        ["他自昨天起沒有吃東西。", "He has not eaten anything ______ yesterday.", "since", "since|for|during|in|at", "since + 起點時間。"],
        ["他們自十月起一直練習。", "They have practised ______ October.", "since", "since|for|during|in|at", "since + 起點月份。"],
        ["這間店自一九九五年起營業。", "This shop has been open ______ 1995.", "since", "since|for|during|in|at", "since + 起點年份。"],
        ["我自那次比賽後沒有見過他。", "I have not seen him ______ that match.", "since", "since|for|during|in|at", "since + 起點事件。"],
        ["她自午飯後一直在睡覺。", "She has been sleeping ______ lunchtime.", "since", "since|for|during|in|at", "since + 起點時間。"],
        ["我在這間學校讀了三年。", "I have studied at this school ______ three years.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["他等了二十分鐘。", "He waited ______ twenty minutes.", "for", "since|for|during|in|at", "for + 持續多久。"],
        ["我們做了兩小時功課。", "We did homework ______ two hours.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["她在日本住了六個月。", "She lived in Japan ______ six months.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["火車延誤了一小時。", "The train was delayed ______ an hour.", "for", "since|for|during|in|at", "for + 持續時間。"],
        ["我已經認識 Peter 十年。", "I have known Peter ______ ten years.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["他們在公園玩了整個下午。", "They played in the park ______ the whole afternoon.", "for", "since|for|during|in|at", "for the whole afternoon 表示持續整個下午。"],
        ["我們排隊排了半小時。", "We queued ______ half an hour.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["她已經病了幾天。", "She has been ill ______ a few days.", "for", "since|for|during|in|at", "for + 一段時間。"],
        ["我練習鋼琴練了一個晚上。", "I practised the piano ______ one evening.", "for", "since|for|during|in|at", "for + 持續時間。"],

        ["請在上課前洗手。", "Please wash your hands ______ the lesson.", "before", "before|after|during|by|until", "before 表示在...之前。"],
        ["我們晚飯後做功課。", "We do homework ______ dinner.", "after", "before|after|during|by|until", "after 表示在...之後。"],
        ["她在考試前感到緊張。", "She felt nervous ______ the exam.", "before", "before|after|during|by|until", "before the exam 表示考試前。"],
        ["比賽後我們拍照。", "We took photos ______ the match.", "after", "before|after|during|by|until", "after the match 表示比賽後。"],
        ["請在睡覺前關燈。", "Please turn off the lights ______ bedtime.", "before", "before|after|during|by|until", "before bedtime 表示睡前。"],
        ["我放學後去圖書館。", "I go to the library ______ school.", "after", "before|after|during|by|until", "after school 表示放學後。"],
        ["早餐前不要吃糖果。", "Do not eat sweets ______ breakfast.", "before", "before|after|during|by|until", "before breakfast 表示早餐前。"],
        ["午飯後我們有中文課。", "We have Chinese lessons ______ lunch.", "after", "before|after|during|by|until", "after lunch 表示午飯後。"],
        ["請在旅行前檢查你的背包。", "Please check your bag ______ the trip.", "before", "before|after|during|by|until", "before the trip 表示旅行前。"],
        ["會議後她寫了一封電郵。", "She wrote an email ______ the meeting.", "after", "before|after|during|by|until", "after the meeting 表示會議後。"],
        ["我昨天下午見到他。", "I saw him ______ yesterday afternoon.", "X (no word)", "in|on|at|by|X (no word)", "yesterday 前不用介詞。"],
        ["我們下星期去日本。", "We are going to Japan ______ next week.", "X (no word)", "in|on|at|by|X (no word)", "next 前不用介詞。"],
        ["我每天早上刷牙。", "I brush my teeth ______ every morning.", "X (no word)", "in|on|at|by|X (no word)", "every 前不用介詞。"],
        ["你昨晚有外出嗎？", "Did you go out ______ last night?", "X (no word)", "in|on|at|by|X (no word)", "last 前不用介詞。"],
        ["她今天早上遲到了。", "She was late ______ this morning.", "X (no word)", "in|on|at|by|X (no word)", "this 前不用介詞。"],
        ["我們明天晚上會再討論。", "We will discuss it again ______ tomorrow evening.", "X (no word)", "in|on|at|by|X (no word)", "tomorrow 前不用介詞。"],
        ["他每星期五都踢足球。", "He plays football ______ every Friday.", "X (no word)", "in|on|at|by|X (no word)", "every 前不用介詞。"],
        ["我上個月買了這本書。", "I bought this book ______ last month.", "X (no word)", "in|on|at|by|X (no word)", "last 前不用介詞。"],
        ["她下星期一開始新工作。", "She starts her new job ______ next Monday.", "X (no word)", "in|on|at|by|X (no word)", "next 前不用介詞。"],
        ["我們今年夏天會參加營隊。", "We will join a camp ______ this summer.", "X (no word)", "in|on|at|by|X (no word)", "this 前不用介詞。"]
    ];

    window.GRAMMAR_PREPOSITION_TIME_BANK = rows.map((row, index) => {
        const [chinese, question, correctText, optionText, explanation] = row;
        const options = optionText.split('|');
        return {
            id: `preposition_time_${String(index + 1).padStart(3, '0')}`,
            chinese,
            question,
            options,
            answer: correctText,
            correctIndex: Math.max(0, options.indexOf(correctText)),
            explanation: `⭐ 規則：${explanation}`
        };
    });
})();
