// Generated by scripts/generate-grammar-workshop-overrides-dart.js.
// Edit scripts/grammar-workshop-answer-overrides.js, then regenerate.
class WorkshopChoiceAnswerOverride {
  const WorkshopChoiceAnswerOverride({
    required this.acceptedAnswers,
    required this.explanation,
    this.question,
    this.chinese,
    this.present,
    this.past,
    this.pp,
    this.ing,
    this.acceptedTokenSets = const [],
  });

  final List<String> acceptedAnswers;
  final String explanation;
  final String? question;
  final String? chinese;
  final String? present;
  final String? past;
  final String? pp;
  final String? ing;
  final List<List<String>> acceptedTokenSets;
}

const grammarWorkshopChoiceAnswerOverrides =
    <String, WorkshopChoiceAnswerOverride>{
  'PREPOSITION_OF_PLACE/preposition_place_008': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: '⭐ 規則：at the station 強調地點；in the station 強調在車站內，兩者在此都成立。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_010': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'in'],
    explanation: '⭐ 規則：on Nathan Road 常見於美式英語；in Nathan Road 亦見於英式／香港英語。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_012': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'on'],
    explanation: '⭐ 規則：in the street 和 on the street 都可表示在街上，視英美用法而異。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_016': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: '⭐ 規則：at school 指身處／上學；in school 亦可表示正在學校或就學。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_017': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation: '⭐ 規則：in the park 強調園內；at the park 強調公園這個地點。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_019': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: '⭐ 規則：at the entrance 和 by the entrance 都可表示在入口附近。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_028': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['into', 'in'],
    explanation:
        '⭐ 規則：pour water into the glass 強調方向；pour water in the glass 亦是自然用法。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_029': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['out of', 'from'],
    explanation:
        '⭐ 規則：take the book out of the bag 強調移出；from the bag 亦表示從袋中取出。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_031': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'by'],
    explanation: '⭐ 規則：travel on a plane 描述身處飛機；travel by plane 描述交通方式。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_033': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'in'],
    explanation: '⭐ 規則：on the train 是常見搭乘說法；in the train 亦可描述人在車廂內。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_040': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['below', 'under'],
    explanation: '⭐ 規則：below zero 和 under zero 都可表示低於零度。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_043': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['opposite', 'facing'],
    explanation:
        '⭐ 規則：opposite the post office 表示在對面；facing the post office 亦可表示面向它。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_044': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['next', 'close', 'near'],
    explanation: '⭐ 規則：next to 最貼近；close to 和 near to 在此亦可表示附近。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_055': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['around', 'round'],
    explanation: '⭐ 規則：around the building 和 round the building 都可表示繞着建築物。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_056': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation: '⭐ 規則：in the corner 強調角落內；at the corner 亦可指出角落位置。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_057': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by', 'on'],
    explanation: '⭐ 規則：at/by the corner 都表示在街角附近；on the corner 亦是常見位置說法。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_058': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'on'],
    explanation:
        '⭐ 規則：at the top of the page 和 on the top of the page 在此都可指出頁面上方位置。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_081': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: '⭐ 規則：at the bus stop 和 by the bus stop 都可表示在巴士站位置。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_083': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'on'],
    explanation: '⭐ 規則：in the street 和 on the street 都可表示在街上玩。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_088': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['over', 'on'],
    explanation:
        '⭐ 規則：put a blanket over the child 強調覆蓋；on the child 亦可表示把毛氈放在孩子身上。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_089': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['under', 'below', 'in'],
    explanation: '⭐ 規則：under/below the water 強調水面以下；in the water 亦描述潛艇所在位置。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_090': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['below', 'under'],
    explanation: '⭐ 規則：below mine 和 under mine 都可表示樓層位置較低。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_102': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['around', 'round'],
    explanation: '⭐ 規則：around the house 和 round the house 都可表示圍繞房屋。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_103': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['by', 'at'],
    explanation: '⭐ 規則：sit by the fire 是常見說法；sit at the fire 亦可表示坐在火爐旁。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_105': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['close', 'near', 'next'],
    explanation: '⭐ 規則：close to、near to 和 next to 都可配合句中的 to 表示鄰近。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_108': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['among', 'in'],
    explanation: '⭐ 規則：among the crowd 強調在人群之間；in the crowd 亦表示在人群中。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_110': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['under', 'below'],
    explanation: '⭐ 規則：under the bed 是常見說法；below the bed 亦可表示在床的下方。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_114': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: '⭐ 規則：at the cinema 強調地點／活動；in the cinema 強調在戲院內。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_123': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'on'],
    explanation:
        '⭐ 規則：at the bottom of the page 和 on the bottom of the page 在此都指出頁面底部。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_127': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation:
        '⭐ 規則：at the front of the queue 是常見搭配；in the front of the queue 亦可表示在隊伍前段。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_131': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation: '⭐ 規則：work in an office 強調辦公室內；work at an office 亦可指工作地點。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_135': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['by', 'at'],
    explanation: '⭐ 規則：by the door 強調門旁；at the door 亦可表示門口位置。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_137': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['across', 'over'],
    explanation:
        '⭐ 規則：walk across the grass 強調橫過；walk over the grass 亦可表示走過草地。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_141': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['around', 'round'],
    explanation: '⭐ 規則：go around the sun 和 go round the sun 都可表示環繞太陽。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_142': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['around', 'round', 'about'],
    explanation: '⭐ 規則：walk around/round/about the room 都可表示在房內來回走動。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_147': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['around', 'round'],
    explanation: '⭐ 規則：turn around 和 turn round 都可表示轉身。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_157': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: '⭐ 規則：at the bus stop 和 by the bus stop 都可表示在巴士站附近會面。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_158': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation:
        '⭐ 規則：at the traffic lights 和 by the traffic lights 都可表示在交通燈位置等候。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_169': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['over', 'above'],
    explanation: '⭐ 規則：over the house 強調飛越；above the house 亦表示在房屋上空。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_171': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'in'],
    explanation: '⭐ 規則：get on the boat 常用於較大船隻；get in the boat 常用於較小船隻。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_174': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['across', 'through'],
    explanation: '⭐ 規則：across the park 強調由一邊到另一邊；through the park 亦可表示穿過公園。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_177': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['below', 'under'],
    explanation: '⭐ 規則：below freezing 和 under freezing 都可表示低於冰點。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_179': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['under', 'below'],
    explanation: '⭐ 規則：under the mat 是常見說法；below the mat 亦可表示位置在墊下。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_184': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'to'],
    explanation: '⭐ 規則：point at 強調指向動作；point to 亦可表示指出該圖片。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_198': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: '⭐ 規則：sit at the back 和 sit in the back 都可表示坐在後方。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_199': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'with'],
    explanation: '⭐ 規則：write in ink 是固定搭配；write with ink 亦可描述所用材料。',
  ),
  'PREPOSITION_OF_PLACE/preposition_place_200': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'in'],
    explanation: '⭐ 規則：write with a pencil 強調工具；write in pencil 亦是常見寫法。',
  ),
  'PHRASAL_VERB/phrasal_verb_038': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['calm down', 'cool down'],
    explanation: 'calm down 和 cool down 在此都可表示先冷靜／平靜下來。',
  ),
  'PHRASAL_VERB/phrasal_verb_039': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['cheer up'],
    explanation:
        'cheer up + 名詞，或 cheer + 代名詞 + up。此題改用名詞受詞，避免錯誤的 cheer up you。',
    question: 'Do not be sad. I will try to ______ my friend.',
    chinese: '別傷心，我會努力令朋友開心起來。',
  ),
  'PHRASAL_VERB/phrasal_verb_090': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['cool down', 'calm down'],
    explanation: '運動後 cool down 指放鬆整理；calm down 在「平靜下來」意思下亦符合句子。',
  ),
  'COMPOUND_ADJ/compound_adj_015': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'of'],
    explanation: 'careful with 強調小心處理；careful of 亦可表示提防熱水。',
  ),
  'COMPOUND_ADJ/compound_adj_026': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'by'],
    explanation: 'confronted with 強調面對情況；confronted by 亦可表示被一群示威者迎面堵住。',
  ),
  'COMPOUND_ADJ/compound_adj_028': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'to'],
    explanation: 'connected with 和 connected to 在此都可表示兩者有關連。',
  ),
  'COMPOUND_ADJ/compound_adj_032': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'by'],
    explanation: 'crowded with 是常見搭配；crowded by 亦可按被動結構表示被食客擠滿。',
  ),
  'COMPOUND_ADJ/compound_adj_037': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['from', 'than'],
    explanation: 'different from 是標準常見寫法；different than 亦見於美式英語。',
  ),
  'COMPOUND_ADJ/compound_adj_048': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['from', 'of'],
    explanation: 'free from worries 和 free of worries 都可表示沒有憂慮。',
  ),
  'COMPOUND_ADJ/compound_adj_049': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to', 'with'],
    explanation: 'friendly to tourists 和 friendly with tourists 在此都可表示對遊客友善。',
  ),
  'COMPOUND_ADJ/compound_adj_057': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['of', 'about'],
    explanation: 'ignorant of 和 ignorant about political issues 都可表示對議題不了解。',
  ),
  'COMPOUND_ADJ/compound_adj_078': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'among'],
    explanation: 'popular with teenagers 和 popular among teenagers 都是自然搭配。',
  ),
  'COMPOUND_ADJ/compound_adj_080': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation: 'proficient in French 和 proficient at French 都可表示精通法語。',
  ),
  'COMPOUND_ADJ/compound_adj_091': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation:
        'skilful in graphic design 和 skilful at graphic design 都可表示擅長該技能。',
  ),
  'COMPOUND_ADJ/compound_adj_092': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['for', 'about'],
    explanation:
        'sorry for the inconvenience 和 sorry about the inconvenience 都是自然道歉說法。',
  ),
  'COMPOUND_ADJ/compound_adj_094': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at'],
    explanation:
        'successful in improving 和 successful at improving 在此都可表示成功做到。',
  ),
  'COMPOUND_ADJ/compound_adj_097': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['of', 'about'],
    explanation: 'sure of the route 和 sure about the route 都可表示確定路線。',
  ),
  'COMPOUND_ADJ/compound_adj_098': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['of', 'about'],
    explanation: 'suspicious of 和 suspicious about the statements 都可表示有所懷疑。',
  ),
  'COMPOUND_ADJ/compound_adj_102': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to', 'for'],
    explanation:
        'useful to web designers 和 useful for web designers 都可表示對設計師有用。',
  ),
  'COMPOUND_ADJ/compound_adj_103': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: 'weak at socializing 和 weak in socializing 都可表示不擅長社交。',
  ),
  'COMPOUND_ADJ/compound_adj_110': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: 'good at math 和 good in math 都是可見的英美地區用法。',
  ),
  'COMPOUND_ADJ/compound_adj_112': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['about', 'for'],
    explanation: 'excited about the trip 是較正式寫法；excited for the trip 亦是常見口語。',
  ),
  'COMPOUND_ADJ/compound_adj_123': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['for', 'about'],
    explanation: 'sorry for being late 和 sorry about being late 都可表達同一歉意。',
  ),
  'COMPOUND_ADJ/compound_adj_133': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to', 'with'],
    explanation: 'friendly to everyone 和 friendly with everyone 在此都可表示待人友善。',
  ),
  'COMPOUND_ADJ/compound_adj_134': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'of'],
    explanation: 'bored with the game 是常見寫法；bored of the game 亦常見於英式口語。',
  ),
  'COMPOUND_ADJ/compound_adj_137': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: 'excellent at dancing 和 excellent in dancing 都可表示舞蹈出色。',
  ),
  'COMPOUND_ADJ/compound_adj_144': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: 'surprised at the news 和 surprised by the news 都是自然搭配。',
  ),
  'COMPOUND_ADJ/compound_adj_145': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: 'amazed at her talent 和 amazed by her talent 都是自然搭配。',
  ),
  'COMPOUND_ADJ/compound_adj_146': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'at'],
    explanation:
        'disappointed with the result 和 disappointed at the result 都可表示對結果失望。',
  ),
  'COMPOUND_ADJ/compound_adj_154': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['about', 'of'],
    explanation:
        'doubtful about his ability 和 doubtful of his ability 都可表示懷疑能力。',
  ),
  'COMPOUND_ADJ/compound_adj_157': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['about', 'for'],
    explanation:
        'excited about the holiday 是較正式寫法；excited for the holiday 亦是常見口語。',
  ),
  'COMPOUND_ADJ/compound_adj_158': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['about', 'at', 'with'],
    explanation: 'annoyed about/at/with the noise 在此都可表示受噪音困擾。',
  ),
  'COMPOUND_ADJ/compound_adj_159': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'at'],
    explanation: 'annoyed with me 和 annoyed at me 都可表示對我生氣。',
  ),
  'COMPOUND_ADJ/compound_adj_164': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['of', 'about'],
    explanation: 'sure of the answer 和 sure about the answer 都可表示確定答案。',
  ),
  'COMPOUND_ADJ/compound_adj_165': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['of', 'about'],
    explanation: 'certain of success 和 certain about success 都可表示確信會成功。',
  ),
  'COMPOUND_ADJ/compound_adj_169': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'in'],
    explanation: 'present at the meeting 和 present in the meeting 都可表示人在會議中。',
  ),
  'COMPOUND_ADJ/compound_adj_173': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['with', 'about'],
    explanation:
        'delighted with the news 和 delighted about the news 都可表示對消息感到高興。',
    question: 'She is delighted ______ the news.',
  ),
  'COMPOUND_ADJ/compound_adj_174': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['by', 'with'],
    explanation: 'impressed by his work 和 impressed with his work 都是自然搭配。',
  ),
  'COMPOUND_ADJ/compound_adj_175': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'by'],
    explanation: 'shocked at the price 和 shocked by the price 都是自然搭配。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_005':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['further', 'farther'],
    explanation: 'further 和 farther 都可作 far 的比較級；抽象意思通常較常用 further。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_011':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['farther', 'further'],
    explanation: 'farther 和 further 都可表示走得更遠。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_033':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['the eldest', 'the oldest'],
    explanation: '在家庭成員中，the eldest 和 the oldest 都可表示最年長。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_036':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['elder', 'older'],
    explanation: 'elder brother 和 older brother 都可表示哥哥。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_046':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['calmer', 'more calm'],
    explanation: 'calmer 和 more calm 都是可接受的比較形式。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_052':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['more', 'the most'],
    explanation: '缺少明確比較範圍時，more 可表示更多；語境指所有人之中最多時可用 the most。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_056':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['easier', 'more convenient'],
    explanation: 'easier 和 more convenient 在此都符合令聯絡祖父更容易／方便的意思。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_060':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['simpler', 'more simple'],
    explanation: 'simpler 和 more simple 都可作 simple 的比較級。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_061':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['more easily', 'more comfortably'],
    explanation: 'more easily 和 more comfortably 都符合較容易／輕鬆操作的語境。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_064':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['more comfortably', 'more easily'],
    explanation: 'more comfortably 和 more easily 都符合較舒適／容易閱讀的語境。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_068':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['more convenient', 'easier'],
    explanation: 'more convenient 和 easier 都符合令撥號更方便／容易的意思。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_097':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['more quickly', 'faster'],
    explanation: 'more quickly 和 faster 都可作比較副詞。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_116':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['the quietest', 'the most quiet'],
    explanation: 'the quietest 是較常見形式；the most quiet 亦可接受。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_128':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['clearer', 'more clear'],
    explanation: 'clearer 是較常見形式；more clear 亦可接受。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_129':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['the clearest', 'the most clear'],
    explanation: 'the clearest 是較常見形式；the most clear 亦可接受。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_138':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['farther', 'further'],
    explanation: 'farther 和 further 都可比較實際距離。',
  ),
  'COMPARATIVE_SUPERLATIVE/comparative_superlative_139':
      WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['the farthest', 'the furthest'],
    explanation: 'the farthest 和 the furthest 都可表示最遠。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_024': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['go', 'going'],
    explanation: 'see him go 強調看見完整動作；see him going 強調看見動作進行中，中文在此兩者皆可。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_032': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to rain', 'raining'],
    explanation: 'begin to rain 和 begin raining 都可表示開始下雨。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_038': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to fix', 'fix'],
    explanation: 'help to fix 和 help fix 都是標準用法。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_058': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['to see', 'seeing'],
    explanation: 'can\'t bear to see 和 can\'t bear seeing 都可表示無法忍受看見。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_075': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['stealing', 'having stolen'],
    explanation: 'admitted stealing 和 admitted having stolen 都可表示承認已偷錢。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_079': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['breaking', 'having broken'],
    explanation: 'denied breaking 和 denied having broken 都可表示否認已打破花瓶。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_080': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['waiting', 'to wait'],
    explanation: 'dislike waiting 和 dislike to wait 在此都可表示不喜歡等候。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_097': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['flying', 'fly'],
    explanation:
        'look at the birds flying 強調進行中；look at the birds fly 亦可表示觀看牠們飛翔。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_099': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['laughing', 'but laugh'],
    explanation: 'couldn\'t help laughing 和 couldn\'t help but laugh 都表示忍不住笑。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_100': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['waiting', 'to wait'],
    explanation: 'can\'t stand waiting 和 can\'t stand to wait 都可表示受不了排隊。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_107': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['posting', 'having posted'],
    explanation: 'remember posting 和 remember having posted 都可表示記得已寄過信。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_112': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['turning', 'having turned'],
    explanation: 'remember turning off 和 remember having turned off 都可表示記得已關燈。',
  ),
  'INFINITIVE_GERUND/infinitive_gerund_118': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['saying', 'having said'],
    explanation: 'regret saying 和 regret having said 都可表示後悔已說過。',
  ),
  'VERB_TABLE/verb_bid_539a9a258cfe': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'bid 表示出價時常用 bid-bid-bid；表示吩咐時亦可用 bade/bidden。',
    past: 'bid/bade',
    pp: 'bid/bidden',
  ),
  'VERB_TABLE/verb_broadcast_b040d43e09ee': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'broadcast 和 broadcasted 都是標準過去式／過去分詞。',
    past: 'broadcast/broadcasted',
    pp: 'broadcast/broadcasted',
  ),
  'VERB_TABLE/verb_burn_274fae6c27b7': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'burnt 常見於英式英語；burned 常見於美式英語，兩者都正確。',
    past: 'burnt/burned',
    pp: 'burnt/burned',
  ),
  'VERB_TABLE/verb_dive_e9753cc44473': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'dived 是英式及通用形式；dove 是常見美式過去式。',
    past: 'dived/dove',
  ),
  'VERB_TABLE/verb_dream_2aaa497bdfb3': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'dreamt 和 dreamed 都是標準形式。',
    past: 'dreamt/dreamed',
    pp: 'dreamt/dreamed',
  ),
  'VERB_TABLE/verb_dwell_72d4d3fc62ad': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'dwelt 和 dwelled 都是標準形式。',
    past: 'dwelt/dwelled',
    pp: 'dwelt/dwelled',
  ),
  'VERB_TABLE/verb_fit_e75e718b4c75': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'fit 常指合身；fitted 亦常用於安裝／配備，符合題目詞義。',
    past: 'fit/fitted',
    pp: 'fit/fitted',
  ),
  'VERB_TABLE/verb_get_588a3e270241': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'got 是英式常用過去分詞；gotten 是美式英語常見形式。',
    pp: 'got/gotten',
  ),
  'VERB_TABLE/verb_kneel_294e27f39c8f': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'knelt 和 kneeled 都是標準形式。',
    past: 'knelt/kneeled',
    pp: 'knelt/kneeled',
  ),
  'VERB_TABLE/verb_lean_f7666041067e': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'leant 常見於英式英語；leaned 常見於美式英語。',
    past: 'leant/leaned',
    pp: 'leant/leaned',
  ),
  'VERB_TABLE/verb_leap_bf3d3a128c06': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'leapt 和 leaped 都是標準形式。',
    past: 'leapt/leaped',
    pp: 'leapt/leaped',
  ),
  'VERB_TABLE/verb_learn_91fcb76d7dec': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'learnt 常見於英式英語；learned 常見於美式英語。',
    past: 'learnt/learned',
    pp: 'learnt/learned',
  ),
  'VERB_TABLE/verb_practise_20bde8dab6ba': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'practise 是英式動詞拼法；practice 是美式動詞拼法，兩套變化都接受。',
    present: 'practise/practice',
    past: 'practised/practiced',
    pp: 'practised/practiced',
    ing: 'practising/practicing',
  ),
  'VERB_TABLE/verb_sew_58c5e1c023ba': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'sewn 和 sewed 都可作 sew 的過去分詞。',
    pp: 'sewn/sewed',
  ),
  'VERB_TABLE/verb_shine_c4678785c64e': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'shone 常指發光；shined 常指擦亮，題目詞義同時包括兩者。',
    past: 'shone/shined',
    pp: 'shone/shined',
  ),
  'VERB_TABLE/verb_shrink_e5a0f42cb856': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'shrank/shrunk 可作過去式；shrunk/shrunken 可作過去分詞。',
    past: 'shrank/shrunk',
    pp: 'shrunk/shrunken',
  ),
  'VERB_TABLE/verb_smell_642ec52d9f8c': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'smelt 常見於英式英語；smelled 常見於美式英語。',
    past: 'smelt/smelled',
    pp: 'smelt/smelled',
  ),
  'VERB_TABLE/verb_sow_6f368d33f08c': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'sown 和 sowed 都可作 sow 的過去分詞。',
    pp: 'sown/sowed',
  ),
  'VERB_TABLE/verb_speed_01947bf6dfee': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'sped 常用於一般加速；speeded 亦是標準形式。',
    past: 'sped/speeded',
    pp: 'sped/speeded',
  ),
  'VERB_TABLE/verb_spell_315a810c3854': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'spelt 常見於英式英語；spelled 常見於美式英語。',
    past: 'spelt/spelled',
    pp: 'spelt/spelled',
  ),
  'VERB_TABLE/verb_spill_48ea338f670c': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'spilt 常見於英式英語；spilled 常見於美式英語。',
    past: 'spilt/spilled',
    pp: 'spilt/spilled',
  ),
  'VERB_TABLE/verb_spit_ec34bc8727c6': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'spat 常見於英式英語；spit 是常見美式過去式／過去分詞。',
    past: 'spat/spit',
    pp: 'spat/spit',
  ),
  'VERB_TABLE/verb_spoil_669a90e49308': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'spoilt 常見於英式英語；spoiled 常見於美式英語。',
    past: 'spoilt/spoiled',
    pp: 'spoilt/spoiled',
  ),
  'VERB_TABLE/verb_spring_5ee7e421b4b4': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'sprang 是傳統過去式；sprung 亦常見於現代用法。',
    past: 'sprang/sprung',
  ),
  'VERB_TABLE/verb_stink_528cac308d5d': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'stank 和 stunk 都可作 stink 的過去式。',
    past: 'stank/stunk',
  ),
  'VERB_TABLE/verb_travel_e239864116a7': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '雙寫 l 是英式拼法；單寫 l 是美式拼法。',
    past: 'travelled/traveled',
    pp: 'travelled/traveled',
    ing: 'travelling/traveling',
  ),
  'VERB_TABLE/verb_tread_cdb1de1b1e49': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'trodden 是常見過去分詞；trod 亦可作過去分詞。',
    pp: 'trodden/trod',
  ),
  'VERB_TABLE/verb_wake_b18cc9810933': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'woke/woken 最常見；waked 亦是標準但較少見。',
    past: 'woke/waked',
    pp: 'woken/waked',
  ),
  'VERB_TABLE/verb_weave_f2615585033d': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'wove/woven 常指編織；weaved 常指迂迴穿行，題目詞義包括兩者。',
    past: 'wove/weaved',
    pp: 'woven/weaved',
  ),
  'PRONOUN/pronoun_013': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['me', 'I'],
    explanation: 'It was not me 是自然日常用法；It was not I 是正式、較傳統的主格用法。',
  ),
  'PRONOUN/pronoun_114': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['your'],
    explanation: 'one of 後接複數名詞，再用 in your collection 表示收藏中的一枚。',
    question: 'It looks like one of the beaded brooches in ______ collection.',
  ),
  'INVERSION/inversion_089': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had + subject + p.p. 可改寫成 If + subject + had + p.p.。',
    acceptedTokenSets: [
      [
        'If',
        'he',
        'had',
        'replied',
        'to',
        'me',
        'earlier',
        ',',
        'I',
        'would',
        'have',
        'finished',
        'the',
        'test',
        'properly',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_090': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had I known 和 If I had known 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'I',
        'had',
        'known',
        'the',
        'truth',
        ',',
        'I',
        'would',
        'not',
        'have',
        'believed',
        'the',
        'rumour',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_091': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had the government taken 和 If the government had taken 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'the',
        'government',
        'had',
        'taken',
        'action',
        'earlier',
        ',',
        'the',
        'loss',
        'would',
        'have',
        'been',
        'smaller',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_092': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had she brought 和 If she had brought 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'she',
        'had',
        'brought',
        'an',
        'umbrella',
        ',',
        'she',
        'would',
        'not',
        'have',
        'got',
        'wet',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_093': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had they followed 和 If they had followed 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'they',
        'had',
        'followed',
        'the',
        'advice',
        ',',
        'they',
        'could',
        'have',
        'avoided',
        'this',
        'mistake',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_094': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'Had I revised 和 If I had revised 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'I',
        'had',
        'revised',
        'yesterday',
        ',',
        'I',
        'would',
        'have',
        'felt',
        'more',
        'confident',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_095': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation:
        'Had the teacher not reminded 和 If the teacher had not reminded 意思相同。',
    acceptedTokenSets: [
      [
        'If',
        'the',
        'teacher',
        'had',
        'not',
        'reminded',
        'us',
        ',',
        'we',
        'would',
        'have',
        'missed',
        'the',
        'deadline',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_096': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '地點片語可放句首作倒裝，亦可放在普通主詞—動詞語序之後。',
    acceptedTokenSets: [
      [
        'A',
        'swarm',
        'of',
        'crazy',
        'fans',
        'stood',
        'in',
        'the',
        'airport',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_097': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: 'On the sofa sat a cat 和 A cat sat on the sofa 意思相同。',
    acceptedTokenSets: [
      ['A', 'listless', 'cat', 'sat', 'on', 'the', 'sofa', '.']
    ],
  ),
  'INVERSION/inversion_098': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '地點倒裝亦可改成普通主詞—動詞語序。',
    acceptedTokenSets: [
      [
        'A',
        'shy',
        'new',
        'student',
        'stood',
        'at',
        'the',
        'classroom',
        'door',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_099': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation:
        'On the table lay magazines 和 Magazines lay on the table 意思相同。',
    acceptedTokenSets: [
      ['Several', 'old', 'magazines', 'lay', 'on', 'the', 'table', '.']
    ],
  ),
  'INVERSION/inversion_100': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '地點倒裝亦可改成普通主詞—動詞語序。',
    acceptedTokenSets: [
      [
        'A',
        'small',
        'cafe',
        'stood',
        'at',
        'the',
        'end',
        'of',
        'the',
        'busy',
        'street',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_101': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '地點倒裝亦可改成普通主詞—動詞語序。',
    acceptedTokenSets: [
      [
        'A',
        'group',
        'of',
        'reporters',
        'waited',
        'outside',
        'the',
        'school',
        'gate',
        '.'
      ]
    ],
  ),
  'INVERSION/inversion_102': WorkshopChoiceAnswerOverride(
    acceptedAnswers: [],
    explanation: '地點倒裝亦可改成普通主詞—動詞語序。',
    acceptedTokenSets: [
      ['An', 'ancient', 'temple', 'stood', 'on', 'the', 'hill', '.']
    ],
  ),
  'PREPOSITION_OF_TIME/preposition_time_017': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['at', 'during'],
    explanation: '⭐ 規則：at Easter 是常見節日搭配；during Easter 亦可強調復活節期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_022': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'X (no word)'],
    explanation: '⭐ 規則：on Tuesday afternoon 是完整寫法；美式英語亦常省略 on。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_023': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'X (no word)'],
    explanation: '⭐ 規則：on Sunday morning 是完整寫法；美式英語亦常省略 on。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_032': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'X (no word)'],
    explanation: '⭐ 規則：on Saturday evening 是完整寫法；美式英語亦常省略 on。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_038': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['on', 'X (no word)'],
    explanation: '⭐ 規則：on Wednesday morning 是完整寫法；美式英語亦常省略 on。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_046': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation: '⭐ 規則：in autumn 是常見季節搭配；during autumn 亦可表示在整個秋季期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_050': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation:
        '⭐ 規則：in the 20th century 是常見寫法；during the 20th century 亦可強調該時期。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_055': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation: '⭐ 規則：in the holidays 和 during the holidays 都可表示在假期期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_056': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'at', 'during'],
    explanation:
        '⭐ 規則：in secondary school 指求學階段；at secondary school 和 during secondary school 在此亦保留同一時期意思。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_057': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation: '⭐ 規則：in spring 是常見季節搭配；during spring 亦可表示在春季期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_058': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation: '⭐ 規則：in December 是常見月份搭配；during December 亦可表示在十二月期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_060': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['in', 'during'],
    explanation:
        '⭐ 規則：in the summer holiday 和 during the summer holiday 都可表示在暑假期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_122': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'on'],
    explanation: '⭐ 規則：during the flight 強調飛行期間；on the flight 亦可表示在該航班旅程中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_123': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the exam 強調考試期間；in the exam 亦可表示在考試之中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_124': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the meeting 強調會議期間；in the meeting 亦可表示在會議進行中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_125': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'at'],
    explanation: '⭐ 規則：during lunchtime 強調整段午飯時間；at lunchtime 亦表示在午飯時段。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_126': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the holiday 和 in the holiday 都可表示在假期期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_127': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the storm 強調暴風雨期間；in the storm 亦可表示身處暴風雨時。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_128': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the lesson 強調課堂期間；in the lesson 亦可表示在該課堂中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_129': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'at'],
    explanation:
        '⭐ 規則：during the performance 強調演出期間；at the performance 亦可指在該演出場合。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_130': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation:
        '⭐ 規則：during the interview 較精準表示整段訪問期間；in the interview 亦可表示在訪問之中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_131': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the blackout 強調停電期間；in the blackout 亦可表示在停電之中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_132': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'at'],
    explanation: '⭐ 規則：during recess 和 at recess 都可表示在小息時段。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_133': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'on'],
    explanation: '⭐ 規則：during the trip 強調旅程期間；on the trip 亦表示在該旅程中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_134': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the quiz 強調測驗期間；in the quiz 亦可表示在該測驗中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_135': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'on'],
    explanation:
        '⭐ 規則：during the summer course 強調課程期間；on the summer course 亦可表示修讀該課程時。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_136': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation: '⭐ 規則：during the match 強調比賽期間；in the match 亦可表示在該場比賽中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_138': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'at'],
    explanation: '⭐ 規則：during dinner 和 at dinner 都可表示在晚飯時段。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_139': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'in'],
    explanation:
        '⭐ 規則：during the fire drill 強調演習期間；in the fire drill 亦可表示在該演習中。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_140': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['during', 'at'],
    explanation: '⭐ 規則：during the concert 強調演唱會期間；at the concert 亦可表示在該演唱會場合。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_177': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['for', 'during'],
    explanation:
        '⭐ 規則：for the whole afternoon 強調持續時間；during the whole afternoon 亦表示整個下午期間。',
  ),
  'PREPOSITION_OF_TIME/preposition_time_180': WorkshopChoiceAnswerOverride(
    acceptedAnswers: ['for', 'during'],
    explanation: '⭐ 規則：for one evening 強調持續一晚；during one evening 亦可表示在某一晚期間。',
  ),
};
