from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "staircase": "樓梯",
    "stale": "不新鮮的／陳舊的",
    "standardise": "使標準化",
    "standardize": "使標準化",
    "starkly": "鮮明地／嚴酷地",
    "startle": "使吃驚",
    "static": "靜態的／靜電的",
    "steely": "鋼鐵般的／冷峻的",
    "stereotype": "刻板印象",
    "sterile": "無菌的／貧瘠的",
    "stew": "燉菜／燉煮",
    "steward": "乘務員／管理員",
    "stewardship": "管理責任",
    "stifle": "抑制／使窒息",
    "stimulation": "刺激",
    "sting": "刺痛／刺",
    "stinger": "刺針",
    "stir": "攪拌／激起",
    "storage": "儲存",
    "strain": "壓力／拉傷",
    "strategic": "策略性的",
    "strew": "散布",
    "stringy": "纖維多的／細長的",
    "strip": "去掉／長條",
    "strive": "努力爭取",
    "structural": "結構的",
    "stumble": "絆倒／失誤",
    "stun": "使震驚／使昏迷",
    "stunt": "特技／阻礙成長",
    "submission": "提交／屈服",
    "subscription": "訂閱",
    "substantial": "大量的／重大的",
    "subtle": "細微的",
    "subtropical": "亞熱帶的",
    "successive": "連續的",
    "sue": "控告",
    "suffocate": "窒息",
    "suitability": "合適性",
    "summarise": "總結",
    "superior": "較好的／上級的",
    "superstitious": "迷信的",
    "supervision": "監督",
    "supplement": "補充／增刊",
    "supportive": "支持的",
    "supposedly": "據說",
    "surge": "激增／湧動",
    "surgical": "外科的",
    "surreptitiously": "偷偷地",
    "susceptible": "易受影響的",
    "suspicion": "懷疑",
    "suspicious": "可疑的",
    "sustain": "維持／承受",
    "sustenance": "食物／維持生命之物",
    "swap": "交換",
    "swarm": "蜂擁而至／群",
    "symbolize": "象徵",
    "syndication": "聯合供稿／節目聯播",
    "synthesize": "合成／綜合",
    "synthetic": "合成的／人造的",
    "tally": "計算總數／記錄",
    "teamwork": "團隊合作",
    "teaser": "預告／吊胃口的東西",
    "tedious": "沉悶乏味的",
    "terminal": "終點站／末期的",
    "termination": "終止",
    "terrain": "地形",
    "terrestrial": "陸地的／地球的",
    "terrific": "極好的",
    "testify": "作證",
    "textile": "紡織品／紡織的",
    "texture": "質地",
    "thoughtful": "體貼的／深思的",
    "thoughtfully": "體貼地／深思地",
    "thread": "線",
    "threshold": "門檻",
    "thrill": "激動／使激動",
    "thrive": "興旺／茁壯成長",
    "thug": "暴徒",
    "tide": "潮汐",
    "tighten": "收緊／加強",
    "timber": "木材",
    "token": "象徵性的東西／代幣",
    "tolerance": "容忍／耐受性",
    "tolerate": "容忍",
    "torture": "折磨／酷刑",
    "toss": "拋擲",
    "toxic": "有毒的",
    "trace": "痕跡／追蹤",
    "trail": "蹤跡／拖曳",
    "trainee": "受訓者",
    "tranquil": "寧靜的",
    "transcribe": "抄寫／轉錄",
    "transcript": "文字稿／成績單",
    "transformation": "轉變",
    "transit": "運輸／過境",
    "transmission": "傳送／傳播",
    "trauma": "創傷",
    "trendy": "時髦的",
    "tribal": "部落的／族群的",
    "trigger": "觸發／扳機",
    "trim": "修剪",
    "trimming": "修剪物／裝飾邊",
    "trip over": "被…絆倒",
    "triumph": "勝利／成功",
    "triumphantly": "得意洋洋地／勝利地",
    "trump": "王牌／勝過",
    "tuition": "學費／教學",
    "tweezers": "鑷子",
    "twist": "扭轉／曲折",
    "ubiquitous": "無處不在的",
    "ubiquity": "無所不在",
    "unanswered": "未回答的",
    "unappreciated": "不被賞識的",
    "unavailable": "無法取得的",
    "unbeatable": "無敵的／非常划算的",
    "unchecked": "未受控制的",
    "uncontacted": "未接觸過的",
    "uncover": "揭露／發現",
    "undecided": "未決定的",
    "underage": "未成年的",
    "underclass": "底層階級",
    "undercover": "臥底的",
    "underfoot": "在腳下／礙事地",
    "undermine": "削弱",
    "undeserving": "不值得的",
    "undocumented": "無證件的／未記錄的",
    "unearth": "發掘／揭露",
    "uneducated": "未受教育的",
    "unending": "無止境的",
    "unfeasible": "不可行的",
    "unforeseen": "未預見的",
    "unify": "統一",
    "uninhabitable": "不適合居住的",
    "unintended": "非故意的",
    "unintentional": "無意的",
    "unintentionally": "無意地",
    "unpaid": "未付款的／無薪的",
    "unprecedented": "前所未有的",
    "unpunished": "未受懲罰的",
    "unquantifiable": "無法量化的",
    "unrealistically": "不切實際地",
    "unspoiled": "未受破壞的",
    "unspoken": "未說出口的",
    "unstick": "使脫離黏住狀態",
    "unveil": "揭幕／公布",
    "unwanted": "不想要的",
    "upcoming": "即將到來的",
    "uproot": "連根拔起",
    "upward": "向上的",
    "urbanization": "城市化",
    "urgency": "緊急",
    "utterly": "完全地",
    "vague": "模糊的",
    "validate": "證實／確認…有效",
    "vanish": "消失",
    "vessel": "船舶／器皿",
    "veteran": "老兵／老手",
    "vibrant": "充滿活力的",
    "vicious": "惡毒的／兇惡的",
    "viciously": "惡狠狠地",
    "victimize": "使受害",
    "villager": "村民",
    "virtue": "美德",
    "vocalization": "發聲／口語表達",
    "vocational": "職業性的",
    "vow": "誓言／發誓",
    "vulnerable": "脆弱的／易受傷害的",
    "ward": "病房／區域",
    "warehouse": "倉庫",
    "warrior": "戰士",
    "weave": "編織",
    "whilst": "同時／雖然",
    "wholly": "完全地",
    "wipe": "擦拭",
    "wisely": "明智地",
    "wit": "機智",
    "wordlessly": "默默地",
    "workout": "鍛鍊",
    "worsen": "惡化",
    "worship": "崇拜",
    "worshipper": "崇拜者／信徒",
    "worthwhile": "值得的",
    "yachtsman": "遊艇駕駛者",
    "yell": "大喊",
    "yield": "產生／讓步",
    "youngster": "年輕人",
    "zoological": "動物學的",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    bank = json.loads(bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(bank_path, bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
