from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "pollinate": "授粉",
    "pollinator": "傳粉者",
    "pond": "池塘",
    "pop": "突然出現／流行樂",
    "portfolio": "作品集／投資組合",
    "portray": "描繪",
    "postpone": "延期",
    "posture": "姿勢／態度",
    "precarious": "不穩定的",
    "precision": "精確",
    "predator": "捕食者",
    "predecessor": "前任／前身",
    "predicament": "困境",
    "prejudice": "偏見",
    "preliminary": "初步的",
    "premier": "首要的／總理",
    "premise": "前提",
    "premium": "高級的／保費",
    "preoccupation": "全神貫注／心事",
    "prescribe": "開處方／規定",
    "prescription": "處方",
    "preservation": "保存／保護",
    "preservationist": "保育主義者",
    "prestigious": "有聲望的",
    "presumably": "大概",
    "presume": "假定",
    "preteen": "青春期前兒童",
    "prettiness": "漂亮",
    "prevail": "盛行／佔上風",
    "primitive": "原始的",
    "principal": "主要的／校長",
    "privilege": "特權／榮幸",
    "problematic": "有問題的",
    "productive": "有成效的",
    "productivity": "生產力",
    "proficient": "熟練的",
    "profound": "深刻的",
    "projection": "投射／預測",
    "proliferation": "擴散／激增",
    "prolong": "延長",
    "prominent": "著名的／突出的",
    "prospective": "預期的／未來的",
    "prosperity": "繁榮",
    "protective": "保護性的",
    "provider": "供應者",
    "province": "省份",
    "provisional": "臨時的",
    "provocative": "挑釁的／發人深省的",
    "provoke": "激起／挑起",
    "prowess": "高超本領",
    "publicize": "宣傳",
    "puddle": "水坑",
    "pulse": "脈搏",
    "puma": "美洲獅",
    "pump": "泵／抽送",
    "punctuality": "守時",
    "punctuate": "加標點／不時打斷",
    "purposefully": "有目的地",
    "query": "疑問／查詢",
    "quota": "配額",
    "rack": "架子／使痛苦",
    "radar": "雷達",
    "radical": "激進的／根本的",
    "radically": "徹底地",
    "raid": "突襲",
    "ramification": "後果／衍生問題",
    "ranch": "大牧場",
    "rational": "理性的",
    "reactionary": "反動的",
    "readership": "讀者群",
    "readily": "欣然地／容易地",
    "realm": "領域",
    "reassure": "使安心",
    "rebellious": "叛逆的",
    "recharge": "充電／恢復精力",
    "recipient": "接收者",
    "recite": "背誦",
    "recognizable": "可辨認的",
    "reconstruct": "重建",
    "reconstruction": "重建",
    "recount": "敘述／重新計算",
    "recurrent": "反覆出現的",
    "reddish": "微紅的",
    "redeem": "贖回／彌補",
    "reflection": "反思／倒影",
    "reform": "改革",
    "refresh": "使恢復精神／刷新",
    "refusal": "拒絕",
    "regain": "重新獲得",
    "regulator": "監管者／調節器",
    "regulatory": "監管的",
    "rehabilitation": "康復／改造",
    "reign": "統治時期／統治",
    "related to": "與…有關",
    "relic": "遺物",
    "reluctance": "不情願",
    "reluctant": "不情願的",
    "reminder": "提醒物／提示",
    "removal": "移除",
    "renew": "更新／續期",
    "renminbi": "人民幣",
    "renovation": "翻新",
    "renowned": "著名的",
    "repeatedly": "反覆地",
    "repressive": "壓制的",
    "reptile": "爬蟲類動物",
    "resemble": "像",
    "residential": "住宅的",
    "resistance": "抵抗",
    "respectful": "尊敬的",
    "respectively": "分別地",
    "restoration": "修復／恢復",
    "resume": "繼續／履歷",
    "rethink": "重新思考",
    "retrieve": "取回",
    "revenge": "報復",
    "reverse": "相反／逆轉",
    "revitalization": "振興",
    "revolutionary": "革命性的／革命者",
    "riddle": "謎語",
    "rip": "撕裂",
    "ripple": "漣漪／產生連鎖反應",
    "ritual": "儀式",
    "rock": "岩石／搖動",
    "rotate": "旋轉",
    "rumour": "謠言",
    "sack": "袋子／解僱",
    "sacrifice": "犧牲",
    "savage": "野蠻的／兇猛的",
    "savagely": "兇狠地",
    "saying": "俗語",
    "scaffold": "鷹架",
    "scandalous": "可恥的／引起公憤的",
    "scarce": "稀少的",
    "scatter": "散開",
    "sceptical": "懷疑的",
    "scholastically": "在學業上",
    "scold": "責罵",
    "scope": "範圍",
    "scrutiny": "仔細審視",
    "seal": "海豹／密封",
    "secretive": "鬼鬼祟祟的／守口如瓶的",
    "seemingly": "表面上",
    "seldom": "很少",
    "sensation": "感覺／轟動",
    "sensitivity": "敏感度",
    "sentiment": "情感／看法",
    "separation": "分離",
    "shameful": "可恥的",
    "shareholder": "股東",
    "shatter": "粉碎",
    "sheer": "純粹的／陡峭的",
    "shoot": "射擊／拍攝",
    "shorten": "縮短",
    "shrine": "聖地／神龕",
    "shrink": "縮小",
    "shrug": "聳肩",
    "shuttle": "穿梭巴士／往返運送",
    "sigh": "嘆氣",
    "signage": "標示系統",
    "silicon": "矽",
    "silliness": "愚蠢",
    "simplify": "簡化",
    "simplistic": "過分簡化的",
    "simulate": "模擬",
    "simultaneously": "同時地",
    "skepticism": "懷疑態度",
    "sketch": "素描／概述",
    "slap": "拍打／耳光",
    "slash": "猛砍／大幅削減",
    "slump": "暴跌／垂頭坐著",
    "smash": "粉碎／猛撞",
    "snap": "啪地折斷／快照",
    "soak": "浸泡",
    "soar": "高飛／猛增",
    "socialist": "社會主義者／社會主義的",
    "societal": "社會的",
    "solace": "安慰",
    "sole": "唯一的／鞋底",
    "solo": "單獨的／獨奏",
    "somber": "陰沉的",
    "sonic": "聲音的／音速的",
    "soothe": "安撫",
    "sophisticate": "使老練／老練的人",
    "sophistication": "精緻／老練",
    "sound": "聲音／健全的",
    "sow": "播種",
    "span": "跨度／持續時間",
    "spare": "多餘的／抽出",
    "spark": "火花／引發",
    "specimen": "樣本",
    "spectacle": "景象／奇觀",
    "spell": "拼寫／一段時間",
    "spin": "旋轉／編造",
    "spindly": "細長脆弱的",
    "sprout": "發芽",
    "spy": "間諜",
    "squeeze": "擠壓",
    "stack": "堆疊",
    "stagnate": "停滯不前",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    bank = json.loads(bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(bank_path, bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
