from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


TRANSLATIONS = {
    "compensatory": "補償性的",
    "complainant": "投訴人／原告",
    "complement": "補足物／補充",
    "complementary": "互補的",
    "complicate": "使複雜化",
    "compost": "堆肥",
    "compostables": "可堆肥物",
    "conceive": "想像／構想",
    "conception": "概念／構想",
    "concession": "讓步",
    "concur": "同意",
    "conducive": "有助於…的",
    "confer": "授予／商議",
    "confidentially": "機密地",
    "confine": "限制／禁閉",
    "confinement": "限制／禁閉",
    "confirmation": "確認",
    "confront": "面對",
    "congestion": "擠塞／堵塞",
    "consciously": "有意識地",
    "consensus": "共識",
    "consent": "同意",
    "conservationist": "保育人士",
    "conserve": "保護／保存",
    "console": "安慰",
    "constitute": "構成",
    "constraint": "限制／約束",
    "constructive": "有建設性的",
    "contamination": "污染",
    "contend": "主張／競爭",
    "contender": "競爭者",
    "content": "內容／滿足的",
    "contentious": "有爭議的",
    "contestant": "參賽者",
    "continually": "持續地",
    "contractor": "承包商",
    "contractual": "合約上的",
    "contradiction": "矛盾",
    "contrary": "相反的",
    "convenor": "召集人",
    "conversion": "轉換／改造",
    "cooperative": "合作的",
    "cop": "警察",
    "copyright": "版權",
    "correction": "改正／修正",
    "correlation": "關聯",
    "correspondence": "通信／對應",
    "correspondent": "記者／通訊者",
    "corrupt": "腐敗的／使腐敗",
    "costly": "昂貴的",
    "counter": "櫃檯／反擊",
    "counteract": "抵消",
    "counterpart": "對應物／對等人物",
    "counterproductive": "適得其反的",
    "countless": "無數的",
    "craft": "工藝／技巧",
    "creator": "創作者",
    "credibility": "可信度",
    "creditworthiness": "信用可靠度",
    "creditworthy": "值得信賴其信用的",
    "cruiser": "巡洋艦",
    "crunch": "嘎吱作響／關鍵時刻",
    "crush": "壓碎／迷戀",
    "crystal": "水晶",
    "cube": "立方體",
    "culprit": "罪魁禍首",
    "cultivate": "培養／栽培",
    "curse": "詛咒",
    "cutting-edge": "尖端的",
    "cynical": "憤世嫉俗的",
    "cynicism": "憤世嫉俗",
    "dab": "輕拍／少量塗抹",
    "debunk": "揭穿",
    "debut": "首次亮相",
    "dedicate": "奉獻／致力於",
    "deem": "視為",
    "defect": "缺陷",
    "deflection": "偏轉／轉移",
    "delicate": "脆弱的／微妙的",
    "delusional": "妄想的",
    "demo": "示範／試用版",
    "dense": "密集的",
    "dependable": "可靠的",
    "depict": "描繪",
    "deplete": "耗盡",
    "deplorable": "糟透的",
    "deploy": "部署",
    "deposit": "存款／沉積物",
    "deprive": "剝奪",
    "descent": "下降／血統",
    "descriptive": "描述性的",
    "designate": "指定",
    "designation": "指定／稱號",
    "destiny": "命運",
    "deteriorate": "惡化",
    "diagnosis": "診斷",
    "diffuse": "擴散／散開",
    "dignify": "使有尊嚴",
    "dimension": "維度／尺寸",
    "diminish": "減少",
    "dimly": "昏暗地／模糊地",
    "disastrous": "災難性的",
    "disbelieve": "不相信",
    "discard": "丟棄",
    "discharge": "排放／出院／解除",
    "disclosure": "披露",
    "discomfort": "不適",
    "discontent": "不滿",
    "discriminate": "歧視／區分",
    "discrimination": "歧視",
    "disdain": "鄙視",
    "disengagement": "脫離／不投入",
    "disinfect": "消毒",
    "disintegrate": "瓦解",
    "dispenser": "分配器",
    "disposal": "處理／處置",
    "dispose": "處理／安排",
    "dispute": "爭議／爭論",
    "disqualification": "取消資格",
    "disrupt": "干擾／擾亂",
    "disruption": "中斷／擾亂",
    "distinction": "區別／榮譽",
    "distinctive": "獨特的",
    "distortion": "扭曲",
    "distraction": "分心事物",
    "distress": "痛苦／困擾",
    "divergent": "分歧的",
    "divert": "轉移",
    "dormitory": "宿舍",
    "dough": "麵團",
    "downfall": "垮台／衰敗",
    "downside": "缺點／不利面",
    "drain": "排走／耗盡",
    "drastic": "激烈的／重大的",
    "drastically": "大幅地",
    "drawback": "缺點",
    "dreary": "沉悶的／陰鬱的",
    "drift": "漂流／逐漸偏移",
    "drill": "鑽孔／演練",
    "drone": "無人機／低沉聲音",
    "droplet": "小滴",
    "drown": "溺死",
    "dub": "取綽號／配音",
    "dumpling": "餃子",
    "duo": "二人組",
    "durable": "耐用的",
    "dweller": "居民",
    "dynamic": "動態的／充滿活力的",
    "dysfunctional": "失靈的／功能失調的",
    "eager": "渴望的",
    "earthen": "陶製的／泥土的",
    "earthly": "塵世的",
    "ease": "緩解／輕鬆",
    "echo": "回聲",
    "ecological": "生態的",
    "edible": "可食用的",
    "educator": "教育工作者",
    "efficiency": "效率",
    "elegance": "優雅",
    "elevate": "提升",
    "elicit": "引出",
    "embark": "開始／上船",
    "embroidery": "刺繡",
    "emergence": "出現",
    "emperor": "皇帝",
    "employable": "具備受聘能力的",
    "empower": "賦權／使有能力",
    "encouragement": "鼓勵",
    "endeavor": "努力／嘗試",
    "endless": "無止境的",
    "endorse": "支持／背書",
    "endure": "忍受／持續",
    "enforce": "執行／強制實施",
    "engagement": "參與／訂婚",
    "enquire": "詢問",
    "enrichment": "充實／豐富化",
    "ensue": "隨之發生",
    "enterprise": "企業／事業",
    "enthusiast": "愛好者",
    "entitle": "給予權利／命名",
    "envelop": "包圍",
    "environmentalist": "環保人士",
    "envisage": "設想／預想",
    "epic": "史詩般的／史詩",
    "equality": "平等",
    "equation": "方程式",
    "escalate": "升級／加劇",
    "establishment": "機構／建立",
    "ethically": "合乎道德地",
    "ethicist": "倫理學者",
    "evacuate": "撤離",
    "evacuation": "撤離",
    "evolutionary": "進化的",
    "exaggerate": "誇大",
    "exaggeration": "誇張",
    "excavate": "挖掘",
    "excavation": "挖掘",
    "excellence": "卓越",
    "exceptional": "卓越的／例外的",
    "excerpt": "摘錄",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    question_bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    question_bank = json.loads(question_bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in question_bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(question_bank_path, question_bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in question_bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
