from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "excess": "過量／過剩",
    "exclusive": "獨家的／專屬的",
    "exclusively": "專門地／僅僅",
    "exhaust": "耗盡／使疲憊",
    "exit": "出口／離開",
    "expat": "僑民",
    "expenditure": "開支",
    "expire": "到期／終止",
    "exploratory": "探索性的",
    "explosive": "爆炸性的／炸藥",
    "extinction": "滅絕",
    "extinguisher": "滅火器",
    "extract": "提取／摘錄",
    "exuberant": "充滿活力的",
    "eyesome": "悅目的",
    "eyesore": "礙眼之物",
    "fable": "寓言",
    "facilitate": "促進／使便利",
    "fade": "褪色／逐漸消失",
    "fascinate": "使著迷",
    "fatal": "致命的",
    "fatally": "致命地",
    "fate": "命運",
    "fatigue": "疲勞",
    "favoritism": "偏袒",
    "ferocious": "兇猛的",
    "fertility": "生育力／肥沃",
    "fertilizer": "肥料",
    "fierce": "激烈的／兇猛的",
    "fierceness": "猛烈",
    "filthy": "骯髒的",
    "fin": "鰭",
    "finalisation": "最終確定",
    "fine": "罰款／精細的",
    "fingertip": "指尖",
    "fit": "適合的／使適合",
    "flair": "天賦／才華",
    "flake": "薄片",
    "flank": "側翼／側面",
    "flashy": "花哨的",
    "flaw": "缺陷",
    "flee": "逃離",
    "fleet": "艦隊／車隊",
    "flesh": "肉體／果肉",
    "flexibility": "靈活性",
    "flick": "輕彈／快速一瞥",
    "flock": "一群／聚集",
    "flourish": "繁榮／茂盛成長",
    "focussed": "專注的",
    "foist": "把…強加於",
    "fondly": "喜愛地",
    "footage": "影片片段",
    "footstep": "腳步聲",
    "foreigner": "外國人",
    "foresee": "預見",
    "formulate": "制定／明確表達",
    "forth": "向前",
    "foster": "促進／培養",
    "foul": "惡臭的／犯規",
    "fracture": "骨折／裂痕",
    "fragile": "脆弱的",
    "frankly": "坦白說",
    "functional": "實用的／功能性的",
    "funeral": "葬禮",
    "funky": "時髦古怪的",
    "fuss": "大驚小怪／忙亂",
    "futuristic": "未來派的",
    "gadget": "小裝置",
    "gastronomic": "美食的",
    "gaze": "凝視",
    "generalize": "概括",
    "glance": "瞥一眼",
    "glimpse": "一瞥",
    "globalist": "全球主義者",
    "gloomy": "陰沉的／令人沮喪的",
    "glorious": "光榮的／壯麗的",
    "glory": "榮耀",
    "grasp": "抓住／理解",
    "gratitude": "感激",
    "grave": "嚴重的／墳墓",
    "grid": "網格／電網",
    "grimmer": "更嚴峻的",
    "grimness": "冷酷／嚴峻",
    "grin": "露齒而笑",
    "grind": "磨碎／辛苦工作",
    "gross": "總的／噁心的",
    "grower": "種植者",
    "gruel": "稀粥",
    "grumble": "抱怨",
    "guidance": "指導",
    "gulp": "大口吞嚥",
    "habitable": "適合居住的",
    "hairy": "多毛的",
    "halt": "停止",
    "hamper": "妨礙／有蓋大籃子",
    "handful": "一把／少數",
    "handiwork": "手工藝品",
    "handy": "方便的／有用的",
    "harmonious": "和諧的",
    "harsh": "嚴厲的／刺耳的",
    "harsher": "更嚴厲的",
    "harvest": "收成／收穫",
    "hatred": "仇恨",
    "hazard": "危險",
    "headphone": "耳機",
    "headset": "頭戴式耳機",
    "hearty": "熱情的／豐盛的",
    "heave": "用力舉起／起伏",
    "helplessly": "無助地",
    "herbal": "草本的",
    "herd": "獸群",
    "heritage": "文化遺產",
    "heroine": "女主角",
    "heyday": "全盛時期",
    "hint": "提示／暗示",
    "honeycomb": "蜂巢",
    "hook": "鉤子／吸引人的點",
    "hoop": "環／圈",
    "hopeful": "有希望的",
    "horizontal": "水平的",
    "hospitalization": "住院治療",
    "hotshot": "能手／大人物",
    "hue": "色調",
    "humanity": "人類／人性",
    "humanize": "使人性化",
    "humble": "謙卑的",
    "hygiene": "衛生",
    "idiot": "笨蛋",
    "idol": "偶像",
    "illuminate": "照亮／闡明",
    "illustrative": "說明性的",
    "immense": "巨大的",
    "immerse": "使沉浸於",
    "impart": "傳授／給予",
    "imperfect": "不完美的",
    "implementation": "執行／實施",
    "imposture": "冒充／欺詐",
    "imprint": "印記／使留下印象",
    "imprison": "監禁",
    "improbable": "不大可能的",
    "improvisation": "即興創作",
    "impulse": "衝動",
    "inability": "無能力",
    "inadequate": "不足的",
    "inappropriate": "不恰當的",
    "inaugural": "就職的／開幕的",
    "incapable": "無能力的",
    "incidence": "發生率",
    "incinerator": "焚化爐",
    "incite": "煽動",
    "inclusion": "包含／包容",
    "inclusive": "包容的／包括一切的",
    "indicator": "指標",
    "indictment": "起訴／控告",
    "indigenous": "本土的／土著的",
    "indispensables": "不可缺少之物",
    "individualistic": "個人主義的",
    "induce": "導致／誘導",
    "ineffectual": "無效的",
    "inefficient": "效率低的",
    "inequality": "不平等",
    "influential": "有影響力的",
    "informative": "有資訊性的",
    "ingrain": "使根深蒂固",
    "initiate": "發起／開始",
    "inject": "注射／注入",
    "injection": "注射",
    "injustice": "不公正",
    "innocuous": "無害的",
    "inquirer": "詢問者",
    "insider": "內部人士",
    "inspect": "檢查",
    "inspection": "檢查",
    "inspiration": "靈感",
    "instruct": "指示／教導",
    "instrumental": "有幫助的／器樂的",
    "insufficient": "不足的",
    "insult": "侮辱",
    "insure": "投保",
    "intact": "完好無損的",
    "intake": "攝取量",
    "integral": "不可或缺的",
    "intellectual": "知識分子／理智的",
    "intensively": "密集地",
    "intent": "意圖／專注的",
    "intently": "專注地",
    "interactive": "互動的",
    "interfere": "干涉／妨礙",
    "interim": "臨時的",
    "intermediate": "中級的／中間的",
    "interrelate": "相互關聯",
    "intervene": "介入",
    "intervention": "介入／干預",
    "intimacy": "親密",
    "intrepid": "無畏的",
    "invisible": "看不見的",
    "involvement": "參與",
    "invulnerable": "無懈可擊的／刀槍不入的",
    "ironic": "諷刺的",
    "ironically": "諷刺地",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    bank = json.loads(bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(bank_path, bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
