from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "abortion": "墮胎",
    "absence": "缺席／缺乏",
    "absorption": "吸收",
    "abstractly": "抽象地",
    "absurd": "荒謬的",
    "absurdity": "荒謬",
    "academy": "學院",
    "accelerate": "加速",
    "acceptance": "接受",
    "accessible": "可到達的／易於使用的",
    "acclaim": "稱讚／讚譽",
    "accomplishment": "成就",
    "accusation": "指控",
    "acid": "酸",
    "acknowledgment": "承認／確認",
    "activist": "行動派／社會運動人士",
    "addictive": "令人上癮的",
    "adhere": "堅持遵守／黏附",
    "administer": "管理／施行",
    "administrator": "管理人員／行政人員",
    "admission": "承認／入場許可",
    "adolescent": "青少年",
    "adoption": "採用／收養",
    "adorn": "裝飾",
    "adverse": "不利的",
    "adversity": "逆境",
    "advocate": "提倡者／提倡",
    "aerial": "空中的",
    "aesthetic": "美學的／美感的",
    "affection": "喜愛／感情",
    "affirm": "確認／堅稱",
    "affluent": "富裕的",
    "afresh": "重新",
    "afterlife": "來世",
    "aftermath": "後果／餘波",
    "aggregate": "總計／合計",
    "agony": "極度痛苦",
    "agricultural": "農業的",
    "airborne": "空運的／空中的",
    "albeit": "雖然",
    "algae": "藻類",
    "algorithm": "演算法",
    "algorithmic": "演算法的",
    "alien": "外星人／陌生的",
    "align": "使一致／對齊",
    "alligator": "短吻鱷",
    "altruistic": "利他的",
    "alumnus": "男校友／畢業生",
    "amateur": "業餘愛好者",
    "amateurish": "業餘的／不專業的",
    "amazonian": "亞馬遜的",
    "ambassador": "大使",
    "amid": "在…之中",
    "analogy": "類比",
    "angel": "天使",
    "anonymous": "匿名的",
    "antidote": "解藥",
    "apparatus": "器械／裝置",
    "applause": "掌聲",
    "appliance": "器具／家電",
    "applicable": "適用的",
    "appoint": "任命",
    "appraisal": "評估",
    "appreciation": "欣賞／感激",
    "aptitude": "天資／才能",
    "aquarium": "水族館／魚缸",
    "aquatic": "水生的",
    "arc": "弧形／弧線",
    "arcade": "拱廊／電子遊戲場",
    "archaeologist": "考古學家",
    "architectural": "建築的",
    "archive": "檔案館／存檔",
    "arduous": "艱鉅的",
    "arena": "競技場",
    "arm": "武裝／裝備",
    "armour": "盔甲",
    "array": "排列／一系列",
    "arthritis": "關節炎",
    "aspiration": "抱負",
    "aspire": "渴望／立志",
    "assemble": "組裝／集合",
    "assort": "分類",
    "astonishingly": "令人驚訝地",
    "astronomer": "天文學家",
    "atomize": "使霧化／使粉碎",
    "attain": "達到",
    "attendance": "出席人數／出席",
    "audition": "試鏡／試音",
    "authentic": "真實的／地道的",
    "authoritarianism": "威權主義",
    "authorize": "授權",
    "autonomy": "自治／自主權",
    "availability": "可用性",
    "averse": "反感的",
    "avid": "熱衷的",
    "await": "等待",
    "awaken": "喚醒",
    "backdrop": "背景",
    "backhands": "反手擊球",
    "bail": "保釋金／保釋",
    "bankruptcy": "破產",
    "bare": "赤裸的／空無的",
    "batter": "麵糊／猛擊",
    "bay": "海灣",
    "beast": "野獸",
    "beekeeper": "養蜂人",
    "befall": "降臨於／發生在",
    "behemoth": "龐然大物",
    "beholder": "觀看者",
    "bellaneil": "貝拉尼爾",
    "bellow": "怒吼",
    "bench": "長椅／法官席",
    "beneath": "在…下面",
    "bilingual": "雙語的",
    "bind": "綑綁／約束",
    "biography": "傳記",
    "biomedical": "生物醫學的",
    "birdshot": "鉛砂",
    "bizarre": "離奇的",
    "blast": "爆炸／衝擊波",
    "bleed": "流血",
    "blend": "混合",
    "blindness": "失明",
    "blockbuster": "大片／轟動作品",
    "boom": "繁榮／激增",
    "bootstrap": "引導程式／自力更生",
    "boundary": "邊界",
    "breach": "違反／突破",
    "breakage": "破損",
    "breakthrough": "突破",
    "breed": "繁殖／品種",
    "browser": "瀏覽器",
    "brutal": "殘酷的",
    "buck": "雄鹿／一元",
    "buddy": "好友／夥伴",
    "bulk": "體積／大部分",
    "bully": "欺凌者／欺負",
    "burden": "負擔",
    "burial": "埋葬",
    "burst": "爆裂／突然爆發",
    "bustle": "忙碌喧鬧",
    "butt": "屁股／末端",
    "bylines": "署名欄",
    "calculation": "計算",
    "cancellation": "取消",
    "canine": "犬的／犬科動物",
    "canoe": "獨木舟",
    "capability": "能力",
    "capitalism": "資本主義",
    "capitalist": "資本家／資本主義的",
    "captivate": "迷住",
    "captive": "被囚禁的／俘虜",
    "captivity": "囚禁",
    "careerist": "事業至上者",
    "carpenter": "木匠",
    "carriage": "馬車／車廂",
    "carve": "雕刻",
    "catalyst": "催化劑／促成因素",
    "cater": "迎合／提供飲食",
    "caterer": "餐飲供應商",
    "caterpillar": "毛毛蟲",
    "caution": "小心／警告",
    "cautionary": "警示性的",
    "cease": "停止",
    "ceaselessly": "不停地",
    "chaos": "混亂",
    "characterize": "描繪…特徵／使具有特徵",
    "charm": "魅力／使著迷",
    "cheesy": "俗氣的／芝士味的",
    "chiefly": "主要地",
    "childbearing": "生育",
    "childishness": "幼稚",
    "choke": "窒息／哽住",
    "circulate": "流通／傳播",
    "civic": "公民的／城市的",
    "clash": "衝突",
    "clay": "黏土",
    "cling": "緊抓／依附",
    "cling to": "堅守／緊抓住",
    "clinical": "臨床的／冷靜客觀的",
    "clout": "影響力",
    "clover": "三葉草",
    "cognitive": "認知的",
    "coincide": "同時發生／相符",
    "collaborate": "合作",
    "collective": "集體的／集體",
    "collide": "碰撞",
    "collision": "碰撞",
    "colonial": "殖民地的",
    "columnist": "專欄作家",
    "comet": "彗星",
    "commentary": "評論",
    "commentator": "評論員",
    "commodifiable": "可商品化的",
    "communist": "共產主義者／共產主義的",
    "companion": "同伴",
    "comparatively": "相對地／比較而言",
    "compel": "迫使",
    "compensate": "補償",
    "compensation": "補償",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    question_bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    question_bank = json.loads(question_bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in question_bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(question_bank_path, question_bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in question_bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
