from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "irony": "諷刺",
    "itinerary": "行程",
    "journalistic": "新聞報導的",
    "junk": "廢物／垃圾",
    "justly": "公正地",
    "knob": "旋鈕",
    "knowledgeable": "知識豐富的",
    "labrador": "拉布拉多犬",
    "lament": "哀嘆",
    "lander": "著陸器",
    "landmark": "地標",
    "lap": "一圈／膝部",
    "latter": "後者",
    "lawyerly": "像律師般的",
    "leap": "跳躍",
    "legendary": "傳奇的",
    "legitimate": "合法的／合理的",
    "lengthy": "冗長的",
    "lever": "槓桿",
    "leverage": "影響力／槓桿作用",
    "liability": "責任／負債",
    "liable": "有責任的／易於…的",
    "liberal": "開明的／自由派的",
    "license": "牌照／許可",
    "lifelike": "栩栩如生的",
    "lifelong": "終身的",
    "likelihood": "可能性",
    "limelight": "矚目焦點",
    "listing": "清單／上市",
    "literacy": "識字能力",
    "liven": "使活躍",
    "lobby": "大堂／遊說",
    "locale": "地區",
    "log": "紀錄／原木",
    "logic": "邏輯",
    "loneliness": "孤獨",
    "loom": "隱約出現／織布機",
    "lounge": "休息室",
    "lush": "茂盛的",
    "machinery": "機械設備",
    "magical": "神奇的",
    "mainland": "大陸",
    "mainstream": "主流的",
    "maintenance": "維修／保養",
    "mammal": "哺乳類動物",
    "mandatory": "強制性的",
    "manic": "狂躁的",
    "manipulate": "操控",
    "marine": "海洋的／海軍陸戰隊員",
    "markedly": "明顯地",
    "marshal": "元帥／整頓",
    "martian": "火星的／火星人",
    "marvel": "奇蹟／驚嘆",
    "mask": "面具／掩飾",
    "mastermind": "策劃者／策劃",
    "mat": "墊子",
    "materialize": "實現／顯現",
    "mature": "成熟的／成熟",
    "maximize": "使最大化",
    "meaningful": "有意義的",
    "meantime": "其間",
    "meditation": "冥想",
    "melody": "旋律",
    "memo": "備忘錄",
    "memoir": "回憶錄",
    "mender": "修補工人",
    "mentors": "導師們",
    "mercedes": "平治",
    "merchandise": "商品",
    "merely": "僅僅",
    "merit": "優點／值得",
    "methane": "甲烷",
    "microorganism": "微生物",
    "migration": "遷徙／移民",
    "militant": "激進的／激進分子",
    "mince": "切碎",
    "mindblowing": "令人震撼的",
    "minimise": "使最小化",
    "minimize": "使最小化",
    "miracle": "奇蹟",
    "misconception": "誤解",
    "misfortune": "不幸",
    "mislead": "誤導",
    "misstep": "失誤",
    "misuse": "濫用",
    "monochrome": "單色的",
    "monoculture": "單一栽培",
    "monologue": "獨白",
    "moor": "荒野／停泊",
    "morality": "道德",
    "motivational": "激勵的",
    "motivator": "激勵者",
    "motive": "動機",
    "mould": "模具／塑造／霉菌",
    "mound": "土堆",
    "mournful": "哀傷的",
    "mutual": "相互的",
    "nationwide": "全國性的",
    "neon": "霓虹燈／氖",
    "nest": "巢",
    "net": "淨值／網",
    "neutralize": "中和／使無效",
    "newsagent": "報刊亭老闆",
    "newsletter": "電子通訊／簡報",
    "niche": "利基市場／合適位置",
    "nightly": "每夜的／每晚地",
    "nocturnal": "夜間活動的",
    "nod": "點頭",
    "nonetheless": "儘管如此",
    "nonsense": "胡說／荒謬",
    "noon": "中午",
    "notably": "尤其／值得注意地",
    "notorious": "臭名昭著的",
    "novel": "新穎的／小說",
    "nudge": "輕推／促使",
    "numb": "麻木的",
    "oasis": "綠洲",
    "obsess": "使著迷",
    "occasional": "偶爾的",
    "occupant": "住戶／佔用者",
    "occurrence": "發生事件",
    "odds": "機會／賠率",
    "offense": "冒犯／進攻",
    "officially": "正式地",
    "offspring": "後代",
    "oldie": "老歌／老東西",
    "omission": "遺漏",
    "onlooker": "旁觀者",
    "onward": "向前",
    "oppression": "壓迫",
    "opt": "選擇",
    "oral": "口頭的",
    "orca": "虎鯨",
    "orchard": "果園",
    "orchid": "蘭花",
    "organizational": "組織上的",
    "originate": "起源於",
    "ostracize": "排斥",
    "outgunned": "火力不及的",
    "outing": "短途出遊",
    "outlet": "出口／銷售點",
    "outlook": "前景／觀點",
    "outnumber": "數量上超過",
    "outrage": "憤怒／暴行",
    "outskirt": "市郊／邊緣",
    "outweigh": "比…更重要",
    "overdeveloping": "過度開發的",
    "overdue": "逾期的",
    "overjoy": "使欣喜若狂",
    "overkill": "做得過火",
    "overlook": "忽略／俯瞰",
    "overly": "過度地",
    "overreaction": "反應過度",
    "overshadow": "使相形失色／遮蔽",
    "overstate": "誇大",
    "overstep": "越界",
    "overt": "公開的／明顯的",
    "overtake": "超越／追上",
    "overview": "概覽",
    "overwhelm": "壓倒／使不知所措",
    "oxygenate": "使氧化／供氧",
    "paradise": "天堂／樂園",
    "parental": "父母的",
    "patch": "補丁／小塊",
    "pathway": "路徑",
    "patron": "顧客／贊助人",
    "patronize": "光顧／居高臨下對待",
    "pavilion": "亭／展館",
    "peak": "高峰",
    "peddler": "小販",
    "pedestrianizing": "步行區化",
    "pending": "待定的",
    "penetrate": "穿透",
    "pensioner": "領退休金者",
    "perfection": "完美",
    "peril": "危險",
    "peripheral": "外圍的／次要的",
    "persimmon": "柿子",
    "persuasive": "有說服力的",
    "peruvian": "秘魯的／秘魯人",
    "philosophical": "哲學的",
    "physician": "醫生",
    "piercings": "穿孔飾品",
    "pioneer": "先驅",
    "pip": "果核／小種子",
    "pipeline": "管道／渠道",
    "pirate": "海盜／盜版者",
    "pit": "坑",
    "pitfall": "陷阱",
    "plaster": "石膏／灰泥",
    "plead": "懇求／申辯",
    "pleasurable": "令人愉快的",
    "pledge": "承諾／保證",
    "plummet": "暴跌",
    "plunge": "猛跌／投入",
    "pointless": "毫無意義的",
    "pole": "柱／極地",
    "politically": "政治上地",
    "poll": "民意調查／投票",
    "pollen": "花粉",
}


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    bank_path = ROOT / "question_bank_c1.json"
    translations_path = ROOT / "c1_ch_translations.json"
    missing_csv_path = ROOT / "question_bank_c1_missing_chinese.csv"

    bank = json.loads(bank_path.read_text(encoding="utf-8"))
    translations = json.loads(translations_path.read_text(encoding="utf-8"))
    translations.update(TRANSLATIONS)

    for entry in bank:
        word = entry.get("word")
        if word in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[word]

    write_json(bank_path, bank)
    translations_path.write_text(
        json.dumps(translations, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with missing_csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["word", "cefr"])
        for entry in bank:
            ch = entry.get("ch") or ""
            if not ch.strip() or set(ch.strip()) <= set("?"):
                writer.writerow([entry["word"], entry["cefr"]])


if __name__ == "__main__":
    main()
