from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "glow": "發光／光彩",
    "glut": "供過於求／充斥",
    "grandiose": "浮誇宏大的",
    "grapple": "搏鬥／努力解決",
    "grotesque": "怪誕的／荒謬的",
    "guise": "偽裝／外表",
    "hapless": "倒霉的／無助的",
    "harbinger": "先兆／預兆",
    "haul": "拖／搬運／收穫量",
    "hay": "乾草",
    "headhunter": "獵頭／招聘專員",
    "heap": "堆／大量",
    "heather": "石楠花",
    "hedonism": "享樂主義",
    "hippocratic": "希波克拉底的／醫德的",
    "hipster": "嬉皮雅痞／潮人",
    "hive": "蜂巢",
    "homeopathy": "順勢療法",
    "homey": "溫馨如家的",
    "homogeneity": "同質性",
    "hop": "跳躍／快速移動",
    "hornet": "大黃蜂",
    "howl": "嚎叫／呼嘯",
    "huff": "氣呼呼地走開／惱怒",
    "humbly": "謙卑地",
    "hunch": "直覺／預感",
    "idolatry": "偶像崇拜",
    "ignorant": "無知的",
    "immortal": "不朽的／永生的",
    "impeccably": "無可挑剔地",
    "impede": "阻礙",
    "impressionable": "易受影響的",
    "inclement": "惡劣的（天氣）",
    "incongruity": "不協調／不一致",
    "indebted to": "感激／欠…情",
    "indispensable": "不可或缺的",
    "indoctrinate": "灌輸思想",
    "infancy": "嬰兒期／初期",
    "infectious": "傳染性的／有感染力的",
    "infinite": "無限的",
    "infuriate": "使暴怒",
    "infuse": "注入／使充滿",
    "ingenuity": "巧思／創造力",
    "ingratiate": "迎合討好",
    "inhabit": "居住於／棲息於",
    "inscrutable": "高深莫測的",
    "instigate": "煽動／促成",
    "intertwine": "交織／纏繞",
    "intolerable": "無法容忍的",
    "intricately": "錯綜複雜地",
    "intrigue": "陰謀／引起興趣",
    "intrinsic": "內在的／本質的",
    "intruder": "闖入者",
    "intuition": "直覺",
    "invariably": "總是／不變地",
    "invincibility": "無敵／不可戰勝",
    "iteration": "反覆／迭代",
    "itinerant": "巡迴的／流動的",
    "janitor": "管理員／看守人",
    "jerk": "混蛋／猛拉",
    "judgment": "判斷／裁決",
    "juggle": "耍弄／兼顧",
    "klaxon": "警報器",
    "knot": "結／糾結",
    "labyrinth": "迷宮",
    "lackluster": "乏味的／暗淡的",
    "lacquer": "漆／給…上漆",
    "lacrosse": "長曲棍球",
    "lair": "巢穴／藏身處",
    "lame": "跛的／無力的",
    "lancet": "柳葉刀",
    "landowner": "地主／土地擁有人",
    "languish": "衰弱／萎靡不振",
    "leaping": "跳躍的／飛躍的",
    "legalities": "法律程序／法律細節",
    "linen": "亞麻布／亞麻製品",
    "lingonberry": "越橘",
    "lodge": "小屋／正式提出",
    "long for": "渴望",
    "longevity": "長壽／持久",
    "lull": "平靜期／使平靜",
    "lump": "塊狀物／腫塊",
    "lunatic": "瘋子／極愚蠢的人",
    "lurk": "潛伏／埋伏",
    "magpie": "喜鵲",
    "malicious": "惡意的",
    "maltese": "馬耳他的／馬耳他人",
    "mar": "損害／玷污",
    "marian": "聖母瑪利亞的",
    "marital": "婚姻的",
    "masonry": "石工／磚石建築",
    "maximise": "使最大化",
    "meddle": "干涉／插手",
    "melancholic": "憂鬱的",
    "microbial": "微生物的",
    "mighty": "強大的",
    "millennium": "千禧年／一千年",
    "mingle": "混合／交際",
    "miniature": "微型的／縮小模型",
    "miniscule": "極小的",
    "miraculously": "奇蹟般地",
    "misfit": "不合群的人／不合適的東西",
    "mishap": "小災禍／意外",
    "moan": "呻吟／抱怨",
    "mojo": "魅力／魔力",
    "molehill": "鼴鼠丘／小土堆",
    "monetise": "使貨幣化／從…獲利",
    "moreish": "令人越吃越想吃的",
    "mortal": "凡人的／致命的",
    "motif": "主題／圖案",
    "nauseate": "使作嘔",
    "nectar": "花蜜／甘露",
    "negligent": "疏忽的／玩忽職守的",
    "nosh": "小吃／吃點東西",
    "nostril": "鼻孔",
    "obliterate": "抹去／徹底摧毀",
    "obscure": "模糊的／鮮為人知的",
    "observant": "善於觀察的",
    "offset": "抵消／補償",
    "openness": "開放／坦率",
    "opine": "發表意見",
    "orphan": "孤兒",
    "ossify": "骨化／僵化",
    "outlandish": "古怪離奇的",
    "outright": "徹底地／公然地",
    "overarching": "全面的／首要的",
    "overflow": "溢出／滿溢",
    "overlord": "霸主／領主",
    "pagan": "異教徒的／異教徒",
    "palette": "調色板／色彩範圍",
    "pander": "迎合／縱容",
    "paparazzi": "狗仔隊",
    "paperback": "平裝書",
    "parasocial": "擬社會關係的",
    "particle": "微粒／粒子",
    "pastime": "消遣／娛樂",
    "patina": "銅綠／表面光澤",
    "peek": "偷看／窺視",
    "pendulum": "鐘擺",
    "perceptive": "敏銳的／有洞察力的",
    "perseverance": "毅力／堅持不懈",
    "persistence": "持續／堅持",
    "personhood": "人格／個體身分",
    "persuasion": "說服／信仰",
    "pertinent": "相關的／中肯的",
    "peruse": "細讀／審閱",
    "pervade": "瀰漫／充斥",
    "pharmaceutical": "製藥的／藥物",
    "pigment": "色素／顏料",
    "pinnacle": "頂峰／巔峰",
    "pious": "虔誠的／假虔誠的",
    "plough": "犁／耕作",
    "pluck": "拔／勇氣",
    "ply": "定期往返／不斷供應",
    "poise": "鎮定／優雅",
    "ponder": "沉思／仔細考慮",
    "porch": "門廊",
    "posit": "假定／提出",
    "poultry": "家禽",
    "pragmatic": "務實的",
    "premeditate": "預先策劃",
    "pretties": "漂亮小物件／裝飾品",
    "procession": "隊伍／行列",
    "procurement": "採購／取得",
    "propel": "推進／驅使",
    "propensity": "傾向／習性",
    "protagonist": "主角",
    "protestation": "抗議／聲稱",
    "proverbially": "眾所周知地",
    "provocation": "挑釁／刺激",
    "psyche": "心靈／精神",
    "psychopath": "精神病態者",
    "puncture": "刺穿／穿孔",
    "purge": "清除／清洗",
    "pushy": "咄咄逼人的",
    "quaint": "古雅的／別緻的",
    "quilt": "被子",
    "quiver": "顫抖／箭袋",
    "rabid": "狂熱的／狂犬病的",
    "rag": "破布／抹布",
    "rake in": "大量賺取",
    "ramp up": "提高／加快",
    "raucous": "刺耳吵鬧的",
    "reap": "收割／獲得",
    "receptive": "樂於接受的",
    "redundant": "多餘的／被裁員的",
    "refine": "改進／提煉",
    "relentless": "無情的／持續不斷的",
    "relentlessly": "不懈地／無情地",
    "reliance": "依賴",
    "relish": "享受／滋味",
    "remnant": "殘餘物／殘存部分",
    "rep": "代表／聲譽",
    "repellent": "令人厭惡的／驅蟲劑",
    "reprehensible": "應受譴責的",
    "reprieve": "緩刑／暫時解脫",
    "resemblance": "相似",
    "resentment": "憤恨／怨恨",
    "resiliency": "復原力／彈性",
    "retailer": "零售商",
}


def main() -> None:
    bank_path = ROOT / "question_bank_c2.json"
    missing_path = ROOT / "question_bank_c2_missing_chinese.csv"
    translations_path = ROOT / "c2_ch_translations.json"

    with bank_path.open("r", encoding="utf-8") as f:
        bank = json.load(f)

    for entry in bank:
        if entry["word"] in TRANSLATIONS:
            entry["ch"] = TRANSLATIONS[entry["word"]]

    with bank_path.open("w", encoding="utf-8") as f:
        json.dump(bank, f, ensure_ascii=False, indent=2)
        f.write("\n")

    rows = [
        {"word": entry["word"], "cefr": entry.get("cefr", "")}
        for entry in bank
        if not (entry.get("ch") or "").strip()
    ]
    with missing_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["word", "cefr"])
        writer.writeheader()
        writer.writerows(rows)

    existing = {}
    if translations_path.exists():
        existing = json.loads(translations_path.read_text(encoding="utf-8"))
    existing.update(TRANSLATIONS)
    translations_path.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
